# **Start Section:**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install git+https://github.com/DaneshSelwal/treeffuser.git

Collecting git+https://github.com/DaneshSelwal/treeffuser.git
  Cloning https://github.com/DaneshSelwal/treeffuser.git to /tmp/pip-req-build-thyjild1
  Running command git clone --filter=blob:none --quiet https://github.com/DaneshSelwal/treeffuser.git /tmp/pip-req-build-thyjild1
  Resolved https://github.com/DaneshSelwal/treeffuser.git to commit 9717581990db9e7dedaa8c593ec724997e52bdb8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: einops<0.9.0,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (0.8.2)
Collecting jaxtyping<0.3.0,>=0.2.19 (from treeffuser==0.1.3)
  Downloading jaxtyping-0.2.38-py3-none-any.whl.metadata (6.6 kB)
Collecting lightgbm==4.3.0 (from treeffuser==0.1.3)
  Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
Collecting ml-collections<0.2.0,>=0.1.1 (from treeffuser==0.1.3)
  Downloading ml_collections-0.1.1.tar.gz (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy<2.0,>=1.24 (from treeffuser==0.1.3)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (2.2.2)
Collecting scikit-learn==1.5.0 (from treeffuser==0.1.3)
  Downloading scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy<2.0,>=1.13 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (1.16.3)
Requirement already satisfied: tqdm<5.0.0,>=4.66.4 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (3.6.0)
Collecting wadler-lindig>=0.1.3 (from jaxtyping<0.3.0,>=0.2.19->treeffuser==0.1.3)
  Downloading wadler_lindig-0.1.7-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (6.0.3)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.17.0)
Collecting contextlib2 (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3)
  Downloading contextlib2-21.6.0-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2025.3)
Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 42.8 MB/s eta 0:00:00
Downloading scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 77.3 MB/s eta 0:00:00
Downloading jaxtyping-0.2.38-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 4.4 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 46.4 MB/s eta 0:00:00
Downloading wadler_lindig-0.1.7-py3-none-any.whl (20 kB)
Downloading contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)
Building wheels for collected packages: treeffuser, ml-collections
  Building wheel for treeffuser (pyproject.toml) ... done
  Created wheel for treeffuser: filename=treeffuser-0.1.3-py3-none-any.whl size=27753 sha256=e5c45049e71a049243495589832658896796e7f9fb131f77f0156dc2dbdc7232
  Stored in directory: /tmp/pip-ephem-wheel-cache-91mrw7we/wheels/5f/d1/1a/e628d7eb76d35fc5915026a0d96591b38160a883cc5a7d2116
  Building wheel for ml-collections (setup.py) ... done
  Created wheel for ml-collections: filename=ml_collections-0.1.1-py3-none-any.whl size=94507 sha256=263c33ee6e5402579a92afb1334d0410f62e514f5ef04488f1a647f531a7eeac
  Stored in directory: /root/.cache/pip/wheels/3e/53/7b/1a6f4bfa9dac09618feedc8b1f28a55d4ab9d4bb8835dc0b7e
Successfully built treeffuser ml-collections
Installing collected packages: wadler-lindig, numpy, contextlib2, ml-collections, jaxtyping, scikit-learn, lightgbm, treeffuser
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 4.6.0
    Uninstalling lightgbm-4.6.0:
      Successfully uninstalled lightgbm-4.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed contextlib2-21.6.0 jaxtyping-0.2.38 lightgbm-4.3.0 ml-collections-0.1.1 numpy-1.26.4 scikit-learn-1.5.0 treeffuser-0.1.3 wadler-lindig-0.1.7

In [ ]:
import os
os.environ["PIP_CONSTRAINT"] = "/tmp/numpy_constraint.txt"
!echo "numpy==1.26.4" > /tmp/numpy_constraint.txt

!pip uninstall -y torch torchaudio torchvision \
    torchao torchcodec torchdata torchtune torchsummary -q 2>/dev/null

!pip uninstall -y tensorflow tensorflow-text tensorflow-hub tf-keras \
    tensorflow_decision_forests tensorflow-probability \
    tensorflow-datasets tensorflow-metadata -q 2>/dev/null

!pip uninstall -y numpy scikit-learn shap xgboost lightgbm dask \
    seaborn plotly openpyxl Cython catboost interpret lime -q 2>/dev/null

!pip install numpy==1.26.4 -q
!pip install scikit-learn==1.6.1 -q
!pip install torch==2.9.0 -q

!pip install lightgbm==4.6.0 -q
!pip install xgboost==3.1.2 -q
!pip install catboost==1.2.8 -q
!pip install gpboost==1.6.1 -q
!pip install ngboost==0.5.8 -q
!pip install pgbm==2.2.0 -q
!pip install pytorch-tabnet2==4.5.3 -q

!pip install bayesian-optimization==3.2.0 -q
!pip install optuna==4.6.0 -q
!pip install optunahub==0.4.0 -q
!pip install cmaes==0.12.0 -q

!pip install shap==0.44.0 -q
!pip install lime==0.2.0.1 -q
!pip install interpret==0.7.4 -q

!pip install mapie==0.6.0 -q
!pip install puncc==0.8.0 -q
!pip install skorch==1.3.1 -q
!pip install properscoring==0.1 -q

!pip install dask[dataframe]==2025.12.0 -q
!pip install cython==3.0.12 -q
!pip install seaborn==0.13.2 -q
!pip install plotly==5.24.1 -q
!pip install kaleido==1.2.0 -q
!pip install openpyxl==3.1.5 -q
!pip install XlsxWriter==3.2.9 -q
!pip install cp==2020.12.3 -q

!pip install numpy==1.26.4 --force-reinstall --no-deps -q

os._exit(0)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, which is not installed.
treeffuser 0.1.3 requires scikit-learn==1.5.0, which is not installed.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
umap-learn 0.5.11 requires scikit-learn>=1.6, which is not installed.
geemap 0.35.3 requires plotly, which is not installed.
pysal 25.7 requires scikit-learn>=1.1, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
esda 2.8.1 requires scikit-learn>=1.4, which is not installed.
segregation 2.5.3 requires scikit-learn>=0.21.3, which is not installed.
segregation 2.5.3 requires seaborn, which is not installed.
sentence-transformers 5.2.3 requires scikit-learn, which is not installed.
sentence-transformers 5.2.3 requires torch>=1.11.0, which is not installed.
mapclassify 2.10.0 requires scikit-learn>=1.4, which is not installed.
pynndescent 0.6.0 requires scikit-learn>=0.18, which is not installed.
accelerate 1.12.0 requires torch>=2.0.0, which is not installed.
spopt 0.7.0 requires scikit-learn>=1.4.0, which is not installed.
missingno 0.5.2 requires seaborn, which is not installed.
sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.
cufflinks 0.17.3 requires plotly>=4.1.1, which is not installed.
libpysal 4.14.1 requires scikit-learn>=1.4.0, which is not installed.
keras-hub 0.21.1 requires tensorflow-text; platform_system != "Windows", which is not installed.
imbalanced-learn 0.14.1 requires scikit-learn<2,>=1.4.2, which is not installed.
yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.
fastai 2.8.7 requires scikit-learn, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
peft 0.18.1 requires torch>=1.13.0, which is not installed.
giddy 2.3.8 requires seaborn, which is not installed.
hdbscan 0.8.41 requires scikit-learn>=1.6, which is not installed.
tsfresh 0.21.1 requires scikit-learn>=0.22.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow>=2.2.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow-probability>=0.13.0, which is not installed.
dopamine-rl 4.1.2 requires tf-keras>=2.18.0, which is not installed.
spreg 1.8.5 requires scikit-learn>=0.22, which is not installed.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 69.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, which is not installed.
segregation 2.5.3 requires seaborn, which is not installed.
sentence-transformers 5.2.3 requires torch>=1.11.0, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
giddy 2.3.8 requires seaborn, which is not installed.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.6.1 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 61.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 41.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 45.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.3/322.3 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 22.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 7.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
timm 1.0.25 requires torchvision, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 38.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, but you have lightgbm 4.6.0 which is incompatible.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.6.1 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 MB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 56.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 46.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 27.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 9.7 MB/s eta 0:00:00
  Building wheel for autograd-gamma (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 14.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.7/180.7 kB 15.7 MB/s eta 0:00:00
  Building wheel for pgbm (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.7/432.7 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 29.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 15.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for shap (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 6.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for lime (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 42.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 62.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 48.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 71.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 70.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 778.9/778.9 kB 28.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 54.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 18.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.9/264.9 kB 23.0 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.5/268.5 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 20.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 36.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 81.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for cp (setup.py) ... done

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ngboost
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from pathlib import Path
from scipy.stats import norm, kstest
from pytorch_tabnet import TabNetRegressor
from treeffuser import Treeffuser, Samples
from treeffuser._score_models import TreeBasedScoreModel

In [2]:
# Go to find & replace button and replace (pile_load_gendy_data) with your folder name. Rename your train and test dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (Settlement) with actual data label name.

In [3]:
feature_names = ['D','L','N30_Ava','Cu_Ava','N30_Base','Cu_Base','UL','Q']

In [4]:
train_data_path = "./drive/MyDrive/pile_load_gendy_data/Data/train.csv"
test_data_path = "./drive/MyDrive/pile_load_gendy_data/Data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (371, 9)
First 5 rows of training data:
      D     L    N30_Ava      Cu_Ava  N30_Base  Cu_Base  UL       Q      S_exp
0  1.0  43.5   3.317241  105.408046        50      0.0   1     0.00   0.000000
1  0.8  24.0   8.875000   17.708333         0     50.0   1   675.00   0.691250
2  0.8  24.0   5.032258   20.000000         0     40.0   1  1012.50   0.870417
3  1.2  70.0  18.214286   14.142857        50      0.0   2  7485.15  19.161300
4  1.0  34.0   6.741176   89.117647        50      0.0   2  3007.59   6.552300

Shape of test data: (186, 9)
First 5 rows of test data:
      D     L    N30_Ava     Cu_Ava  N30_Base  Cu_Base  UL        Q     S_exp
0  0.8  24.0   8.875000  17.708333         0     50.0   2  1687.500  3.295000
1  1.0  38.0  26.631579  49.539474        50      0.0   2  2250.000  4.595960
2  0.8  24.0   5.032258  20.000000         0     40.0   1  1687.500  1.721250
3  1.0  35.5  28.400000  36.676056        50      0.0   1   741.259  0.441964
4  1.2  57.0  10.015789  55.842105        50      0.0   1     0.000  0.000000

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (371, 8)
Shape of y_train: (371,)
Shape of X_test: (186, 8)
Shape of y_test: (186,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[ 0.11501862  0.7026739  -1.39285389  2.03926221  0.47278688 -0.36847246
  -0.88040878 -0.93211799]
 [-1.33640677 -0.87840793 -0.78031847 -0.77862641 -1.76108898  0.85111254
  -0.88040878 -0.72895693]
 [-1.33640677 -0.87840793 -1.2038373  -0.70499262 -1.76108898  0.60719554
  -0.88040878 -0.6273764 ]
 [ 1.566444    2.85132356  0.24898912 -0.89318909  0.47278688 -0.36847246
   1.13583602  1.32075756]
 [ 0.11501862 -0.06759674 -1.0154929   1.5158337   0.47278688 -0.36847246
   1.13583602 -0.02689552]]

First five rows of normalized X_test:
[[-1.33640677 -0.87840793 -0.78031847 -0.77862641 -1.76108898  0.85111254
   1.13583602 -0.42421534]
 [ 0.11501862  0.25672774  1.1766814   0.2441433   0.47278688 -0.36847246
   1.13583602 -0.25491446]
 [-1.33640677 -0.87840793 -1.2038373  -0.70499262 -1.76108898  0.60719554
  -0.88040878 -0.42421534]
 [ 0.11501862  0.05402494  1.37158379 -0.16917252  0.47278688 -0.36847246
  -0.88040878 -0.70901434]
 [ 1.566444    1.79726901 -0.65458908  0.44665379  0.47278688 -0.36847246
  -0.88040878 -0.93211799]]

# **Functions:**

In [8]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [9]:
def generate_and_save_plots(predictions_df, y_test, excel_path):
    # 1. Predicted vs. Actual Plot
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x='Actual', y='Mean', data=predictions_df)
    plt.plot([predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             [predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             color='red', linestyle='--')
    plt.title('Predicted Settlement vs. Actual Settlement')
    plt.xlabel('Actual Settlement')
    plt.ylabel('Predicted Mean Settlement')
    plt.tight_layout()
    predicted_vs_actual_path = 'predicted_vs_actual.png'
    plt.savefig(predicted_vs_actual_path)
    plt.close()

    # 2. Uncertainty Bands
    plt.figure(figsize=(12, 8))
    plt.errorbar(x=range(len(predictions_df)), y=predictions_df['Mean'],
                 yerr=predictions_df['StdDev'], fmt='o', markersize=4, ecolor='red', elinewidth=1, capsize=5, alpha=0.7)
    plt.plot(range(len(predictions_df)), predictions_df['Mean'], color='black', linewidth=0.5, alpha=0.7)
    plt.title('Predicted Mean with Uncertainty Bands', fontsize=16)
    plt.xlabel('Sample Number', fontsize=14)
    plt.ylabel('Predicted Mean Settlement')
    plt.tight_layout()
    uncertainty_bands_path = 'uncertainty_bands.png'
    plt.savefig(uncertainty_bands_path)
    plt.close()

    # 3. Histogram of Standard Deviations
    plt.figure(figsize=(12, 8))
    sns.histplot(predictions_df['StdDev'], bins=20, kde=True)
    plt.title('Distribution of Predicted Standard Deviations')
    plt.xlabel('Standard Deviation')
    plt.ylabel('Frequency')
    plt.tight_layout()
    histogram_stddev_path = 'histogram_stddev.png'
    plt.savefig(histogram_stddev_path)
    plt.close()

    # 4. Residual Plot
    residuals = predictions_df['Actual'] - predictions_df['Mean']
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x=predictions_df['Mean'], y=residuals)
    plt.axhline(0, color='red', linestyle='--')
    plt.title('Residual Plot')
    plt.xlabel('Predicted Mean Settlement')
    plt.ylabel('Residuals')
    plt.tight_layout()
    residual_plot_path = 'residual_plot.png'
    plt.savefig(residual_plot_path)
    plt.close()

    # Plot the standard deviation of the predictions
    plt.figure(figsize=(12, 6))
    plt.plot(
        predictions_df['StdDev'],
        label='Standard Deviation',
        color='green',
        marker='o',
        linestyle='dashed'
    )
    plt.xlabel('Sample Number')
    plt.ylabel('Standard Deviation')
    plt.title('Standard Deviation of Predictions')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    stddev_plot_path = 'stddev_plot.png'
    plt.savefig(stddev_plot_path)
    plt.close()

    # Plot the actual vs predicted mean with confidence intervals
    plt.figure(figsize=(12, 6))
    plt.plot(
        y_test,
        label='Actual Settlement',
        color='black',
        marker='o',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    plt.plot(
        predictions_df['Mean'],
        label='Predicted Mean Settlement',
        color='red',
        marker='x',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    confidence_interval = 1.96 * predictions_df['StdDev']
    plt.fill_between(
        np.arange(len(predictions_df)),
        predictions_df['Mean'] - confidence_interval,
        predictions_df['Mean'] + confidence_interval,
        color='blue',
        alpha=0.2,
        label='95% Confidence Interval'
    )
    plt.xlabel('Sample Number')
    plt.ylabel(' Settlement')
    plt.title('Predictions with Confidence Intervals')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    prediction_plot_path = 'prediction_plot.png'
    plt.savefig(prediction_plot_path)
    plt.close()

    # Create a Pandas Excel writer using XlsxWriter as the engine.
    writer = pd.ExcelWriter(excel_path, engine='xlsxwriter')

    # Write the dataframe to a worksheet.
    predictions_df.to_excel(writer, sheet_name='Predictions', index=False)

    # Access the XlsxWriter workbook and worksheet objects from the writer object.
    workbook = writer.book

    # Insert the plots into new worksheets.
    worksheet_predicted_vs_actual = workbook.add_worksheet('Predicted vs Actual')
    worksheet_predicted_vs_actual.insert_image('A1', predicted_vs_actual_path)

    worksheet_uncertainty_bands = workbook.add_worksheet('Uncertainty Bands')
    worksheet_uncertainty_bands.insert_image('A1', uncertainty_bands_path)

    worksheet_histogram_stddev = workbook.add_worksheet('Histogram StdDev')
    worksheet_histogram_stddev.insert_image('A1', histogram_stddev_path)

    worksheet_residual_plot = workbook.add_worksheet('Residual Plot')
    worksheet_residual_plot.insert_image('A1', residual_plot_path)

    worksheet_stddev = workbook.add_worksheet('StdDev Plot')
    worksheet_stddev.insert_image('A1', stddev_plot_path)

    worksheet_prediction = workbook.add_worksheet('Predictions Plot')
    worksheet_prediction.insert_image('A1', prediction_plot_path)

    # Close the Pandas Excel writer and output the Excel file.
    writer.close()
    print(f"Excel file saved at {excel_path}")

    # Optionally, remove the image files now that they're embedded in the Excel file
    os.remove(predicted_vs_actual_path)
    os.remove(uncertainty_bands_path)
    os.remove(histogram_stddev_path)
    os.remove(residual_plot_path)
    os.remove(stddev_plot_path)
    os.remove(prediction_plot_path)

In [10]:
def generate_and_save_crps_decomposition(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    # -------------------------------
    # Total CRPS
    # -------------------------------
    crps_values = ps.crps_gaussian(
        y_true, mu=mu_pred, sig=sigma_pred
    )
    total_crps = np.mean(crps_values)

    # -------------------------------
    # Uncertainty (climatology)
    # -------------------------------
    global_mu = np.mean(y_true)
    global_sigma = np.std(y_true)

    uncertainty = np.mean(
        ps.crps_gaussian(y_true, mu=global_mu, sig=global_sigma)
    )

    # -------------------------------
    # Reliability & Resolution
    # -------------------------------
    sort_idx = np.argsort(mu_pred)
    y_sorted = y_true[sort_idx]
    mu_sorted = mu_pred[sort_idx]
    sigma_sorted = sigma_pred[sort_idx]

    bins = np.array_split(np.arange(len(y_true)), n_bins)

    bin_results = []
    reliability_sum = 0.0

    for i, b in enumerate(bins):
        bin_y = y_sorted[b]
        bin_mu = mu_sorted[b]
        bin_sigma = sigma_sorted[b]

        bin_crps = np.mean(
            ps.crps_gaussian(bin_y, mu=bin_mu, sig=bin_sigma)
        )

        reliability_sum += bin_crps

        bin_results.append({
            "Bin": i + 1,
            "Bin_Size": len(b),
            "Mean_Pred_Mu": np.mean(bin_mu),
            "Mean_Pred_Sigma": np.mean(bin_sigma),
            "Bin_CRPS": bin_crps
        })

    reliability = reliability_sum / n_bins
    resolution = uncertainty - (total_crps - reliability)

    # -------------------------------
    # Summary table
    # -------------------------------
    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Total_CRPS": total_crps,
        "Reliability": reliability,
        "Resolution": resolution,
        "Uncertainty": uncertainty,
        "Num_Bins": n_bins
    }])

    bin_df = pd.DataFrame(bin_results)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_summary = f"CRPS_Summary_{model_name}"
    sheet_bins = f"CRPS_Bins_{model_name}"

    with pd.ExcelWriter(
        excel_path,
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)
        bin_df.to_excel(writer, sheet_name=sheet_bins, index=False)

    print(f"✅ CRPS decomposition saved to:\n{excel_path}")
    print(f"   Sheets: {sheet_summary}, {sheet_bins}")

    return summary_df

In [11]:
def generate_and_save_pit_results(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):
    """
    Generate PIT values, histogram, calibration diagnostics,
    and save everything to Excel with the PIT plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Compute PIT values
    # -------------------------------
    pit_values = norm.cdf(y_true, loc=mu_pred, scale=sigma_pred)

    pit_df = pd.DataFrame({"PIT_Value": pit_values})

    # -------------------------------
    # Histogram data
    # -------------------------------
    hist_density, bin_edges = np.histogram(
        pit_values, bins=n_bins, range=(0, 1), density=True
    )
    bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])

    hist_df = pd.DataFrame({
        "Bin_Center": bin_centers,
        "Density": hist_density
    })

    # -------------------------------
    # Calibration diagnostics
    # -------------------------------
    pit_mean = pit_values.mean()
    pit_var = pit_values.var()
    ks_stat, ks_pvalue = kstest(pit_values, 'uniform')

    if ks_pvalue > 0.05:
        diagnosis = "Well-calibrated (Uniform PIT)"
    elif pit_var < 1/12:
        diagnosis = "Over-dispersed (Under-confident)"
    elif pit_var > 1/12:
        diagnosis = "Under-dispersed (Over-confident)"
    else:
        diagnosis = "Biased or miscalibrated"

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_PIT": pit_mean,
        "Variance_PIT": pit_var,
        "Ideal_Variance_(1/12)": 1/12,
        "KS_Statistic": ks_stat,
        "KS_pvalue": ks_pvalue,
        "Calibration_Diagnosis": diagnosis
    }])

    # -------------------------------
    # Create PIT plot in memory
    # -------------------------------
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(
        pit_values,
        bins=n_bins,
        density=True,
        color="skyblue",
        edgecolor="black",
        alpha=0.75
    )
    ax.axhline(1, color="red", linestyle="--", label="Perfect Calibration")
    ax.set_xlabel("PIT Value")
    ax.set_ylabel("Density")
    ax.set_title(f"PIT Histogram – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_values = f"PIT_Values_{model_name}"
    sheet_hist = f"PIT_Histogram_{model_name}"
    sheet_summary = f"PIT_Summary_{model_name}"
    sheet_plot = f"PIT_Plot_{model_name}"

    with pd.ExcelWriter(
        excel_path,
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        pit_df.to_excel(writer, sheet_name=sheet_values, index=False)
        hist_df.to_excel(writer, sheet_name=sheet_hist, index=False)
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        # Create empty sheet for plot
        workbook = writer.book
        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print(f"✅ PIT values, histogram, summary, and EMBEDDED plot saved to:")
    print(f"   {excel_path}")

    return pit_df

In [12]:
def generate_and_save_calibration_curve(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_quantiles=10
):
    """
    Generate quantile calibration curve (reliability diagram),
    compute calibration errors, and save everything to Excel
    with the plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()
    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Quantiles
    # -------------------------------
    quantiles = np.linspace(0, 1, n_quantiles + 1)

    observed_freq = []
    predicted_q = []

    for q in quantiles:
        # Predicted value at quantile q
        thresh = norm.ppf(q, loc=mu_pred, scale=sigma_pred)

        # Observed frequency
        obs = np.mean(y_true <= thresh)

        predicted_q.append(q)
        observed_freq.append(obs)

    predicted_q = np.array(predicted_q)
    observed_freq = np.array(observed_freq)

    # -------------------------------
    # Calibration metrics
    # -------------------------------
    mce = np.mean(np.abs(observed_freq - predicted_q))
    rmsce = np.sqrt(np.mean((observed_freq - predicted_q) ** 2))

    calib_df = pd.DataFrame({
        "Predicted_Quantile": predicted_q,
        "Observed_Frequency": observed_freq,
        "Absolute_Error": np.abs(observed_freq - predicted_q)
    })

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_Calibration_Error (MCE)": mce,
        "RMS_Calibration_Error (RMSCE)": rmsce,
        "Num_Quantiles": n_quantiles
    }])

    # -------------------------------
    # Create calibration plot
    # -------------------------------
    fig, ax = plt.subplots(figsize=(7, 7))

    ax.plot([0, 1], [0, 1], 'k--', label="Perfect Calibration")
    ax.plot(
        predicted_q,
        observed_freq,
        'o-',
        color='teal',
        label=f"{model_name}"
    )

    ax.set_xlabel("Predicted Quantile (Confidence Level)")
    ax.set_ylabel("Observed Frequency")
    ax.set_title(f"Quantile Calibration Curve – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_curve = f"Calibration_Curve_{model_name}"
    sheet_summary = f"Calibration_Summary_{model_name}"
    sheet_plot = f"Calibration_Plot_{model_name}"

    with pd.ExcelWriter(
        excel_path,
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        calib_df.to_excel(writer, sheet_name=sheet_curve, index=False)
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        workbook = writer.book

        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print("✅ Calibration curve & metrics saved to Excel:")
    print(f"   {excel_path}")

    return calib_df

In [13]:
# Define the path to the folder
folder_path = "/content/drive/MyDrive/pile_load_gendy_data"

# Create the folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

def plot_metrics_and_save_to_excel(writer, predictions_df, y_true, model_name):
    # Calculate metrics
    mean_pred = predictions_df['Mean']
    std_pred = predictions_df['StdDev']

    # Sharpness is the standard deviation
    sharpness = std_pred.mean()

    # CRPS for each prediction
    crps_values = ps.crps_gaussian(y_true, mean_pred, std_pred)

    # Negative Log Likelihood (NLL) for each prediction
    nll_values = -norm.logpdf(y_true, loc=mean_pred, scale=std_pred)
    nll = nll_values.mean()

    # Calibration (Validity)
    percentiles = np.linspace(0, 100, 101)
    calibration = [np.mean((y_true <= np.percentile(mean_pred + std_pred * np.random.randn(*mean_pred.shape), p))) for p in percentiles]

    # Create a DataFrame to store the metrics
    metrics_df = pd.DataFrame({
        'Mean Prediction': mean_pred,
        'Standard Deviation': std_pred,
        'CRPS': crps_values,
        'NLL': nll_values
    })

    # Add summary statistics
    summary_df = pd.DataFrame({
        'Metric': ['Sharpness', 'Mean CRPS', 'Mean NLL'],
        'Value': [sharpness, crps_values.mean(), nll]
    })

    # Write the metrics and summary to the Excel sheet
    metrics_sheet_name = f'{model_name} Metrics'
    metrics_df.to_excel(writer, sheet_name=metrics_sheet_name, index=False)

    summary_sheet_name = f'{model_name} Summary'
    summary_df.to_excel(writer, sheet_name=summary_sheet_name, index=False)

    # Plotting
    fig, axs = plt.subplots(2, 2, figsize=(12, 10))

    # Sharpness plot
    axs[0, 0].hist(std_pred, bins=30, color='skyblue', edgecolor='black')
    axs[0, 0].set_title(f'Sharpness (StdDev) for {model_name}')
    axs[0, 0].set_xlabel('Standard Deviation')
    axs[0, 0].set_ylabel('Frequency')

    # CRPS plot (distribution)
    axs[0, 1].hist(crps_values, bins=30, color='lightgreen', edgecolor='black')
    axs[0, 1].set_title(f'CRPS Distribution for {model_name}')
    axs[0, 1].set_xlabel('CRPS')
    axs[0, 1].set_ylabel('Frequency')

    # NLL plot (distribution)
    axs[1, 0].hist(nll_values, bins=30, color='salmon', edgecolor='black')
    axs[1, 0].set_title(f'NLL Distribution for {model_name}')
    axs[1, 0].set_xlabel('NLL')
    axs[1, 0].set_ylabel('Frequency')

    # Calibration plot
    axs[1, 1].plot(percentiles, calibration, label='Calibration Curve')
    axs[1, 1].plot(percentiles, percentiles / 100, linestyle='--', label='Perfect Calibration')
    axs[1, 1].set_title(f'Calibration (Validity) for {model_name}')
    axs[1, 1].set_xlabel('Predicted Percentile')
    axs[1, 1].set_ylabel('Observed Frequency')
    axs[1, 1].legend()

    plt.tight_layout()

    # Save plots to images
    plot_image_path = f'{model_name}_plots.png'
    fig.savefig(plot_image_path)
    plt.close(fig)

    # Insert the plot image into the Excel sheet
    sheet_name = f'{model_name} Plots'
    if sheet_name not in writer.sheets:  # Check if sheet already exists
        # If sheet doesn't exist, create a new one
        worksheet = writer.book.add_worksheet(sheet_name)
    else:
        # If sheet exists, get the existing sheet object to avoid duplicates
        worksheet = writer.sheets[sheet_name]
    worksheet.insert_image('A1', plot_image_path)

# **Tuned Parameters**

In [14]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 152.98063120551464,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 152.98063120551464,
  'test_rmse': np.float64(12.368533914959956),
  'test_corr_coef': np.float64(0.9100717040625368),
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 170.63124260879067,
  'best_params': {'n_estimators': 100,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 170.63124260879067,
  'test_rmse': np.float64(13.062589429695425),
  'test_corr_coef': np.float64(0.8943907434686084),
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 180.04588999142493,
  'best_params': {'n_estimators': 100,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 180.04588999142493,
  'test_rmse': np.float64(13.418117975015159),
  'test_corr_coef': np.float64(0.8893904103704389),
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 154.16247953238616,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 154.16247953238616,
  'test_rmse': np.float64(12.416218407082978),
  'test_corr_coef': np.float64(0.9098826634121733),
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 152.46010559118824, 'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.3,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05}, 'test_mse': 152.46010559118824, 'test_rmse': np.float64(12.347473652176312), 'test_corr_coef': np.float64(0.9101947022096951), 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 163.0289258942997,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 163.0289258942997,
  'test_rmse': np.float64(12.768278109999786),
  'test_corr_coef': np.float64(0.9002897960107232),
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 154.64840720467092,
  'best_params': {'n_estimators': 200,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.3,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 154.64840720467092,
  'test_rmse': np.float64(12.435771275022347),
  'test_corr_coef': np.float64(0.9065053984224763),
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 158.28207318969893,
  'best_params': {'n_estimators': 700,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.3,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 158.28207318969893,
  'test_rmse': np.float64(12.581020355666663),
  'test_corr_coef': np.float64(0.9052738863008764),
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 106.82199342946828,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 106.82199342946828,
  'test_rmse': np.float64(10.335472578913278),
  'test_corr_coef': np.float64(0.9310344147012503),
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 111.15668952779254,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 2,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 111.15668952779254,
  'test_rmse': np.float64(10.543087286359368),
  'test_corr_coef': np.float64(0.9270426649914485),
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 89.02816733158211,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 89.02816733158211,
  'test_rmse': np.float64(9.435473879545325),
  'test_corr_coef': np.float64(0.9456205230324285),
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 100.66262991393918,
  'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 100.66262991393918,
  'test_rmse': np.float64(10.033076791988547),
  'test_corr_coef': np.float64(0.9342492651003499),
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 120.46198397430994, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 100,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.001}, 'test_mse': 120.46198397430994, 'test_rmse': np.float64(10.975517480935007), 'test_corr_coef': np.float64(0.923499908135557), 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 109.53579015309792,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.01},
  'test_mse': 109.53579015309792,
  'test_rmse': np.float64(10.46593474817696),
  'test_corr_coef': np.float64(0.9327627929002421),
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 107.86816836778692,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 107.86816836778692,
  'test_rmse': np.float64(10.385960156277653),
  'test_corr_coef': np.float64(0.9277543666060549),
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 115.63069596852776,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 115.63069596852776,
  'test_rmse': np.float64(10.753171437698171),
  'test_corr_coef': np.float64(0.9255816102420358),
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 100.58914887067544,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 100.58914887067544,
  'test_rmse': np.float64(10.029414183823272),
  'test_corr_coef': np.float64(0.9359533194853996),
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 89.61367880089917,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 89.61367880089917,
  'test_rmse': np.float64(9.466450168933399),
  'test_corr_coef': np.float64(0.9431313973448553),
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 98.49578970490964,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 98.49578970490964,
  'test_rmse': np.float64(9.924504506770583),
  'test_corr_coef': np.float64(0.9365472186074788),
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 67.93676050134304,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 67.93676050134304,
  'test_rmse': np.float64(8.242375901482717),
  'test_corr_coef': np.float64(0.9561296172273666),
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 99.3361140760957,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 99.3361140760957,
  'test_rmse': np.float64(9.966750427099884),
  'test_corr_coef': np.float64(0.9389056880557962),
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 86.68867330070917,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 86.68867330070917,
  'test_rmse': np.float64(9.310675233338834),
  'test_corr_coef': np.float64(0.9488970717669976),
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 92.02039272806104,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 92.02039272806104,
  'test_rmse': np.float64(9.592726032159005),
  'test_corr_coef': np.float64(0.9432169166482989),
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 93.85385734548784,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 93.85385734548784,
  'test_rmse': np.float64(9.687820051254453),
  'test_corr_coef': np.float64(0.9417304624183378),
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 95.44911836418507,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 95.44911836418507,
  'test_rmse': np.float64(9.769806465032206),
  'test_corr_coef': np.float64(0.93682381557629),
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 78.38037008965738,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 78.38037008965738,
  'test_rmse': np.float64(8.85326889288117),
  'test_corr_coef': np.float64(0.9541227486219568),
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 100.44210495654774,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 100.44210495654774,
  'test_rmse': np.float64(10.0220808695873),
  'test_corr_coef': np.float64(0.933242701768733),
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 101.63336303111387,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'min_child_weight': 0.01,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 101.63336303111387,
  'test_rmse': np.float64(10.081337363222891),
  'test_corr_coef': np.float64(0.9322923768116579),
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 97.56376537904843,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 97.56376537904843,
  'test_rmse': np.float64(9.877437186793365),
  'test_corr_coef': np.float64(0.9334568585552251),
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 108.72600408852692,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 108.72600408852692,
  'test_rmse': np.float64(10.427176227940473),
  'test_corr_coef': np.float64(0.926544507181797),
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 100.48601146382701,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 0,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 100.48601146382701,
  'test_rmse': np.float64(10.024271118830885),
  'test_corr_coef': np.float64(0.9336433334531059),
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 88.65248921998764,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 88.65248921998764,
  'test_rmse': np.float64(9.41554508353009),
  'test_corr_coef': np.float64(0.9452888449153922),
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 98.89133129858779,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.9,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 98.89133129858779,
  'test_rmse': np.float64(9.944412063997941),
  'test_corr_coef': np.float64(0.933729392135044),
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 101.36751534760184,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 1.0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 101.36751534760184,
  'test_rmse': np.float64(10.068143589937613),
  'test_corr_coef': np.float64(0.9311295278444216),
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 95.51459146564854,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.9,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 1.0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 95.51459146564854,
  'test_rmse': np.float64(9.773156678660612),
  'test_corr_coef': np.float64(0.935810950039782),
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 95.02584170675935,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.5,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 95.02584170675935,
  'test_rmse': np.float64(9.748119906256763),
  'test_corr_coef': np.float64(0.9367257738852067),
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 103.04660969928004,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.5,
   'reg_lambda': 1.0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 103.04660969928004,
  'test_rmse': np.float64(10.151187600437696),
  'test_corr_coef': np.float64(0.9294310296392595),
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 93.31598269527979,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 93.31598269527979,
  'test_rmse': np.float64(9.660019808223987),
  'test_corr_coef': np.float64(0.9374326288527489),
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 96.29461706369923,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 96.29461706369923,
  'test_rmse': np.float64(9.812982067837444),
  'test_corr_coef': np.float64(0.934807468291228),
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 102.18009827730634,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': -1,
   'num_leaves': 31,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 102.18009827730634,
  'test_rmse': np.float64(10.108417199408933),
  'test_corr_coef': np.float64(0.9314026791262863),
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 85.48272460888411,
  'best_params': {'iterations': 500,
   'learning_rate': 0.1,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 85.48272460888411,
  'test_rmse': np.float64(9.245686811096519),
  'test_corr_coef': np.float64(0.9445059932077939),
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 93.36712377305112,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 6,
   'l2_leaf_reg': 3,
   'border_count': 128,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 93.36712377305112,
  'test_rmse': np.float64(9.662666493936916),
  'test_corr_coef': np.float64(0.9413875272554717),
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 89.50072499631383,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 128,
   'min_data_in_leaf': 10,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 89.50072499631383,
  'test_rmse': np.float64(9.46048228138047),
  'test_corr_coef': np.float64(0.9462768805177888),
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 88.95178129138309,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 128,
   'min_data_in_leaf': 1,
   'rsm': 0.8,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 88.95178129138309,
  'test_rmse': np.float64(9.431425199373798),
  'test_corr_coef': np.float64(0.945133421527909),
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 85.36080983400738,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 85.36080983400738,
  'test_rmse': np.float64(9.239091396560994),
  'test_corr_coef': np.float64(0.944589054411141),
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 89.78953847272699,
  'best_params': {'iterations': 500,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 128,
   'min_data_in_leaf': 20,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 89.78953847272699,
  'test_rmse': np.float64(9.475734191751423),
  'test_corr_coef': np.float64(0.9446376921418882),
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 88.95178129138309,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 128,
   'min_data_in_leaf': 1,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 88.95178129138309,
  'test_rmse': np.float64(9.431425199373798),
  'test_corr_coef': np.float64(0.945133421527909),
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 85.36080983400738,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 85.36080983400738,
  'test_rmse': np.float64(9.239091396560994),
  'test_corr_coef': np.float64(0.944589054411141),
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 153.3856053332811,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 153.3856053332811,
  'test_rmse': np.float64(12.384894239890832),
  'test_corr_coef': np.float64(0.8930112337646037),
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 143.30218176515817,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 143.30218176515817,
  'test_rmse': np.float64(11.970888929614132),
  'test_corr_coef': np.float64(0.9007498276924898),
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 157.5719110469103,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 157.5719110469103,
  'test_rmse': np.float64(12.552765075747665),
  'test_corr_coef': np.float64(0.8882779345461344),
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 159.10355471401047,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 159.10355471401047,
  'test_rmse': np.float64(12.613625756062785),
  'test_corr_coef': np.float64(0.8887176533138197),
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 151.44908811890718,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 151.44908811890718,
  'test_rmse': np.float64(12.306465297513627),
  'test_corr_coef': np.float64(0.8942223224428472),
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 145.81711936793175,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 145.81711936793175,
  'test_rmse': np.float64(12.07547594788428),
  'test_corr_coef': np.float64(0.8990006764687222),
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 152.87737506561598,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 152.87737506561598,
  'test_rmse': np.float64(12.364359064084802),
  'test_corr_coef': np.float64(0.8947260671053722),
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 155.76578578406654,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 1.0,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 155.76578578406654,
  'test_rmse': np.float64(12.480616402408439),
  'test_corr_coef': np.float64(0.8945010680208828),
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 67.56506779356722,
  'best_params': {'n_d': 32,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 2.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 67.56506779356722,
  'test_rmse': np.float64(8.21979730854522),
  'test_corr_coef': np.float64(0.9530052734492968),
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 76.08969444498896,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 76.08969444498896,
  'test_rmse': np.float64(8.722940699385097),
  'test_corr_coef': np.float64(0.9539981359400319),
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 51.715715833103495,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 3,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 51.715715833103495,
  'test_rmse': np.float64(7.191363975846549),
  'test_corr_coef': np.float64(0.9656865213398506),
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 71.63011611867866,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 71.63011611867866,
  'test_rmse': np.float64(8.463457692850993),
  'test_corr_coef': np.float64(0.9654969292739963),
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 82.00418994914077,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 3,
   'gamma': 2.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 82.00418994914077,
  'test_rmse': np.float64(9.055616486421052),
  'test_corr_coef': np.float64(0.9437403007013775),
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 61.70944877314963,
  'best_params': {'n_d': 8,
   'n_a': 16,
   'n_steps': 3,
   'gamma': 1.5,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 61.70944877314963,
  'test_rmse': np.float64(7.855536186228769),
  'test_corr_coef': np.float64(0.9585631287990138),
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 75.58697579720257,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 75.58697579720257,
  'test_rmse': np.float64(8.694077052637764),
  'test_corr_coef': np.float64(0.9758601351677328),
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 71.4337647373294,
  'best_params': {'n_d': 16,
   'n_a': 64,
   'n_steps': 5,
   'gamma': 1.3,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 71.4337647373294,
  'test_rmse': np.float64(8.451849781990296),
  'test_corr_coef': np.float64(0.9505375759724721),
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 129.3442580892259,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 300,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 129.3442580892259,
  'test_rmse': np.float64(11.372961711411232),
  'test_corr_coef': np.float64(0.9110563465189973),
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 128.84698844088038,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 300,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': None,
   'l2_regularization': 0.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 128.84698844088038,
  'test_rmse': np.float64(11.351078734678937),
  'test_corr_coef': np.float64(0.9126867001605148),
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 118.10639347146959,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 200,
   'max_depth': None,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.1,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 118.10639347146959,
  'test_rmse': np.float64(10.867676544297295),
  'test_corr_coef': np.float64(0.9232102276248901),
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 118.33165303465466, 'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 118.33165303465466, 'test_rmse': np.float64(10.878035348106508), 'test_corr_coef': np.float64(0.9214138007846934), 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 120.04036901152315, 'best_params': {'learning_rate': 0.15,
   'max_iter': 500,
   'max_depth': 7,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 120.04036901152315, 'test_rmse': np.float64(10.956293580017064), 'test_corr_coef': np.float64(0.9202582418957181), 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting',
  'HyperbandPruner'): {'best_score': 116.79271602948637, 'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': None,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 1.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 116.79271602948637, 'test_rmse': np.float64(10.8070678738262), 'test_corr_coef': np.float64(0.9225001141872002), 'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting',
  'ThresholdPruner'): {'best_score': 114.40748198147847, 'best_params': {'learning_rate': 0.15,
   'max_iter': 500,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 114.40748198147847, 'test_rmse': np.float64(10.696143322781277), 'test_corr_coef': np.float64(0.9255663426415169), 'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 117.98955148062424,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 300,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': None,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 117.98955148062424,
  'test_rmse': np.float64(10.8622995484669),
  'test_corr_coef': np.float64(0.9224400475682029),
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 110.06646235121923,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 59,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 110.06646235121923,
  'test_rmse': np.float64(10.491256471520426),
  'test_corr_coef': np.float64(0.9238145638885917),
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 116.36760716412837,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 54,
   'min_split_gain': 0.5,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 116.36760716412837,
  'test_rmse': np.float64(10.787381849370512),
  'test_corr_coef': np.float64(0.9212230066839205),
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 120.43814576742204,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_leaves': 19,
   'min_split_gain': 0.1,
   'reg_lambda': 1.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 120.43814576742204,
  'test_rmse': np.float64(10.97443145531567),
  'test_corr_coef': np.float64(0.9174495811585923),
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 105.28414366018494,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 15,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 64,
   'distribution': 'normal'},
  'test_mse': 105.28414366018494,
  'test_rmse': np.float64(10.260806189583006),
  'test_corr_coef': np.float64(0.9302272067031147),
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 109.29949887489617,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_leaves': 56,
   'min_split_gain': 0.5,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 109.29949887489617,
  'test_rmse': np.float64(10.454640064339669),
  'test_corr_coef': np.float64(0.9255118931278087),
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 110.77295523525386,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 34,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 110.77295523525386,
  'test_rmse': np.float64(10.52487316955667),
  'test_corr_coef': np.float64(0.9231205172720397),
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 111.64254560217586,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_leaves': 55,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 111.64254560217586,
  'test_rmse': np.float64(10.566103614964973),
  'test_corr_coef': np.float64(0.9236377603457087),
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 105.48508904482442,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 58,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 105.48508904482442,
  'test_rmse': np.float64(10.270593412496886),
  'test_corr_coef': np.float64(0.9287649006989753),
  'pruner': 'WilcoxonPruner'}}

# **Probabilistic distributions using NGBoost**

In [15]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize NGBoost model with best_params
ngb_model = NGBRegressor(Dist=Normal, **best_params)

# Fit the model
ngb_model.fit(X_train, y_train)

# Predict the distribution
pred_dist = ngb_model.pred_dist(X_test)

# Extract mean and standard deviation
predictions_NGB_df = pd.DataFrame({
    'Mean': pred_dist.loc,
    'StdDev': pred_dist.scale,
    'Actual': y_test.ravel()
})

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, pred_dist.loc)
print(f"Mean Squared Error: {mse:.2f}")

# Print the DataFrame with mean and standard deviation
print(predictions_NGB_df.head())

Mean Squared Error: 165.95
        Mean    StdDev    Actual
0   3.106476  0.200286  3.295000
1   5.621190  0.773639  4.595960
2   1.837036  0.371629  1.721250
3  -0.966613  0.739337  0.441964
4  23.019008  6.082229  0.000000

In [16]:
generate_and_save_plots(predictions_NGB_df, y_test, "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution//NGBoost_Prob.xlsx")

Excel file saved at ./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution//NGBoost_Prob.xlsx

In [17]:
generate_and_save_crps_decomposition(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/NGBoost_Prob.xlsx
   Sheets: CRPS_Summary_NGBoost, CRPS_Bins_NGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  NGBoost    5.855781     6.016792   13.892931     13.73192        10

In [18]:
generate_and_save_pit_results(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/NGBoost_Prob.xlsx

     PIT_Value
0     0.826718
1     0.092552
2     0.377686
3     0.971622
4     0.000077
..         ...
181   0.124406
182   0.259385
183   0.647770
184   0.433426
185   0.170619

[186 rows x 1 columns]

In [19]:
generate_and_save_calibration_curve(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/NGBoost_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.317204        0.217204
2                  0.2            0.397849        0.197849
3                  0.3            0.446237        0.146237
4                  0.4            0.489247        0.089247
5                  0.5            0.537634        0.037634
6                  0.6            0.612903        0.012903
7                  0.7            0.650538        0.049462
8                  0.8            0.709677        0.090323
9                  0.9            0.774194        0.125806
10                 1.0            1.000000        0.000000

# **Probabilistic distributions using PGBM**

In [20]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
# Note: Adjust the incompatible keys based on PGBM's requirements
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()

def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)
# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params = best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Extract mean and standard deviation
# Note: PGBM might return predictions in a different format, adjust accordingly
predictions_PGBM_df = pd.DataFrame({
    'Mean': pred_dist.mean(axis=0),
    'StdDev': pred_dist.std(axis=0),
    'Actual': y_test.ravel()
})

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, predictions_PGBM_df['Mean'])
print(f"Mean Squared Error: {mse:.2f}")

# Print the DataFrame with mean and standard deviation
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/500, Train metric: 22.1361
Estimator 1/500, Train metric: 20.8855
Estimator 2/500, Train metric: 19.5915
Estimator 3/500, Train metric: 18.2131
Estimator 4/500, Train metric: 17.1009
Estimator 5/500, Train metric: 16.1603
Estimator 6/500, Train metric: 15.3445
Estimator 7/500, Train metric: 14.5007
Estimator 8/500, Train metric: 13.8727
Estimator 9/500, Train metric: 13.4215
Estimator 10/500, Train metric: 12.9436
Estimator 11/500, Train metric: 12.4729
Estimator 12/500, Train metric: 12.0088
Estimator 13/500, Train metric: 11.6548
Estimator 14/500, Train metric: 11.2491
Estimator 15/500, Train metric: 10.9663
Estimator 16/500, Train metric: 10.6614
Estimator 17/500, Train metric: 10.4037
Estimator 18/500, Train metric: 10.1342
Estimator 19/500, Train metric: 9.8889
Estimator 20/500, Train metric: 9.5760
Estimator 21/500, Train metric: 9.4135
Estimator 22/500, Train metric: 9.2053
Estimator 23/500, Train metric: 8.9860
Estimator 24/500, Train metric: 8.8239
Estimator 25/500, Train metric: 8.6790
Estimator 26/500, Train metric: 8.4876
Estimator 27/500, Train metric: 8.3136
Estimator 28/500, Train metric: 8.1183
Estimator 29/500, Train metric: 7.9377
Estimator 30/500, Train metric: 7.7895
Estimator 31/500, Train metric: 7.6707
Estimator 32/500, Train metric: 7.5320
Estimator 33/500, Train metric: 7.4224
Estimator 34/500, Train metric: 7.3083
Estimator 35/500, Train metric: 7.2022
Estimator 36/500, Train metric: 7.1235
Estimator 37/500, Train metric: 7.0237
Estimator 38/500, Train metric: 6.9367
Estimator 39/500, Train metric: 6.8656
Estimator 40/500, Train metric: 6.7973
Estimator 41/500, Train metric: 6.6991
Estimator 42/500, Train metric: 6.6169
Estimator 43/500, Train metric: 6.5408
Estimator 44/500, Train metric: 6.4748
Estimator 45/500, Train metric: 6.4064
Estimator 46/500, Train metric: 6.3435
Estimator 47/500, Train metric: 6.2796
Estimator 48/500, Train metric: 6.2217
Estimator 49/500, Train metric: 6.1998
Estimator 50/500, Train metric: 6.1501
Estimator 51/500, Train metric: 6.0788
Estimator 52/500, Train metric: 6.0169
Estimator 53/500, Train metric: 5.9483
Estimator 54/500, Train metric: 5.9065
Estimator 55/500, Train metric: 5.8547
Estimator 56/500, Train metric: 5.7898
Estimator 57/500, Train metric: 5.7290
Estimator 58/500, Train metric: 5.6813
Estimator 59/500, Train metric: 5.6441
Estimator 60/500, Train metric: 5.5936
Estimator 61/500, Train metric: 5.5520
Estimator 62/500, Train metric: 5.5188
Estimator 63/500, Train metric: 5.4571
Estimator 64/500, Train metric: 5.4115
Estimator 65/500, Train metric: 5.3213
Estimator 66/500, Train metric: 5.2441
Estimator 67/500, Train metric: 5.2148
Estimator 68/500, Train metric: 5.1848
Estimator 69/500, Train metric: 5.1616
Estimator 70/500, Train metric: 5.1097
Estimator 71/500, Train metric: 5.0797
Estimator 72/500, Train metric: 5.0480
Estimator 73/500, Train metric: 4.9788
Estimator 74/500, Train metric: 4.9511
Estimator 75/500, Train metric: 4.9212
Estimator 76/500, Train metric: 4.8922
Estimator 77/500, Train metric: 4.8737
Estimator 78/500, Train metric: 4.8424
Estimator 79/500, Train metric: 4.7915
Estimator 80/500, Train metric: 4.7590
Estimator 81/500, Train metric: 4.7360
Estimator 82/500, Train metric: 4.7037
Estimator 83/500, Train metric: 4.6858
Estimator 84/500, Train metric: 4.6652
Estimator 85/500, Train metric: 4.6296
Estimator 86/500, Train metric: 4.5971
Estimator 87/500, Train metric: 4.5629
Estimator 88/500, Train metric: 4.5365
Estimator 89/500, Train metric: 4.5053
Estimator 90/500, Train metric: 4.4787
Estimator 91/500, Train metric: 4.4592
Estimator 92/500, Train metric: 4.4321
Estimator 93/500, Train metric: 4.4054
Estimator 94/500, Train metric: 4.3796
Estimator 95/500, Train metric: 4.3590
Estimator 96/500, Train metric: 4.3280
Estimator 97/500, Train metric: 4.3044
Estimator 98/500, Train metric: 4.2898
Estimator 99/500, Train metric: 4.2780
Estimator 100/500, Train metric: 4.2579
Estimator 101/500, Train metric: 4.2485
Estimator 102/500, Train metric: 4.2362
Estimator 103/500, Train metric: 4.2132
Estimator 104/500, Train metric: 4.1884
Estimator 105/500, Train metric: 4.1733
Estimator 106/500, Train metric: 4.1630
Estimator 107/500, Train metric: 4.1447
Estimator 108/500, Train metric: 4.0921
Estimator 109/500, Train metric: 4.0749
Estimator 110/500, Train metric: 4.0523
Estimator 111/500, Train metric: 4.0308
Estimator 112/500, Train metric: 4.0152
Estimator 113/500, Train metric: 4.0034
Estimator 114/500, Train metric: 3.9792
Estimator 115/500, Train metric: 3.9407
Estimator 116/500, Train metric: 3.9286
Estimator 117/500, Train metric: 3.9152
Estimator 118/500, Train metric: 3.8771
Estimator 119/500, Train metric: 3.8649
Estimator 120/500, Train metric: 3.8519
Estimator 121/500, Train metric: 3.8431
Estimator 122/500, Train metric: 3.8351
Estimator 123/500, Train metric: 3.8136
Estimator 124/500, Train metric: 3.8019
Estimator 125/500, Train metric: 3.7934
Estimator 126/500, Train metric: 3.7785
Estimator 127/500, Train metric: 3.7599
Estimator 128/500, Train metric: 3.7451
Estimator 129/500, Train metric: 3.7048
Estimator 130/500, Train metric: 3.6879
Estimator 131/500, Train metric: 3.6756
Estimator 132/500, Train metric: 3.6529
Estimator 133/500, Train metric: 3.6245
Estimator 134/500, Train metric: 3.6078
Estimator 135/500, Train metric: 3.5948
Estimator 136/500, Train metric: 3.5647
Estimator 137/500, Train metric: 3.5563
Estimator 138/500, Train metric: 3.5424
Estimator 139/500, Train metric: 3.5315
Estimator 140/500, Train metric: 3.5080
Estimator 141/500, Train metric: 3.5000
Estimator 142/500, Train metric: 3.4927
Estimator 143/500, Train metric: 3.4792
Estimator 144/500, Train metric: 3.4671
Estimator 145/500, Train metric: 3.4573
Estimator 146/500, Train metric: 3.4399
Estimator 147/500, Train metric: 3.4322
Estimator 148/500, Train metric: 3.4159
Estimator 149/500, Train metric: 3.4061
Estimator 150/500, Train metric: 3.3818
Estimator 151/500, Train metric: 3.3671
Estimator 152/500, Train metric: 3.3603
Estimator 153/500, Train metric: 3.3439
Estimator 154/500, Train metric: 3.3330
Estimator 155/500, Train metric: 3.3251
Estimator 156/500, Train metric: 3.3132
Estimator 157/500, Train metric: 3.3006
Estimator 158/500, Train metric: 3.2921
Estimator 159/500, Train metric: 3.2807
Estimator 160/500, Train metric: 3.2720
Estimator 161/500, Train metric: 3.2666
Estimator 162/500, Train metric: 3.2578
Estimator 163/500, Train metric: 3.2477
Estimator 164/500, Train metric: 3.2335
Estimator 165/500, Train metric: 3.2295
Estimator 166/500, Train metric: 3.2211
Estimator 167/500, Train metric: 3.2094
Estimator 168/500, Train metric: 3.1949
Estimator 169/500, Train metric: 3.1748
Estimator 170/500, Train metric: 3.1678
Estimator 171/500, Train metric: 3.1447
Estimator 172/500, Train metric: 3.1279
Estimator 173/500, Train metric: 3.1179
Estimator 174/500, Train metric: 3.0928
Estimator 175/500, Train metric: 3.0820
Estimator 176/500, Train metric: 3.0758
Estimator 177/500, Train metric: 3.0639
Estimator 178/500, Train metric: 3.0544
Estimator 179/500, Train metric: 3.0510
Estimator 180/500, Train metric: 3.0436
Estimator 181/500, Train metric: 3.0341
Estimator 182/500, Train metric: 3.0253
Estimator 183/500, Train metric: 3.0104
Estimator 184/500, Train metric: 2.9987
Estimator 185/500, Train metric: 2.9940
Estimator 186/500, Train metric: 2.9788
Estimator 187/500, Train metric: 2.9650
Estimator 188/500, Train metric: 2.9514
Estimator 189/500, Train metric: 2.9405
Estimator 190/500, Train metric: 2.9321
Estimator 191/500, Train metric: 2.9261
Estimator 192/500, Train metric: 2.9201
Estimator 193/500, Train metric: 2.9135
Estimator 194/500, Train metric: 2.9088
Estimator 195/500, Train metric: 2.8975
Estimator 196/500, Train metric: 2.8881
Estimator 197/500, Train metric: 2.8742
Estimator 198/500, Train metric: 2.8684
Estimator 199/500, Train metric: 2.8613
Estimator 200/500, Train metric: 2.8555
Estimator 201/500, Train metric: 2.8489
Estimator 202/500, Train metric: 2.8420
Estimator 203/500, Train metric: 2.8275
Estimator 204/500, Train metric: 2.8217
Estimator 205/500, Train metric: 2.8150
Estimator 206/500, Train metric: 2.8103
Estimator 207/500, Train metric: 2.8058
Estimator 208/500, Train metric: 2.7999
Estimator 209/500, Train metric: 2.7931
Estimator 210/500, Train metric: 2.7872
Estimator 211/500, Train metric: 2.7743
Estimator 212/500, Train metric: 2.7707
Estimator 213/500, Train metric: 2.7654
Estimator 214/500, Train metric: 2.7556
Estimator 215/500, Train metric: 2.7483
Estimator 216/500, Train metric: 2.7382
Estimator 217/500, Train metric: 2.7299
Estimator 218/500, Train metric: 2.7269
Estimator 219/500, Train metric: 2.7226
Estimator 220/500, Train metric: 2.7129
Estimator 221/500, Train metric: 2.7048
Estimator 222/500, Train metric: 2.7002
Estimator 223/500, Train metric: 2.6941
Estimator 224/500, Train metric: 2.6897
Estimator 225/500, Train metric: 2.6838
Estimator 226/500, Train metric: 2.6791
Estimator 227/500, Train metric: 2.6712
Estimator 228/500, Train metric: 2.6630
Estimator 229/500, Train metric: 2.6604
Estimator 230/500, Train metric: 2.6548
Estimator 231/500, Train metric: 2.6494
Estimator 232/500, Train metric: 2.6421
Estimator 233/500, Train metric: 2.6338
Estimator 234/500, Train metric: 2.6278
Estimator 235/500, Train metric: 2.6182
Estimator 236/500, Train metric: 2.6062
Estimator 237/500, Train metric: 2.6020
Estimator 238/500, Train metric: 2.5936
Estimator 239/500, Train metric: 2.5872
Estimator 240/500, Train metric: 2.5800
Estimator 241/500, Train metric: 2.5720
Estimator 242/500, Train metric: 2.5673
Estimator 243/500, Train metric: 2.5595
Estimator 244/500, Train metric: 2.5574
Estimator 245/500, Train metric: 2.5481
Estimator 246/500, Train metric: 2.5404
Estimator 247/500, Train metric: 2.5359
Estimator 248/500, Train metric: 2.5319
Estimator 249/500, Train metric: 2.5189
Estimator 250/500, Train metric: 2.5146
Estimator 251/500, Train metric: 2.5099
Estimator 252/500, Train metric: 2.5044
Estimator 253/500, Train metric: 2.4956
Estimator 254/500, Train metric: 2.4889
Estimator 255/500, Train metric: 2.4810
Estimator 256/500, Train metric: 2.4780
Estimator 257/500, Train metric: 2.4701
Estimator 258/500, Train metric: 2.4647
Estimator 259/500, Train metric: 2.4624
Estimator 260/500, Train metric: 2.4568
Estimator 261/500, Train metric: 2.4536
Estimator 262/500, Train metric: 2.4497
Estimator 263/500, Train metric: 2.4450
Estimator 264/500, Train metric: 2.4385
Estimator 265/500, Train metric: 2.4325
Estimator 266/500, Train metric: 2.4276
Estimator 267/500, Train metric: 2.4244
Estimator 268/500, Train metric: 2.4217
Estimator 269/500, Train metric: 2.4175
Estimator 270/500, Train metric: 2.4112
Estimator 271/500, Train metric: 2.4084
Estimator 272/500, Train metric: 2.4042
Estimator 273/500, Train metric: 2.4012
Estimator 274/500, Train metric: 2.3943
Estimator 275/500, Train metric: 2.3896
Estimator 276/500, Train metric: 2.3828
Estimator 277/500, Train metric: 2.3756
Estimator 278/500, Train metric: 2.3641
Estimator 279/500, Train metric: 2.3589
Estimator 280/500, Train metric: 2.3536
Estimator 281/500, Train metric: 2.3477
Estimator 282/500, Train metric: 2.3419
Estimator 283/500, Train metric: 2.3369
Estimator 284/500, Train metric: 2.3323
Estimator 285/500, Train metric: 2.3221
Estimator 286/500, Train metric: 2.3148
Estimator 287/500, Train metric: 2.3123
Estimator 288/500, Train metric: 2.3078
Estimator 289/500, Train metric: 2.3046
Estimator 290/500, Train metric: 2.2986
Estimator 291/500, Train metric: 2.2915
Estimator 292/500, Train metric: 2.2866
Estimator 293/500, Train metric: 2.2860
Estimator 294/500, Train metric: 2.2816
Estimator 295/500, Train metric: 2.2772
Estimator 296/500, Train metric: 2.2706
Estimator 297/500, Train metric: 2.2680
Estimator 298/500, Train metric: 2.2671
Estimator 299/500, Train metric: 2.2644
Estimator 300/500, Train metric: 2.2600
Estimator 301/500, Train metric: 2.2550
Estimator 302/500, Train metric: 2.2509
Estimator 303/500, Train metric: 2.2483
Estimator 304/500, Train metric: 2.2465
Estimator 305/500, Train metric: 2.2423
Estimator 306/500, Train metric: 2.2364
Estimator 307/500, Train metric: 2.2321
Estimator 308/500, Train metric: 2.2293
Estimator 309/500, Train metric: 2.2249
Estimator 310/500, Train metric: 2.2213
Estimator 311/500, Train metric: 2.2178
Estimator 312/500, Train metric: 2.2160
Estimator 313/500, Train metric: 2.2080
Estimator 314/500, Train metric: 2.1977
Estimator 315/500, Train metric: 2.1909
Estimator 316/500, Train metric: 2.1879
Estimator 317/500, Train metric: 2.1860
Estimator 318/500, Train metric: 2.1829
Estimator 319/500, Train metric: 2.1796
Estimator 320/500, Train metric: 2.1768
Estimator 321/500, Train metric: 2.1741
Estimator 322/500, Train metric: 2.1696
Estimator 323/500, Train metric: 2.1668
Estimator 324/500, Train metric: 2.1623
Estimator 325/500, Train metric: 2.1549
Estimator 326/500, Train metric: 2.1527
Estimator 327/500, Train metric: 2.1517
Estimator 328/500, Train metric: 2.1474
Estimator 329/500, Train metric: 2.1458
Estimator 330/500, Train metric: 2.1442
Estimator 331/500, Train metric: 2.1423
Estimator 332/500, Train metric: 2.1393
Estimator 333/500, Train metric: 2.1333
Estimator 334/500, Train metric: 2.1293
Estimator 335/500, Train metric: 2.1264
Estimator 336/500, Train metric: 2.1239
Estimator 337/500, Train metric: 2.1204
Estimator 338/500, Train metric: 2.1173
Estimator 339/500, Train metric: 2.1142
Estimator 340/500, Train metric: 2.1101
Estimator 341/500, Train metric: 2.1076
Estimator 342/500, Train metric: 2.1015
Estimator 343/500, Train metric: 2.0975
Estimator 344/500, Train metric: 2.0948
Estimator 345/500, Train metric: 2.0920
Estimator 346/500, Train metric: 2.0891
Estimator 347/500, Train metric: 2.0846
Estimator 348/500, Train metric: 2.0833
Estimator 349/500, Train metric: 2.0770
Estimator 350/500, Train metric: 2.0756
Estimator 351/500, Train metric: 2.0717
Estimator 352/500, Train metric: 2.0692
Estimator 353/500, Train metric: 2.0664
Estimator 354/500, Train metric: 2.0644
Estimator 355/500, Train metric: 2.0620
Estimator 356/500, Train metric: 2.0564
Estimator 357/500, Train metric: 2.0529
Estimator 358/500, Train metric: 2.0432
Estimator 359/500, Train metric: 2.0359
Estimator 360/500, Train metric: 2.0328
Estimator 361/500, Train metric: 2.0299
Estimator 362/500, Train metric: 2.0279
Estimator 363/500, Train metric: 2.0263
Estimator 364/500, Train metric: 2.0238
Estimator 365/500, Train metric: 2.0203
Estimator 366/500, Train metric: 2.0167
Estimator 367/500, Train metric: 2.0138
Estimator 368/500, Train metric: 2.0081
Estimator 369/500, Train metric: 2.0064
Estimator 370/500, Train metric: 2.0037
Estimator 371/500, Train metric: 1.9992
Estimator 372/500, Train metric: 1.9978
Estimator 373/500, Train metric: 1.9951
Estimator 374/500, Train metric: 1.9934
Estimator 375/500, Train metric: 1.9927
Estimator 376/500, Train metric: 1.9838
Estimator 377/500, Train metric: 1.9813
Estimator 378/500, Train metric: 1.9765
Estimator 379/500, Train metric: 1.9740
Estimator 380/500, Train metric: 1.9715
Estimator 381/500, Train metric: 1.9684
Estimator 382/500, Train metric: 1.9658
Estimator 383/500, Train metric: 1.9626
Estimator 384/500, Train metric: 1.9560
Estimator 385/500, Train metric: 1.9538
Estimator 386/500, Train metric: 1.9494
Estimator 387/500, Train metric: 1.9450
Estimator 388/500, Train metric: 1.9424
Estimator 389/500, Train metric: 1.9360
Estimator 390/500, Train metric: 1.9336
Estimator 391/500, Train metric: 1.9277
Estimator 392/500, Train metric: 1.9248
Estimator 393/500, Train metric: 1.9224
Estimator 394/500, Train metric: 1.9206
Estimator 395/500, Train metric: 1.9193
Estimator 396/500, Train metric: 1.9167
Estimator 397/500, Train metric: 1.9160
Estimator 398/500, Train metric: 1.9094
Estimator 399/500, Train metric: 1.9071
Estimator 400/500, Train metric: 1.9037
Estimator 401/500, Train metric: 1.9013
Estimator 402/500, Train metric: 1.8992
Estimator 403/500, Train metric: 1.8980
Estimator 404/500, Train metric: 1.8957
Estimator 405/500, Train metric: 1.8936
Estimator 406/500, Train metric: 1.8919
Estimator 407/500, Train metric: 1.8902
Estimator 408/500, Train metric: 1.8866
Estimator 409/500, Train metric: 1.8834
Estimator 410/500, Train metric: 1.8809
Estimator 411/500, Train metric: 1.8794
Estimator 412/500, Train metric: 1.8764
Estimator 413/500, Train metric: 1.8738
Estimator 414/500, Train metric: 1.8698
Estimator 415/500, Train metric: 1.8677
Estimator 416/500, Train metric: 1.8650
Estimator 417/500, Train metric: 1.8637
Estimator 418/500, Train metric: 1.8627
Estimator 419/500, Train metric: 1.8589
Estimator 420/500, Train metric: 1.8541
Estimator 421/500, Train metric: 1.8533
Estimator 422/500, Train metric: 1.8519
Estimator 423/500, Train metric: 1.8496
Estimator 424/500, Train metric: 1.8486
Estimator 425/500, Train metric: 1.8475
Estimator 426/500, Train metric: 1.8455
Estimator 427/500, Train metric: 1.8421
Estimator 428/500, Train metric: 1.8393
Estimator 429/500, Train metric: 1.8366
Estimator 430/500, Train metric: 1.8347
Estimator 431/500, Train metric: 1.8327
Estimator 432/500, Train metric: 1.8308
Estimator 433/500, Train metric: 1.8287
Estimator 434/500, Train metric: 1.8247
Estimator 435/500, Train metric: 1.8223
Estimator 436/500, Train metric: 1.8168
Estimator 437/500, Train metric: 1.8149
Estimator 438/500, Train metric: 1.8135
Estimator 439/500, Train metric: 1.8121
Estimator 440/500, Train metric: 1.8100
Estimator 441/500, Train metric: 1.8079
Estimator 442/500, Train metric: 1.8059
Estimator 443/500, Train metric: 1.8056
Estimator 444/500, Train metric: 1.8044
Estimator 445/500, Train metric: 1.8041
Estimator 446/500, Train metric: 1.8012
Estimator 447/500, Train metric: 1.7967
Estimator 448/500, Train metric: 1.7957
Estimator 449/500, Train metric: 1.7925
Estimator 450/500, Train metric: 1.7911
Estimator 451/500, Train metric: 1.7887
Estimator 452/500, Train metric: 1.7872
Estimator 453/500, Train metric: 1.7838
Estimator 454/500, Train metric: 1.7820
Estimator 455/500, Train metric: 1.7805
Estimator 456/500, Train metric: 1.7787
Estimator 457/500, Train metric: 1.7775
Estimator 458/500, Train metric: 1.7752
Estimator 459/500, Train metric: 1.7740
Estimator 460/500, Train metric: 1.7704
Estimator 461/500, Train metric: 1.7690
Estimator 462/500, Train metric: 1.7686
Estimator 463/500, Train metric: 1.7662
Estimator 464/500, Train metric: 1.7633
Estimator 465/500, Train metric: 1.7617
Estimator 466/500, Train metric: 1.7598
Estimator 467/500, Train metric: 1.7583
Estimator 468/500, Train metric: 1.7581
Estimator 469/500, Train metric: 1.7566
Estimator 470/500, Train metric: 1.7550
Estimator 471/500, Train metric: 1.7545
Estimator 472/500, Train metric: 1.7526
Estimator 473/500, Train metric: 1.7501
Estimator 474/500, Train metric: 1.7466
Estimator 475/500, Train metric: 1.7446
Estimator 476/500, Train metric: 1.7435
Estimator 477/500, Train metric: 1.7424
Estimator 478/500, Train metric: 1.7372
Estimator 479/500, Train metric: 1.7350
Estimator 480/500, Train metric: 1.7296
Estimator 481/500, Train metric: 1.7264
Estimator 482/500, Train metric: 1.7253
Estimator 483/500, Train metric: 1.7245
Estimator 484/500, Train metric: 1.7181
Estimator 485/500, Train metric: 1.7164
Estimator 486/500, Train metric: 1.7149
Estimator 487/500, Train metric: 1.7110
Estimator 488/500, Train metric: 1.7099
Estimator 489/500, Train metric: 1.7087
Estimator 490/500, Train metric: 1.7080
Estimator 491/500, Train metric: 1.7056
Estimator 492/500, Train metric: 1.7047
Estimator 493/500, Train metric: 1.7010
Estimator 494/500, Train metric: 1.6983
Estimator 495/500, Train metric: 1.6946
Estimator 496/500, Train metric: 1.6933
Estimator 497/500, Train metric: 1.6912
Estimator 498/500, Train metric: 1.6903
Estimator 499/500, Train metric: 1.6895
Mean Squared Error: 105.24
        Mean    StdDev    Actual

In [21]:
generate_and_save_plots(predictions_PGBM_df, y_test, "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/PGBM_Prob.xlsx")

Excel file saved at ./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/PGBM_Prob.xlsx

In [22]:
generate_and_save_crps_decomposition(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/PGBM_Prob.xlsx
   Sheets: CRPS_Summary_PGBM, CRPS_Bins_PGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  PGBM     4.31491     4.425673   13.842683     13.73192        10

In [23]:
generate_and_save_pit_results(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/PGBM_Prob.xlsx

         PIT_Value
0     3.254236e-01
1     9.999943e-01
2     2.301889e-02
3     2.746809e-04
4    3.127636e-138
..             ...
181   5.905066e-01
182   2.865421e-67
183   1.667171e-01
184   9.999993e-01
185   7.140577e-01

[186 rows x 1 columns]

In [24]:
generate_and_save_calibration_curve(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/PGBM_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.408602        0.308602
2                  0.2            0.430108        0.230108
3                  0.3            0.440860        0.140860
4                  0.4            0.451613        0.051613
5                  0.5            0.483871        0.016129
6                  0.6            0.500000        0.100000
7                  0.7            0.510753        0.189247
8                  0.8            0.553763        0.246237
9                  0.9            0.569892        0.330108
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using GPBoost (Treeffuser)**

In [25]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

gpboost_score_engine = TreeBasedScoreModel(
    model_name='gpboost',
    model_params=best_params,
    seed=42,
    verbose=-1
)

# The fix is in the line below: '_score_model' has been corrected to 'score_model'.
model = Treeffuser(score_model=gpboost_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_GPBoost_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GPBoost_TF_df.head())

[1]	valid_0's l2: 0.451541
[2]	valid_0's l2: 0.365441
[3]	valid_0's l2: 0.31948
[4]	valid_0's l2: 0.275213
[5]	valid_0's l2: 0.255516
[6]	valid_0's l2: 0.253049
[7]	valid_0's l2: 0.237431
[8]	valid_0's l2: 0.243928
[9]	valid_0's l2: 0.233183
[10]	valid_0's l2: 0.22968
[11]	valid_0's l2: 0.21646
[12]	valid_0's l2: 0.208013
[13]	valid_0's l2: 0.209577
[14]	valid_0's l2: 0.202216
[15]	valid_0's l2: 0.203377
[16]	valid_0's l2: 0.206575
[17]	valid_0's l2: 0.20696
[18]	valid_0's l2: 0.202508
[19]	valid_0's l2: 0.203547
[20]	valid_0's l2: 0.202905
[21]	valid_0's l2: 0.197044
[22]	valid_0's l2: 0.199205
[23]	valid_0's l2: 0.201562
[24]	valid_0's l2: 0.198016
[25]	valid_0's l2: 0.195332
[26]	valid_0's l2: 0.192286
[27]	valid_0's l2: 0.193957
[28]	valid_0's l2: 0.193467
[29]	valid_0's l2: 0.191088
[30]	valid_0's l2: 0.193111
[31]	valid_0's l2: 0.191225
[32]	valid_0's l2: 0.194353
[33]	valid_0's l2: 0.192988
[34]	valid_0's l2: 0.19168
[35]	valid_0's l2: 0.19172
[36]	valid_0's l2: 0.190321
[37]	valid_0's l2: 0.191248
[38]	valid_0's l2: 0.191021
[39]	valid_0's l2: 0.189818
[40]	valid_0's l2: 0.191386
[41]	valid_0's l2: 0.195547
[42]	valid_0's l2: 0.19593
[43]	valid_0's l2: 0.197588
[44]	valid_0's l2: 0.198556
[45]	valid_0's l2: 0.198564
[46]	valid_0's l2: 0.196633
[47]	valid_0's l2: 0.195945
[48]	valid_0's l2: 0.196879
[49]	valid_0's l2: 0.198997
[50]	valid_0's l2: 0.19796
[51]	valid_0's l2: 0.198721
[52]	valid_0's l2: 0.199791
[53]	valid_0's l2: 0.19897
[54]	valid_0's l2: 0.199209
[55]	valid_0's l2: 0.199383
[56]	valid_0's l2: 0.202128
[57]	valid_0's l2: 0.201889
[58]	valid_0's l2: 0.200898
[59]	valid_0's l2: 0.202273
[60]	valid_0's l2: 0.203849
[61]	valid_0's l2: 0.201516
[62]	valid_0's l2: 0.199671
[63]	valid_0's l2: 0.199716
[64]	valid_0's l2: 0.198857
[65]	valid_0's l2: 0.197653
[66]	valid_0's l2: 0.197708
[67]	valid_0's l2: 0.197252
[68]	valid_0's l2: 0.199563
[69]	valid_0's l2: 0.199942
[70]	valid_0's l2: 0.196465
[71]	valid_0's l2: 0.195586
[72]	valid_0's l2: 0.194432
[73]	valid_0's l2: 0.193705
[74]	valid_0's l2: 0.191179
[75]	valid_0's l2: 0.194229
[76]	valid_0's l2: 0.195063
[77]	valid_0's l2: 0.196903
[78]	valid_0's l2: 0.194746
[79]	valid_0's l2: 0.194485
[80]	valid_0's l2: 0.195106
[81]	valid_0's l2: 0.194535
[82]	valid_0's l2: 0.193662
[83]	valid_0's l2: 0.192066
[84]	valid_0's l2: 0.192411
[85]	valid_0's l2: 0.190364
[86]	valid_0's l2: 0.188479
[87]	valid_0's l2: 0.188506
[88]	valid_0's l2: 0.188259
[89]	valid_0's l2: 0.188091
[90]	valid_0's l2: 0.18899
[91]	valid_0's l2: 0.190177
[92]	valid_0's l2: 0.189917
[93]	valid_0's l2: 0.187533
[94]	valid_0's l2: 0.186699
[95]	valid_0's l2: 0.188285
[96]	valid_0's l2: 0.188851
[97]	valid_0's l2: 0.189592
[98]	valid_0's l2: 0.185174
[99]	valid_0's l2: 0.185069
[100]	valid_0's l2: 0.18503
[101]	valid_0's l2: 0.184115
[102]	valid_0's l2: 0.184732
[103]	valid_0's l2: 0.185564
[104]	valid_0's l2: 0.184422
[105]	valid_0's l2: 0.18328
[106]	valid_0's l2: 0.183709
[107]	valid_0's l2: 0.183287
[108]	valid_0's l2: 0.185378
[109]	valid_0's l2: 0.185617
[110]	valid_0's l2: 0.184014
[111]	valid_0's l2: 0.183457
[112]	valid_0's l2: 0.184039
[113]	valid_0's l2: 0.184225
[114]	valid_0's l2: 0.18431
[115]	valid_0's l2: 0.182908
[116]	valid_0's l2: 0.181908
[117]	valid_0's l2: 0.183492
[118]	valid_0's l2: 0.183094
[119]	valid_0's l2: 0.18242
[120]	valid_0's l2: 0.182263
[121]	valid_0's l2: 0.17968
[122]	valid_0's l2: 0.179218
[123]	valid_0's l2: 0.182666
[124]	valid_0's l2: 0.181986
[125]	valid_0's l2: 0.182032
[126]	valid_0's l2: 0.183116
[127]	valid_0's l2: 0.183045
[128]	valid_0's l2: 0.183478
[129]	valid_0's l2: 0.183579
[130]	valid_0's l2: 0.182757
[131]	valid_0's l2: 0.182454
[132]	valid_0's l2: 0.182492
[133]	valid_0's l2: 0.181254
[134]	valid_0's l2: 0.180627
[135]	valid_0's l2: 0.180597
[136]	valid_0's l2: 0.179527
[137]	valid_0's l2: 0.18043
[138]	valid_0's l2: 0.181048
[139]	valid_0's l2: 0.180875
[140]	valid_0's l2: 0.180583
[141]	valid_0's l2: 0.180995
[142]	valid_0's l2: 0.180321
[143]	valid_0's l2: 0.180719
[144]	valid_0's l2: 0.178785
[145]	valid_0's l2: 0.178852
[146]	valid_0's l2: 0.179
[147]	valid_0's l2: 0.178518
[148]	valid_0's l2: 0.178213
[149]	valid_0's l2: 0.177507
[150]	valid_0's l2: 0.177565
[151]	valid_0's l2: 0.176663
[152]	valid_0's l2: 0.176954
[153]	valid_0's l2: 0.176733
[154]	valid_0's l2: 0.175922
[155]	valid_0's l2: 0.175445
[156]	valid_0's l2: 0.175717
[157]	valid_0's l2: 0.175581
[158]	valid_0's l2: 0.173784
[159]	valid_0's l2: 0.173757
[160]	valid_0's l2: 0.174815
[161]	valid_0's l2: 0.174892
[162]	valid_0's l2: 0.175131
[163]	valid_0's l2: 0.174956
[164]	valid_0's l2: 0.173841
[165]	valid_0's l2: 0.174853
[166]	valid_0's l2: 0.173907
[167]	valid_0's l2: 0.173955
[168]	valid_0's l2: 0.173483
[169]	valid_0's l2: 0.173414
[170]	valid_0's l2: 0.174405
[171]	valid_0's l2: 0.17441
[172]	valid_0's l2: 0.173217
[173]	valid_0's l2: 0.171883
[174]	valid_0's l2: 0.171523
[175]	valid_0's l2: 0.171291
[176]	valid_0's l2: 0.172208
[177]	valid_0's l2: 0.17241
[178]	valid_0's l2: 0.172794
[179]	valid_0's l2: 0.172569
[180]	valid_0's l2: 0.172303
[181]	valid_0's l2: 0.172314
[182]	valid_0's l2: 0.172136
[183]	valid_0's l2: 0.171363
[184]	valid_0's l2: 0.170685
[185]	valid_0's l2: 0.170387
[186]	valid_0's l2: 0.170593
[187]	valid_0's l2: 0.169487
[188]	valid_0's l2: 0.171543
[189]	valid_0's l2: 0.17238
[190]	valid_0's l2: 0.171679
[191]	valid_0's l2: 0.171645
[192]	valid_0's l2: 0.171831
[193]	valid_0's l2: 0.171466
[194]	valid_0's l2: 0.171219
[195]	valid_0's l2: 0.171442
[196]	valid_0's l2: 0.171464
[197]	valid_0's l2: 0.172763
[198]	valid_0's l2: 0.167525
[199]	valid_0's l2: 0.168832
[200]	valid_0's l2: 0.16775
       Mean     StdDev    Actual
0  6.128511  10.284738  3.295000
1  4.175452   8.536538  4.595960
2  2.826399   6.293949  1.721250
3 -0.943798  15.597996  0.441964
4  2.288249   9.506998  0.000000

In [26]:
generate_and_save_plots(predictions_GPBoost_TF_df, y_test, "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx

In [27]:
generate_and_save_crps_decomposition(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx
   Sheets: CRPS_Summary_GPBoost, CRPS_Bins_GPBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  GPBoost     6.51199     6.649563   13.869493     13.73192        10

In [28]:
generate_and_save_pit_results(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx

     PIT_Value
0     0.391464
1     0.519644
2     0.430308
3     0.535396
4     0.404897
..         ...
181   0.402219
182   0.331246
183   0.450724
184   0.429233
185   0.519201

[186 rows x 1 columns]

In [29]:
generate_and_save_calibration_curve(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.010753        0.089247
2                  0.2            0.043011        0.156989
3                  0.3            0.086022        0.213978
4                  0.4            0.268817        0.131183
5                  0.5            0.731183        0.231183
6                  0.6            0.865591        0.265591
7                  0.7            0.903226        0.203226
8                  0.8            0.930108        0.130108
9                  0.9            0.940860        0.040860
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Gradient Boosting (Treeffuser)**

In [30]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

gbr_score_engine = TreeBasedScoreModel(
    model_name='gradient_boosting',
    model_params=best_params,
    seed=42,
)

model = Treeffuser(score_model=gbr_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_GBR_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GBR_TF_df.head())

        Mean     StdDev    Actual
0   6.138620  26.201791  3.295000
1   4.355901  23.233106  4.595960
2  -0.531343  23.642772  1.721250
3   2.892364  30.814537  0.441964
4  13.774154  79.136502  0.000000

In [31]:
generate_and_save_plots(predictions_GBR_TF_df, y_test, "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx

In [32]:
generate_and_save_crps_decomposition(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx",
    model_name="Gradient Boosting",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx
   Sheets: CRPS_Summary_Gradient Boosting, CRPS_Bins_Gradient Boosting

,Model,Total_CRPS,Reliability,Resolution,Uncertainty,Num_Bins
0,Gradient Boosting,9.888896,10.010528,13.853552,13.73192,10

In [33]:
generate_and_save_pit_results(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx",
    model_name="GBoosting",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx

     PIT_Value
0     0.456789
1     0.504122
2     0.537952
3     0.468309
4     0.430911
..         ...
181   0.433546
182   0.451855
183   0.468703
184   0.519573
185   0.535156

[186 rows x 1 columns]

In [34]:
generate_and_save_calibration_curve(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx",
    model_name="GBoosting",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.010753        0.189247
3                  0.3            0.075269        0.224731
4                  0.4            0.231183        0.168817
5                  0.5            0.677419        0.177419
6                  0.6            0.908602        0.308602
7                  0.7            0.940860        0.240860
8                  0.8            0.956989        0.156989
9                  0.9            0.983871        0.083871
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Catboost (Treeffuser)**

In [35]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

catboost_score_engine = TreeBasedScoreModel(
    model_name='catboost',
    model_params=best_params,
    seed=42,
)

model = Treeffuser(score_model=catboost_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_CatBoost_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_CatBoost_TF_df.head())

       Mean     StdDev    Actual
0  6.141716  20.045154  3.295000
1  2.603129  27.731967  4.595960
2  2.210629   1.521655  1.721250
3 -1.755824  15.953162  0.441964
4  1.695117   8.318541  0.000000

In [36]:
generate_and_save_plots(predictions_CatBoost_TF_df, y_test, "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx

In [37]:
generate_and_save_crps_decomposition(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx
   Sheets: CRPS_Summary_CatBoost, CRPS_Bins_CatBoost

      Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  CatBoost    7.109723     7.222174   13.844371     13.73192        10

In [38]:
generate_and_save_pit_results(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx

     PIT_Value
0     0.443534
1     0.528644
2     0.373874
3     0.554787
4     0.419264
..         ...
181   0.409188
182   0.474131
183   0.492287
184   0.444949
185   0.498795

[186 rows x 1 columns]

In [39]:
generate_and_save_calibration_curve(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.005376        0.094624
2                  0.2            0.032258        0.167742
3                  0.3            0.075269        0.224731
4                  0.4            0.204301        0.195699
5                  0.5            0.672043        0.172043
6                  0.6            0.881720        0.281720
7                  0.7            0.935484        0.235484
8                  0.8            0.951613        0.151613
9                  0.9            0.973118        0.073118
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using XGBoost (Treeffuser)**

In [40]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

xgb_score_engine = TreeBasedScoreModel(
    model_name='xgboost',
    model_params=best_params,
    seed=42,
    verbose=-1
)

model = Treeffuser(score_model=xgb_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_XGB_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_XGB_TF_df.head())

[0]	validation_0-rmse:0.67428
[1]	validation_0-rmse:0.60823
[2]	validation_0-rmse:0.61569
[3]	validation_0-rmse:0.56435
[4]	validation_0-rmse:0.52690
[5]	validation_0-rmse:0.49738
[6]	validation_0-rmse:0.47673
[7]	validation_0-rmse:0.45438
[8]	validation_0-rmse:0.44553
[9]	validation_0-rmse:0.43921
[10]	validation_0-rmse:0.44112
[11]	validation_0-rmse:0.44587
[12]	validation_0-rmse:0.44827
[13]	validation_0-rmse:0.44793
[14]	validation_0-rmse:0.44126
[15]	validation_0-rmse:0.45318
[16]	validation_0-rmse:0.43997
[17]	validation_0-rmse:0.44187
[18]	validation_0-rmse:0.43235
[19]	validation_0-rmse:0.43940
[20]	validation_0-rmse:0.44149
[21]	validation_0-rmse:0.44205
[22]	validation_0-rmse:0.44322
[23]	validation_0-rmse:0.44367
[24]	validation_0-rmse:0.43819
[25]	validation_0-rmse:0.44317
[26]	validation_0-rmse:0.44111
[27]	validation_0-rmse:0.43560
[28]	validation_0-rmse:0.44654
[29]	validation_0-rmse:0.45215
[30]	validation_0-rmse:0.44800
[31]	validation_0-rmse:0.45449
[32]	validation_0-rmse:0.44004
[33]	validation_0-rmse:0.44126
[34]	validation_0-rmse:0.43928
[35]	validation_0-rmse:0.43748
[36]	validation_0-rmse:0.43346
[37]	validation_0-rmse:0.43299
[38]	validation_0-rmse:0.43573
[39]	validation_0-rmse:0.43319
[40]	validation_0-rmse:0.44085
[41]	validation_0-rmse:0.44309
[42]	validation_0-rmse:0.44424
[43]	validation_0-rmse:0.45587
[44]	validation_0-rmse:0.45531
[45]	validation_0-rmse:0.45552
[46]	validation_0-rmse:0.45772
[47]	validation_0-rmse:0.46144
[48]	validation_0-rmse:0.45838
[49]	validation_0-rmse:0.45711
[50]	validation_0-rmse:0.46063
[51]	validation_0-rmse:0.46120
[52]	validation_0-rmse:0.46369
[53]	validation_0-rmse:0.46363
[54]	validation_0-rmse:0.46351
[55]	validation_0-rmse:0.44643
[56]	validation_0-rmse:0.44017
[57]	validation_0-rmse:0.44665
[58]	validation_0-rmse:0.45055
[59]	validation_0-rmse:0.44935
[60]	validation_0-rmse:0.45070
[61]	validation_0-rmse:0.44587
[62]	validation_0-rmse:0.45240
[63]	validation_0-rmse:0.45415
[64]	validation_0-rmse:0.45048
[65]	validation_0-rmse:0.44833
[66]	validation_0-rmse:0.45138
[67]	validation_0-rmse:0.45107
[68]	validation_0-rmse:0.45257
[69]	validation_0-rmse:0.45250
[70]	validation_0-rmse:0.45641
[71]	validation_0-rmse:0.45775
[72]	validation_0-rmse:0.45430
[73]	validation_0-rmse:0.45349
[74]	validation_0-rmse:0.45260
[75]	validation_0-rmse:0.44919
[76]	validation_0-rmse:0.45011
[77]	validation_0-rmse:0.45750
[78]	validation_0-rmse:0.45821
[79]	validation_0-rmse:0.46265
[80]	validation_0-rmse:0.46659
[81]	validation_0-rmse:0.46342
[82]	validation_0-rmse:0.46265
[83]	validation_0-rmse:0.46821
[84]	validation_0-rmse:0.46435
[85]	validation_0-rmse:0.46224
[86]	validation_0-rmse:0.45639
[87]	validation_0-rmse:0.45180
[88]	validation_0-rmse:0.45687
[89]	validation_0-rmse:0.45612
[90]	validation_0-rmse:0.45666
[91]	validation_0-rmse:0.45676
[92]	validation_0-rmse:0.45764
[93]	validation_0-rmse:0.46215
[94]	validation_0-rmse:0.46627
[95]	validation_0-rmse:0.47074
[96]	validation_0-rmse:0.47168
[97]	validation_0-rmse:0.47342
[98]	validation_0-rmse:0.47165
[99]	validation_0-rmse:0.47745
[100]	validation_0-rmse:0.48070
[101]	validation_0-rmse:0.48453
[102]	validation_0-rmse:0.48499
[103]	validation_0-rmse:0.48749
[104]	validation_0-rmse:0.48837
[105]	validation_0-rmse:0.48911
[106]	validation_0-rmse:0.48956
[107]	validation_0-rmse:0.48689
[108]	validation_0-rmse:0.48762
[109]	validation_0-rmse:0.48583
[110]	validation_0-rmse:0.47988
[111]	validation_0-rmse:0.48428
[112]	validation_0-rmse:0.48360
[113]	validation_0-rmse:0.48112
[114]	validation_0-rmse:0.48217
[115]	validation_0-rmse:0.48174
[116]	validation_0-rmse:0.48338
[117]	validation_0-rmse:0.48427
[118]	validation_0-rmse:0.48445
[119]	validation_0-rmse:0.48434
[120]	validation_0-rmse:0.48307
[121]	validation_0-rmse:0.48131
[122]	validation_0-rmse:0.48183
[123]	validation_0-rmse:0.48188
[124]	validation_0-rmse:0.47739
[125]	validation_0-rmse:0.47451
[126]	validation_0-rmse:0.47372
[127]	validation_0-rmse:0.47377
[128]	validation_0-rmse:0.47425
[129]	validation_0-rmse:0.47479
[130]	validation_0-rmse:0.47372
[131]	validation_0-rmse:0.47357
[132]	validation_0-rmse:0.47425
[133]	validation_0-rmse:0.47356
[134]	validation_0-rmse:0.47628
[135]	validation_0-rmse:0.47737
[136]	validation_0-rmse:0.47328
[137]	validation_0-rmse:0.47222
[138]	validation_0-rmse:0.47323
[139]	validation_0-rmse:0.47288
[140]	validation_0-rmse:0.47317
[141]	validation_0-rmse:0.47315
[142]	validation_0-rmse:0.47298
[143]	validation_0-rmse:0.47334
[144]	validation_0-rmse:0.47144
[145]	validation_0-rmse:0.47296
[146]	validation_0-rmse:0.47212
[147]	validation_0-rmse:0.47109
[148]	validation_0-rmse:0.47094
[149]	validation_0-rmse:0.47229
[150]	validation_0-rmse:0.47142
[151]	validation_0-rmse:0.47157
[152]	validation_0-rmse:0.47370
[153]	validation_0-rmse:0.47325
[154]	validation_0-rmse:0.47475
[155]	validation_0-rmse:0.47540
[156]	validation_0-rmse:0.47478
[157]	validation_0-rmse:0.47158
[158]	validation_0-rmse:0.47116
[159]	validation_0-rmse:0.47053
[160]	validation_0-rmse:0.47083
[161]	validation_0-rmse:0.47209
[162]	validation_0-rmse:0.47097
[163]	validation_0-rmse:0.47144
[164]	validation_0-rmse:0.47154
[165]	validation_0-rmse:0.47182
[166]	validation_0-rmse:0.47319
[167]	validation_0-rmse:0.47260
[168]	validation_0-rmse:0.47326
[169]	validation_0-rmse:0.47215
[170]	validation_0-rmse:0.47208
[171]	validation_0-rmse:0.47165
[172]	validation_0-rmse:0.47263
[173]	validation_0-rmse:0.47256
[174]	validation_0-rmse:0.47340
[175]	validation_0-rmse:0.47318
[176]	validation_0-rmse:0.47320
[177]	validation_0-rmse:0.47329
[178]	validation_0-rmse:0.47471
[179]	validation_0-rmse:0.47408
[180]	validation_0-rmse:0.47524
[181]	validation_0-rmse:0.47446
[182]	validation_0-rmse:0.47392
[183]	validation_0-rmse:0.47401
[184]	validation_0-rmse:0.47376
[185]	validation_0-rmse:0.47439
[186]	validation_0-rmse:0.47430
[187]	validation_0-rmse:0.47374
[188]	validation_0-rmse:0.47404
[189]	validation_0-rmse:0.47423
[190]	validation_0-rmse:0.47353
[191]	validation_0-rmse:0.47393
[192]	validation_0-rmse:0.47331
[193]	validation_0-rmse:0.47406
[194]	validation_0-rmse:0.47455
[195]	validation_0-rmse:0.47493
[196]	validation_0-rmse:0.47479
[197]	validation_0-rmse:0.47384
[198]	validation_0-rmse:0.47279
[199]	validation_0-rmse:0.47261
[200]	validation_0-rmse:0.47007
[201]	validation_0-rmse:0.47206
[202]	validation_0-rmse:0.47290
[203]	validation_0-rmse:0.47182
[204]	validation_0-rmse:0.47196
[205]	validation_0-rmse:0.47268
[206]	validation_0-rmse:0.47321
[207]	validation_0-rmse:0.47370
[208]	validation_0-rmse:0.47510
[209]	validation_0-rmse:0.47655
[210]	validation_0-rmse:0.47624
[211]	validation_0-rmse:0.47664
[212]	validation_0-rmse:0.47793
[213]	validation_0-rmse:0.47780
[214]	validation_0-rmse:0.47833
[215]	validation_0-rmse:0.47564
[216]	validation_0-rmse:0.47528
[217]	validation_0-rmse:0.47398
[218]	validation_0-rmse:0.47311
[219]	validation_0-rmse:0.47329
[220]	validation_0-rmse:0.47396
[221]	validation_0-rmse:0.47286
[222]	validation_0-rmse:0.47278
[223]	validation_0-rmse:0.47174
[224]	validation_0-rmse:0.47208
[225]	validation_0-rmse:0.47226
[226]	validation_0-rmse:0.47169
[227]	validation_0-rmse:0.47144
[228]	validation_0-rmse:0.47131
[229]	validation_0-rmse:0.47145
[230]	validation_0-rmse:0.47053
[231]	validation_0-rmse:0.47119
[232]	validation_0-rmse:0.47115
[233]	validation_0-rmse:0.47197
[234]	validation_0-rmse:0.47158
[235]	validation_0-rmse:0.47308
[236]	validation_0-rmse:0.47050
[237]	validation_0-rmse:0.47067
[238]	validation_0-rmse:0.46963
[239]	validation_0-rmse:0.47071
[240]	validation_0-rmse:0.47079
[241]	validation_0-rmse:0.47032
[242]	validation_0-rmse:0.47116
[243]	validation_0-rmse:0.47161
[244]	validation_0-rmse:0.47243
[245]	validation_0-rmse:0.47251
[246]	validation_0-rmse:0.47243
[247]	validation_0-rmse:0.47180
[248]	validation_0-rmse:0.47193
[249]	validation_0-rmse:0.47274
[250]	validation_0-rmse:0.47353
[251]	validation_0-rmse:0.47357
[252]	validation_0-rmse:0.47310
[253]	validation_0-rmse:0.47317
[254]	validation_0-rmse:0.47278
[255]	validation_0-rmse:0.47274
[256]	validation_0-rmse:0.47282
[257]	validation_0-rmse:0.47259
[258]	validation_0-rmse:0.47389
[259]	validation_0-rmse:0.47373
[260]	validation_0-rmse:0.47420
[261]	validation_0-rmse:0.47404
[262]	validation_0-rmse:0.47439
[263]	validation_0-rmse:0.47421
[264]	validation_0-rmse:0.47415
[265]	validation_0-rmse:0.47383
[266]	validation_0-rmse:0.47253
[267]	validation_0-rmse:0.47369
[268]	validation_0-rmse:0.47386
[269]	validation_0-rmse:0.47279
[270]	validation_0-rmse:0.47184
[271]	validation_0-rmse:0.47199
[272]	validation_0-rmse:0.47113
[273]	validation_0-rmse:0.47260
[274]	validation_0-rmse:0.47335
[275]	validation_0-rmse:0.47401
[276]	validation_0-rmse:0.47409
[277]	validation_0-rmse:0.47422
[278]	validation_0-rmse:0.47430
[279]	validation_0-rmse:0.47412
[280]	validation_0-rmse:0.47311
[281]	validation_0-rmse:0.47330
[282]	validation_0-rmse:0.47261
[283]	validation_0-rmse:0.47369
[284]	validation_0-rmse:0.47324
[285]	validation_0-rmse:0.47283
[286]	validation_0-rmse:0.47279
[287]	validation_0-rmse:0.47341
[288]	validation_0-rmse:0.47394
[289]	validation_0-rmse:0.47469
[290]	validation_0-rmse:0.47452
[291]	validation_0-rmse:0.47470
[292]	validation_0-rmse:0.47486
[293]	validation_0-rmse:0.47559
[294]	validation_0-rmse:0.47546
[295]	validation_0-rmse:0.47530
[296]	validation_0-rmse:0.47620
[297]	validation_0-rmse:0.47666
[298]	validation_0-rmse:0.47621
[299]	validation_0-rmse:0.47583
[300]	validation_0-rmse:0.47575
[301]	validation_0-rmse:0.47531
[302]	validation_0-rmse:0.47489
[303]	validation_0-rmse:0.47436
[304]	validation_0-rmse:0.47497
[305]	validation_0-rmse:0.47442
[306]	validation_0-rmse:0.47520
[307]	validation_0-rmse:0.47497
[308]	validation_0-rmse:0.47570
[309]	validation_0-rmse:0.47511
[310]	validation_0-rmse:0.47486
[311]	validation_0-rmse:0.47478
[312]	validation_0-rmse:0.47391
[313]	validation_0-rmse:0.47372
[314]	validation_0-rmse:0.47436
[315]	validation_0-rmse:0.47486
[316]	validation_0-rmse:0.47419
[317]	validation_0-rmse:0.47388
[318]	validation_0-rmse:0.47430
[319]	validation_0-rmse:0.47498
[320]	validation_0-rmse:0.47493
[321]	validation_0-rmse:0.47523
[322]	validation_0-rmse:0.47506
[323]	validation_0-rmse:0.47658
[324]	validation_0-rmse:0.47622
[325]	validation_0-rmse:0.47575
[326]	validation_0-rmse:0.47576
[327]	validation_0-rmse:0.47621
[328]	validation_0-rmse:0.47574
[329]	validation_0-rmse:0.47521
[330]	validation_0-rmse:0.47547
[331]	validation_0-rmse:0.47524
[332]	validation_0-rmse:0.47498
[333]	validation_0-rmse:0.47492
[334]	validation_0-rmse:0.47503
[335]	validation_0-rmse:0.47477
[336]	validation_0-rmse:0.47471
[337]	validation_0-rmse:0.47473
[338]	validation_0-rmse:0.47458
[339]	validation_0-rmse:0.47442
[340]	validation_0-rmse:0.47423
[341]	validation_0-rmse:0.47458
[342]	validation_0-rmse:0.47494
[343]	validation_0-rmse:0.47520
[344]	validation_0-rmse:0.47508
[345]	validation_0-rmse:0.47498
[346]	validation_0-rmse:0.47524
[347]	validation_0-rmse:0.47544
[348]	validation_0-rmse:0.47571
[349]	validation_0-rmse:0.47571
[350]	validation_0-rmse:0.47488
[351]	validation_0-rmse:0.47568
[352]	validation_0-rmse:0.47516
[353]	validation_0-rmse:0.47501
[354]	validation_0-rmse:0.47475
[355]	validation_0-rmse:0.47482
[356]	validation_0-rmse:0.47502
[357]	validation_0-rmse:0.47523
[358]	validation_0-rmse:0.47514
[359]	validation_0-rmse:0.47502
[360]	validation_0-rmse:0.47497
[361]	validation_0-rmse:0.47448
[362]	validation_0-rmse:0.47485
[363]	validation_0-rmse:0.47502
[364]	validation_0-rmse:0.47517
[365]	validation_0-rmse:0.47542
[366]	validation_0-rmse:0.47500
[367]	validation_0-rmse:0.47489
[368]	validation_0-rmse:0.47651
[369]	validation_0-rmse:0.47643
[370]	validation_0-rmse:0.47643
[371]	validation_0-rmse:0.47637
[372]	validation_0-rmse:0.47618
[373]	validation_0-rmse:0.47585
[374]	validation_0-rmse:0.47568
[375]	validation_0-rmse:0.47448
[376]	validation_0-rmse:0.47478
[377]	validation_0-rmse:0.47483
[378]	validation_0-rmse:0.47508
[379]	validation_0-rmse:0.47465
[380]	validation_0-rmse:0.47479
[381]	validation_0-rmse:0.47463
[382]	validation_0-rmse:0.47508
[383]	validation_0-rmse:0.47483
[384]	validation_0-rmse:0.47467
[385]	validation_0-rmse:0.47499
[386]	validation_0-rmse:0.47497
[387]	validation_0-rmse:0.47494
[388]	validation_0-rmse:0.47441
[389]	validation_0-rmse:0.47394
[390]	validation_0-rmse:0.47355
[391]	validation_0-rmse:0.47337
[392]	validation_0-rmse:0.47321
[393]	validation_0-rmse:0.47329
[394]	validation_0-rmse:0.47333
[395]	validation_0-rmse:0.47390
[396]	validation_0-rmse:0.47421
[397]	validation_0-rmse:0.47424
[398]	validation_0-rmse:0.47440
[399]	validation_0-rmse:0.47455
[400]	validation_0-rmse:0.47432
[401]	validation_0-rmse:0.47373
[402]	validation_0-rmse:0.47374
[403]	validation_0-rmse:0.47368
[404]	validation_0-rmse:0.47355
[405]	validation_0-rmse:0.47358
[406]	validation_0-rmse:0.47327
[407]	validation_0-rmse:0.47372
[408]	validation_0-rmse:0.47346
[409]	validation_0-rmse:0.47314
[410]	validation_0-rmse:0.47198
[411]	validation_0-rmse:0.47182
[412]	validation_0-rmse:0.47219
[413]	validation_0-rmse:0.47205
[414]	validation_0-rmse:0.47200
[415]	validation_0-rmse:0.47181
[416]	validation_0-rmse:0.47129
[417]	validation_0-rmse:0.47121
[418]	validation_0-rmse:0.47130
[419]	validation_0-rmse:0.47101
[420]	validation_0-rmse:0.47076
[421]	validation_0-rmse:0.47089
[422]	validation_0-rmse:0.47124
[423]	validation_0-rmse:0.47136
[424]	validation_0-rmse:0.47148
[425]	validation_0-rmse:0.47161
[426]	validation_0-rmse:0.47158
[427]	validation_0-rmse:0.47192
[428]	validation_0-rmse:0.47207
[429]	validation_0-rmse:0.47217
[430]	validation_0-rmse:0.47272
[431]	validation_0-rmse:0.47316
[432]	validation_0-rmse:0.47316
[433]	validation_0-rmse:0.47345
[434]	validation_0-rmse:0.47310
[435]	validation_0-rmse:0.47305
[436]	validation_0-rmse:0.47288
[437]	validation_0-rmse:0.47289
[438]	validation_0-rmse:0.47309
[439]	validation_0-rmse:0.47297
[440]	validation_0-rmse:0.47297
[441]	validation_0-rmse:0.47302
[442]	validation_0-rmse:0.47322
[443]	validation_0-rmse:0.47316
[444]	validation_0-rmse:0.47336
[445]	validation_0-rmse:0.47341
[446]	validation_0-rmse:0.47335
[447]	validation_0-rmse:0.47312
[448]	validation_0-rmse:0.47292
[449]	validation_0-rmse:0.47292
[450]	validation_0-rmse:0.47279
[451]	validation_0-rmse:0.47259
[452]	validation_0-rmse:0.47229
[453]	validation_0-rmse:0.47231
[454]	validation_0-rmse:0.47215
[455]	validation_0-rmse:0.47286
[456]	validation_0-rmse:0.47345
[457]	validation_0-rmse:0.47361
[458]	validation_0-rmse:0.47362
[459]	validation_0-rmse:0.47364
[460]	validation_0-rmse:0.47360
[461]	validation_0-rmse:0.47355
[462]	validation_0-rmse:0.47375
[463]	validation_0-rmse:0.47363
[464]	validation_0-rmse:0.47387
[465]	validation_0-rmse:0.47380
[466]	validation_0-rmse:0.47365
[467]	validation_0-rmse:0.47388
[468]	validation_0-rmse:0.47369
[469]	validation_0-rmse:0.47369
[470]	validation_0-rmse:0.47378
[471]	validation_0-rmse:0.47383
[472]	validation_0-rmse:0.47375
[473]	validation_0-rmse:0.47276
[474]	validation_0-rmse:0.47309
[475]	validation_0-rmse:0.47332
[476]	validation_0-rmse:0.47321
[477]	validation_0-rmse:0.47292
[478]	validation_0-rmse:0.47300
[479]	validation_0-rmse:0.47302
[480]	validation_0-rmse:0.47294
[481]	validation_0-rmse:0.47273
[482]	validation_0-rmse:0.47274
[483]	validation_0-rmse:0.47278
[484]	validation_0-rmse:0.47262
[485]	validation_0-rmse:0.47271
[486]	validation_0-rmse:0.47259
[487]	validation_0-rmse:0.47239
[488]	validation_0-rmse:0.47241
[489]	validation_0-rmse:0.47281
[490]	validation_0-rmse:0.47285
[491]	validation_0-rmse:0.47294
[492]	validation_0-rmse:0.47308
[493]	validation_0-rmse:0.47299
[494]	validation_0-rmse:0.47306
[495]	validation_0-rmse:0.47278
[496]	validation_0-rmse:0.47330
[497]	validation_0-rmse:0.47359
[498]	validation_0-rmse:0.47378
[499]	validation_0-rmse:0.47398
       Mean     StdDev    Actual
0  5.293639  14.880411  3.295000
1  4.902755   2.897875  4.595960
2  2.570917   0.607277  1.721250
3  0.360231   0.809084  0.441964
4  3.701619  10.720169  0.000000

In [41]:
generate_and_save_plots(predictions_XGB_TF_df, y_test, "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob_TF.xlsx

In [42]:
generate_and_save_crps_decomposition(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob_TF.xlsx
   Sheets: CRPS_Summary_XGBoost, CRPS_Bins_XGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  XGBoost    5.494306     5.630991   13.868605     13.73192        10

In [43]:
generate_and_save_pit_results(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob_TF.xlsx

     PIT_Value
0     0.446577
1     0.457843
2     0.080885
3     0.540232
4     0.364936
..         ...
181   0.412731
182   0.361999
183   0.442411
184   0.568107
185   0.723254

[186 rows x 1 columns]

In [44]:
generate_and_save_calibration_curve(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.021505        0.078495
2                  0.2            0.086022        0.113978
3                  0.3            0.220430        0.079570
4                  0.4            0.413978        0.013978
5                  0.5            0.655914        0.155914
6                  0.6            0.833333        0.233333
7                  0.7            0.892473        0.192473
8                  0.8            0.924731        0.124731
9                  0.9            0.951613        0.051613
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using LGBM (Treeffuser)**

In [45]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

lgbm_score_engine = TreeBasedScoreModel(
    model_name='lightgbm',
    model_params=best_params,
    seed=42,
    verbose=-1
)

model = Treeffuser(score_model=lgbm_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_LGBM_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_LGBM_TF_df.head())

       Mean    StdDev    Actual
0  4.111459  1.955781  3.295000
1  5.384371  5.525806  4.595960
2  2.110637  3.114329  1.721250
3  0.383161  0.548204  0.441964
4  0.907726  3.458343  0.000000

In [46]:
generate_and_save_plots(predictions_LGBM_TF_df, y_test, "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob_TF.xlsx

In [47]:
generate_and_save_crps_decomposition(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob_TF.xlsx
   Sheets: CRPS_Summary_LightGBM, CRPS_Bins_LightGBM

      Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LightGBM    4.647307     4.777297   13.861909     13.73192        10

In [48]:
generate_and_save_pit_results(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob_TF.xlsx

     PIT_Value
0     0.338171
1     0.443272
2     0.450250
3     0.542711
4     0.396478
..         ...
181   0.251824
182   0.064046
183   0.443047
184   0.450329
185   0.536801

[186 rows x 1 columns]

In [49]:
generate_and_save_calibration_curve(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.026882        0.073118
2                  0.2            0.107527        0.092473
3                  0.3            0.182796        0.117204
4                  0.4            0.413978        0.013978
5                  0.5            0.688172        0.188172
6                  0.6            0.801075        0.201075
7                  0.7            0.881720        0.181720
8                  0.8            0.924731        0.124731
9                  0.9            0.946237        0.046237
10                 1.0            1.000000        0.000000

# **IBUG Installation**

In [50]:
# Clone the repository
!git clone https://github.com/jjbrophy47/ibug.git
%cd ibug

# Build extensions if needed
!python setup.py build_ext --inplace

# Install the package
!pip install .

# Verify installation
try:
    from ibug import IBUGWrapper
    print("IBUGWrapper imported successfully!")
except ImportError as e:
    print("Error importing IBUGWrapper:", e)

Cloning into 'ibug'...
remote: Enumerating objects: 1763, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 1763 (delta 18), reused 15 (delta 4), pack-reused 1726 (from 1)
Receiving objects: 100% (1763/1763), 1.31 MiB | 9.99 MiB/s, done.
Resolving deltas: 100% (967/967), done.
/content/ibug
Compiling ibug/parsers/_tree32.pyx because it changed.
Compiling ibug/parsers/_tree64.pyx because it changed.
[1/2] Cythonizing ibug/parsers/_tree32.pyx
performance hint: ibug/parsers/_tree32.pyx:84:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:112:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:140:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:238:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:266:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:312:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:344:47: Exception check after calling '_initialize_node' will always require the GIL to be acquired. Declare '_initialize_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:352:48: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:355:49: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:400:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:401:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:417:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:418:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:434:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:435:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:464:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:465:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
[2/2] Cythonizing ibug/parsers/_tree64.pyx
performance hint: ibug/parsers/_tree64.pyx:93:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:121:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:149:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:247:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:275:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:321:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:353:47: Exception check after calling '_initialize_node' will always require the GIL to be acquired. Declare '_initialize_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:361:48: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:364:49: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:409:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:410:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:426:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:427:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:443:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:444:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:473:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:474:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
running build_ext
building 'ibug.parsers._tree32' extension
creating build/temp.linux-x86_64-cpython-312/ibug/parsers
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c ibug/parsers/_tree32.c -o build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree32.o
In file included from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ibug/parsers/_tree32.c:1257:
/usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
creating build/lib.linux-x86_64-cpython-312/ibug/parsers
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree32.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree32.cpython-312-x86_64-linux-gnu.so
building 'ibug.parsers._tree64' extension
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c ibug/parsers/_tree64.c -o build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree64.o
In file included from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ibug/parsers/_tree64.c:1257:
/usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree64.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree64.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree32.cpython-312-x86_64-linux-gnu.so -> ibug/parsers
copying build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree64.cpython-312-x86_64-linux-gnu.so -> ibug/parsers
Processing /content/ibug
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.26.4)
Collecting uncertainty-toolbox>=0.1.0 (from ibug==0.0.12)
  Downloading uncertainty_toolbox-0.1.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: joblib>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.5.3)
Requirement already satisfied: scikit-learn>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.6.1)
Requirement already satisfied: scipy>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.16.3)
Requirement already satisfied: pandas>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (2.2.2)
Requirement already satisfied: Cython>=0.29.23 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (3.0.12)
Requirement already satisfied: xgboost>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.5.0->ibug==0.0.12) (3.6.0)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.12/dist-packages (from uncertainty-toolbox>=0.1.0->ibug==0.0.12) (3.10.0)
Requirement already satisfied: tqdm>=4.54.0 in /usr/local/lib/python3.12/dist-packages (from uncertainty-toolbox>=0.1.0->ibug==0.0.12) (4.67.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost>=1.6.1->ibug==0.0.12) (2.27.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.3->ibug==0.0.12) (1.17.0)
Downloading uncertainty_toolbox-0.1.1-py3-none-any.whl (24 kB)
Building wheels for collected packages: ibug
  Building wheel for ibug (pyproject.toml) ... done
  Created wheel for ibug: filename=ibug-0.0.12-cp312-cp312-linux_x86_64.whl size=1458001 sha256=8196881287d41b6ab1b87d72e734d53b202437e881f5b12e7ed1db69a722491b
  Stored in directory: /tmp/pip-ephem-wheel-cache-l8ixqkwz/wheels/bc/4c/24/9707d9556afa0b36e8ea6c7b2641eb7474f791664f4bb187cd
Successfully built ibug
Installing collected packages: uncertainty-toolbox, ibug
Successfully installed ibug-0.0.12 uncertainty-toolbox-0.1.1
IBUGWrapper imported successfully!

In [51]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3)

# **Probabilistic Distributions using LGBM (IBUG)**

In [52]:
# y_train = y_train.to_numpy()
# y_val = y_val.to_numpy()

In [53]:
# Assume hyperparameter tuning has been done and best_params are obtained
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

# --- Ensure IBUG compatibility ---
best_params['reg_alpha'] = 0
best_params['class_weight'] = None
best_params['boosting_type'] = 'gbdt'

# Initialize and train the LightGBM regressor using the best_params
model = LGBMRegressor(**best_params)
model.fit(X_train, y_train)

# Extend the trained model into a probabilistic predictor using IBUGWrapper
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# Use the model to predict the probabilistic distribution on the test data.
location, scale = prob_model.pred_dist(X_test)

# Optionally, to also get the k-nearest training indices and their values used in modeling
location2, scale2, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)

dev = scale**0.5
# Create a DataFrame for clarity
predictions_LGBM_df = pd.DataFrame({
    'Mean': location,
    'StdDev': dev,
    'Actual': y_test,
})

print(predictions_LGBM_df.head())

        Mean    StdDev    Actual
0   3.880292  0.977662  3.295000
1   6.058720  1.566365  4.595960
2   1.913773  0.987099  1.721250
3   0.533891  0.450271  0.441964
4  37.333590  4.587587  0.000000

In [54]:
%cd ..

/content

In [55]:
%cd ..

/

In [56]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob.xlsx")

Excel file saved at ./content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob.xlsx

In [57]:
generate_and_save_crps_decomposition(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob.xlsx
   Sheets: CRPS_Summary_LGBM, CRPS_Bins_LGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LGBM    5.411881     5.567934   13.887973     13.73192        10

In [58]:
generate_and_save_pit_results(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   /content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob.xlsx

        PIT_Value
0    2.746980e-01
1    1.751889e-01
2    4.226810e-01
3    4.191141e-01
4    2.009998e-16
..            ...
181  4.471134e-01
182  3.350659e-01
183  5.919419e-01
184  8.788670e-01
185  5.554458e-01

[186 rows x 1 columns]

In [59]:
generate_and_save_calibration_curve(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   /content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/LGBM_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.139785        0.039785
2                  0.2            0.198925        0.001075
3                  0.3            0.236559        0.063441
4                  0.4            0.344086        0.055914
5                  0.5            0.521505        0.021505
6                  0.6            0.715054        0.115054
7                  0.7            0.779570        0.079570
8                  0.8            0.838710        0.038710
9                  0.9            0.881720        0.018280
10                 1.0            1.000000        0.000000

# **Probabilistic Distributions using XGBoost (IBUG)**

In [60]:
# Assume hyperparameter tuning has been done and best_params are obtained
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

best_params['reg_alpha'] = 0
best_params['scale_pos_weight'] = 1
best_params['base_score'] = 0.5

# Initialize and train the XGBoost regressor using the best_params
model = XGBRegressor(**best_params)
model.fit(X_train, y_train)

# Extend the trained model into a probabilistic predictor using IBUGWrapper
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# Use the model to predict the probabilistic distribution on the test data.
# This returns the predicted mean (location) and uncertainty (scale, variance proxy)
location, scale = prob_model.pred_dist(X_test)

# Optionally, to also get the k-nearest training indices and their values used in modeling
location, scale, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)

# Calculate the standard deviation from the variance (scale)
std_dev = scale ** 0.5

# Create a DataFrame for clarity
predictions_XGB_df = pd.DataFrame({
    'Mean': location,
    'StdDev': std_dev,
    'Actual': y_test
})

print(predictions_XGB_df.head())

        Mean    StdDev    Actual
0   3.512149  1.138130  3.295000
1   7.054487  1.600900  4.595960
2   1.651625  0.997854  1.721250
3  -0.066082  1.602239  0.441964
4  41.338772  5.162925  0.000000

In [61]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob.xlsx")

Excel file saved at ./content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob.xlsx

In [62]:
generate_and_save_crps_decomposition(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_bins=10
)

✅ CRPS decomposition saved to:
/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob.xlsx
   Sheets: CRPS_Summary_XGB, CRPS_Bins_XGB

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0   XGB    5.385464     5.539979   13.886435     13.73192        10

In [63]:
generate_and_save_pit_results(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   /content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob.xlsx

        PIT_Value
0    4.243433e-01
1    6.230411e-02
2    5.278135e-01
3    6.244105e-01
4    5.884123e-16
..            ...
181  4.375177e-01
182  2.087248e-01
183  4.844769e-01
184  6.830895e-01
185  6.248034e-01

[186 rows x 1 columns]

In [64]:
generate_and_save_calibration_curve(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   /content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/XGB_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.182796        0.082796
2                  0.2            0.247312        0.047312
3                  0.3            0.311828        0.011828
4                  0.4            0.387097        0.012903
5                  0.5            0.543011        0.043011
6                  0.6            0.704301        0.104301
7                  0.7            0.806452        0.106452
8                  0.8            0.854839        0.054839
9                  0.9            0.870968        0.029032
10                 1.0            1.000000        0.000000

# **Matrix Evaulation**

In [65]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
folder_path = "/content/drive/MyDrive/pile_load_gendy_data"
excel_path = os.path.join(folder_path, "/content/drive/MyDrive/pile_load_gendy_data/Probabilistic_Distribution/Matrix Evaluation.xlsx")
with pd.ExcelWriter(excel_path, engine='xlsxwriter') as writer:
    plot_metrics_and_save_to_excel(writer, predictions_NGB_df, y_test, 'NGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_PGBM_df, y_test, 'PGBM')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_df, y_test, 'LGBM')
    plot_metrics_and_save_to_excel(writer, predictions_XGB_df, y_test, 'XGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_TF_df, y_test, "LightGBM_TF")
    plot_metrics_and_save_to_excel(writer, predictions_XGB_TF_df, y_test, "XGBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_CatBoost_TF_df, y_test, "CatBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_GPBoost_TF_df, y_test, "GPBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_GBR_TF_df, y_test, "GradientBoosting_TF")