# **Start Section:**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.environ["PIP_CONSTRAINT"] = "/tmp/numpy_constraint.txt"
!echo "numpy==1.26.4" > /tmp/numpy_constraint.txt

!pip uninstall -y torch torchaudio torchvision \
    torchao torchcodec torchdata torchtune torchsummary -q 2>/dev/null

!pip uninstall -y tensorflow tensorflow-text tensorflow-hub tf-keras \
    tensorflow_decision_forests tensorflow-probability \
    tensorflow-datasets tensorflow-metadata -q 2>/dev/null

!pip uninstall -y numpy scikit-learn shap xgboost lightgbm dask \
    seaborn plotly openpyxl Cython catboost interpret lime -q 2>/dev/null

!pip install numpy==1.26.4 -q
!pip install scikit-learn==1.6.1 -q
!pip install torch==2.9.0 -q

!pip install lightgbm==4.6.0 -q
!pip install xgboost==3.1.2 -q
!pip install catboost==1.2.8 -q
!pip install gpboost==1.6.1 -q
!pip install ngboost==0.5.8 -q
!pip install pgbm==2.2.0 -q
!pip install pytorch-tabnet2==4.5.3 -q

!pip install bayesian-optimization==3.2.0 -q
!pip install optuna==4.6.0 -q
!pip install optunahub==0.4.0 -q
!pip install cmaes==0.12.0 -q

!pip install shap==0.44.0 -q
!pip install lime==0.2.0.1 -q
!pip install interpret==0.7.4 -q

!pip install mapie==0.6.0 -q
!pip install puncc==0.8.0 -q
!pip install skorch==1.3.1 -q
!pip install properscoring==0.1 -q

!pip install dask[dataframe]==2025.12.0 -q
!pip install cython==3.0.12 -q
!pip install seaborn==0.13.2 -q
!pip install plotly==5.24.1 -q
!pip install kaleido==1.2.0 -q
!pip install openpyxl==3.1.5 -q
!pip install XlsxWriter==3.2.9 -q
!pip install cp==2020.12.3 -q

!pip install numpy==1.26.4 --force-reinstall --no-deps -q

os._exit(0)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 91.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
segregation 2.5.3 requires scikit-learn>=0.21.3, which is not installed.
segregation 2.5.3 requires seaborn, which is not installed.
mapclassify 2.10.0 requires scikit-learn>=1.4, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not installed.
libpysal 4.14.1 requires scikit-learn>=1.4.0, which is not installed.
accelerate 1.12.0 requires torch>=2.0.0, which is not installed.
spreg 1.8.5 requires scikit-learn>=0.22, which is not installed.
peft 0.18.1 requires torch>=1.13.0, which is not installed.
pysal 25.7 requires scikit-learn>=1.1, which is not installed.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, which is not installed.
cuml-cu12 26.2.0 requires scikit-learn>=1.5, which is not installed.
umap-learn 0.5.11 requires scikit-learn>=1.6, which is not installed.
giddy 2.3.8 requires seaborn, which is not installed.
sentence-transformers 5.2.3 requires scikit-learn, which is not installed.
sentence-transformers 5.2.3 requires torch>=1.11.0, which is not installed.
keras-hub 0.21.1 requires tensorflow-text; platform_system != "Windows", which is not installed.
missingno 0.5.2 requires seaborn, which is not installed.
yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.
hdbscan 0.8.41 requires scikit-learn>=1.6, which is not installed.
geemap 0.35.3 requires plotly, which is not installed.
spopt 0.7.0 requires scikit-learn>=1.4.0, which is not installed.
esda 2.8.1 requires scikit-learn>=1.4, which is not installed.
cufflinks 0.17.3 requires plotly>=4.1.1, which is not installed.
tsfresh 0.21.1 requires scikit-learn>=0.22.0, which is not installed.
imbalanced-learn 0.14.1 requires scikit-learn<2,>=1.4.2, which is not installed.
sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow>=2.2.0, which is not installed.
dopamine-rl 4.1.2 requires tensorflow-probability>=0.13.0, which is not installed.
dopamine-rl 4.1.2 requires tf-keras>=2.18.0, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
fastai 2.8.7 requires scikit-learn, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 89.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
segregation 2.5.3 requires seaborn, which is not installed.
giddy 2.3.8 requires seaborn, which is not installed.
sentence-transformers 5.2.3 requires torch>=1.11.0, which is not installed.
splot 1.1.7 requires seaborn>=0.11.0, which is not installed.
fastai 2.8.7 requires torch<3,>=1.10, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 6.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
timm 1.0.25 requires torchvision, which is not installed.
fastai 2.8.7 requires torchvision>=0.11, which is not installed.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 43.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 MB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 128.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 57.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.9/413.9 kB 39.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 14.0 MB/s eta 0:00:00
  Building wheel for autograd-gamma (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 25.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.7/180.7 kB 14.4 MB/s eta 0:00:00
  Building wheel for pgbm (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.7/432.7 kB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 61.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 24.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for shap (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 9.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for lime (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 51.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 84.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 65.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 63.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 778.9/778.9 kB 55.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 87.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 26.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.9/264.9 kB 27.9 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.5/268.5 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 29.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rapids-dask-dependency 26.2.0 requires dask==2026.1.1, but you have dask 2025.12.0 which is incompatible.
distributed 2026.1.1 requires dask<2026.1.2,>=2026.1.1, but you have dask 2025.12.0 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 30.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 61.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 7.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for cp (setup.py) ... done

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
import ngboost
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from optuna.samplers import BaseSampler
from optuna.samplers import GridSampler
from optuna.samplers import TPESampler
from optuna.samplers import PartialFixedSampler
from optuna.samplers import CmaEsSampler
from optuna.samplers import QMCSampler
from optuna.samplers import NSGAIIISampler
from optuna.samplers import NSGAIISampler
from optuna.samplers import BruteForceSampler
from optuna.samplers import GPSampler
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from openpyxl.drawing.image import Image
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from openpyxl.utils.dataframe import dataframe_to_rows
from scipy.stats import genpareto
from pytorch_tabnet import TabNetRegressor
import torch.nn as nn
import warnings
import io
import time
import numpy as np
import pandas as pd
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from openpyxl import load_workbook
from openpyxl.drawing.image import Image
from openpyxl.utils.dataframe import dataframe_to_rows

In [2]:
# Go to find & replace button and replace (pile_load_gendy_data) with your folder name. Rename your train and test dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (Settlementent) with actual data label name.

In [3]:
feature_names = ['D','L','N30_Ava','Cu_Ava','N30_Base','Cu_Base','UL','Q']

In [4]:
train_data_path = "./drive/MyDrive/pile_load_gendy_data/Data/train.csv"
test_data_path = "./drive/MyDrive/pile_load_gendy_data/Data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (371, 9)
First 5 rows of training data:
      D     L    N30_Ava      Cu_Ava  N30_Base  Cu_Base  UL       Q      S_exp
0  1.0  43.5   3.317241  105.408046        50      0.0   1     0.00   0.000000
1  0.8  24.0   8.875000   17.708333         0     50.0   1   675.00   0.691250
2  0.8  24.0   5.032258   20.000000         0     40.0   1  1012.50   0.870417
3  1.2  70.0  18.214286   14.142857        50      0.0   2  7485.15  19.161300
4  1.0  34.0   6.741176   89.117647        50      0.0   2  3007.59   6.552300

Shape of test data: (186, 9)
First 5 rows of test data:
      D     L    N30_Ava     Cu_Ava  N30_Base  Cu_Base  UL        Q     S_exp
0  0.8  24.0   8.875000  17.708333         0     50.0   2  1687.500  3.295000
1  1.0  38.0  26.631579  49.539474        50      0.0   2  2250.000  4.595960
2  0.8  24.0   5.032258  20.000000         0     40.0   1  1687.500  1.721250
3  1.0  35.5  28.400000  36.676056        50      0.0   1   741.259  0.441964
4  1.2  57.0  10.015789  55.842105        50      0.0   1     0.000  0.000000

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (371, 8)
Shape of y_train: (371,)
Shape of X_test: (186, 8)
Shape of y_test: (186,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[ 0.11501862  0.7026739  -1.39285389  2.03926221  0.47278688 -0.36847246
  -0.88040878 -0.93211799]
 [-1.33640677 -0.87840793 -0.78031847 -0.77862641 -1.76108898  0.85111254
  -0.88040878 -0.72895693]
 [-1.33640677 -0.87840793 -1.2038373  -0.70499262 -1.76108898  0.60719554
  -0.88040878 -0.6273764 ]
 [ 1.566444    2.85132356  0.24898912 -0.89318909  0.47278688 -0.36847246
   1.13583602  1.32075756]
 [ 0.11501862 -0.06759674 -1.0154929   1.5158337   0.47278688 -0.36847246
   1.13583602 -0.02689552]]

First five rows of normalized X_test:
[[-1.33640677 -0.87840793 -0.78031847 -0.77862641 -1.76108898  0.85111254
   1.13583602 -0.42421534]
 [ 0.11501862  0.25672774  1.1766814   0.2441433   0.47278688 -0.36847246
   1.13583602 -0.25491446]
 [-1.33640677 -0.87840793 -1.2038373  -0.70499262 -1.76108898  0.60719554
  -0.88040878 -0.42421534]
 [ 0.11501862  0.05402494  1.37158379 -0.16917252  0.47278688 -0.36847246
  -0.88040878 -0.70901434]
 [ 1.566444    1.79726901 -0.65458908  0.44665379  0.47278688 -0.36847246
  -0.88040878 -0.93211799]]

# **Functions:**

In [8]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'TabNet' : 'TabNet',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [9]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test.to_numpy()[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test.to_numpy()[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.to_numpy().ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]
    cum_weights = np.cumsum(weights)
    cum_weights = cum_weights / cum_weights[-1]
    return np.interp(q, cum_weights, values)

In [10]:
def conformal_predictions_NEXCP(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    strategies_names = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # =========================================================
    # NexCP – Split
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    res = np.abs(y_train.to_numpy() - yhat_train)
    weights = decay ** np.arange(len(res) - 1, -1, -1)
    q = weighted_quantile(res, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_test
    int_pred["NexCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Full
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train.to_numpy() - yhat_train), 1 - alpha)

    y_pred["NexCP-Full"] = yhat_test
    int_pred["NexCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Jackknife+ after Bootstrap
    # =========================================================
    rng = np.random.default_rng(SEED)
    lowers_t, uppers_t, preds_t = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train.iloc[idx])

        yte = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train.iloc[idx].to_numpy() - model.predict(X_train[idx])),
            1 - alpha,
        )

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-J+aB"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers_t, axis=0), np.max(uppers_t, axis=0)]

    # =========================================================
    # NexCP – CV+
    # =========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers_t, uppers_t, preds_t = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train.iloc[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train.iloc[cal].to_numpy() - y_cal), 1 - alpha)

        yte = model.predict(X_test)

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-CV+"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers_t, axis=0), np.mean(uppers_t, axis=0)]

    # =========================================================
    # Metrics
    # =========================================================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    y_true = y_test.to_numpy()

    summary_rows = []

    print("\n===== NEXCP RESULTS =====")

    for s in strategies_names:
        cov = coverage(y_true, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_true, alpha)

        summary_rows.append([
            strategies_names[s],
            cov,
            wid,
            rmse,
            cwc_val,
        ])

        print(f"{strategies_names[s]} - Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary_rows,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    idx = np.arange(len(y_test))
    plot_buffers = {}

    for s in strategies_names:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_test, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(
            idx,
            int_pred[s][:, 0],
            int_pred[s][:, 1],
            color="gray",
            alpha=0.5,
            label="Prediction interval",
        )
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(strategies_names[s])
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("Settlement")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # Excel Export
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary sheet ----
        sheet_name = "NEXCP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name, 0)
        for r_idx, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)

            sheet_name = f"NEXCP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        results_dict = {}
        for s in strategies_names:
            results_dict[f"{s}_true"] = y_true
            results_dict[f"{s}_pred"] = y_pred[s]
            results_dict[f"{s}_lower"] = int_pred[s][:, 0]
            results_dict[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(results_dict)

        sheet_name = "NEXCP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r_idx, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        wb.save(excel_file_path)

    return summary_df

In [11]:
def conformal_predictions_online_super(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    STRATEGY_NAMES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    ALL_STRATEGIES = list(STRATEGY_NAMES.keys())
    if strategies == "all":
        strategies = ALL_STRATEGIES

    # =========================================================
    # Base model
    # =========================================================
    base_model = model_class(**model_params)
    base_model.fit(X_train, y_train)

    yhat_train = base_model.predict(X_train)

    X_all = np.vstack([X_train, X_test])
    y_all = np.concatenate([y_train.to_numpy(), y_test.to_numpy()])

    n_train = len(X_train)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train
    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # =========================================================
    # Online methods (UNCHANGED LOGIC)
    # =========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_hat_all[n_train:] - q,
                                         y_hat_all[n_train:] + q]

    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(X_train[idx], y_train.iloc[idx])
            res = np.abs(y_train.iloc[idx] - m.predict(X_train[idx]))
            q = np.quantile(res, 1 - alpha)
            p = m.predict(X_test)
            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)
        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, t // 2), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            grad = alpha - (r_t <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_hat_all[n_train:] - q,
                                       y_hat_all[n_train:] + q]

    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            preds.append(yhat)
            res = np.abs(y_all[:t] - m.predict(X_all[:t]))
            q = np.quantile(res, 1 - alpha)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # =========================================================
    # METRICS
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rows = []
    for s in y_pred:
        ymin, ymax = int_pred[s].T
        cov = np.mean((y_true >= ymin) & (y_true <= ymax))
        wid = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc = wid * (1 + (cov < (1 - alpha)) * (1 - cov))

        rows.append([STRATEGY_NAMES[s], cov, wid, rmse, cwc])

    summary_df = pd.DataFrame(
        rows, columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"]
    )

    print("\n===== ONLINE CP RESULTS =====")
    print(summary_df)

    # =========================================================
    # PLOTTING (SAVE ONLY)
    # =========================================================
    plot_buffers = {}
    idx = np.arange(len(y_test))

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_true, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(idx,
                        int_pred[s][:, 0],
                        int_pred[s][:, 1],
                        color="gray",
                        alpha=0.5,
                        label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(f"{STRATEGY_NAMES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("Settlement")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # EXCEL EXPORT (APPEND SAFE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "ONLINECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        values = {}
        for s in y_pred:
            values[f"{s}_true"] = y_true
            values[f"{s}_pred"] = y_pred[s]
            values[f"{s}_lower"] = int_pred[s][:, 0]
            values[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(values)

        sheet_name = "ONLINECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

In [12]:
def conformal_predictions_COP(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,          # Learning rate for COP
    T_burnin=50,      # Window size for distribution estimation
    scale=0.5,        # Scale factor for the integrator
    random_state=123,
):
    """
    Conformal Optimistic Prediction (COP)
    ✔ Implements the Distribution-Informed Gradient logic from the repository.
    ✔ Matches the "Excel-safe" and plotting structure of your previous functions.
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # 1. Train Base Model & Generate Test Predictions
    # =========================================================
    # COP is an online calibration method, but we usually start with a pre-trained model
    # or an online model. Here we fit on Train and calibrate on Test stream.
    model = model_class(**model_params)
    model.fit(X_train, y_train)

    # Predict on test set
    y_pred_test = model.predict(X_test).ravel()
    y_true_test = y_test.to_numpy().ravel()

    # Calculate non-conformity scores (Absolute Residuals)
    # This assumes symmetric intervals.
    scores = np.abs(y_true_test - y_pred_test)
    T_test = len(scores)

    # =========================================================
    # 2. COP Initialization
    # =========================================================
    # Initialize quantiles based on training data residuals if possible
    y_pred_train = model.predict(X_train).ravel()
    scores_train = np.abs(y_train.to_numpy().ravel() - y_pred_train)
    init_q = np.quantile(scores_train, 1 - alpha)

    # Arrays to store history
    qs = np.zeros(T_test)          # Final adaptive quantile
    qts = np.zeros(T_test)         # Base quantile term
    integrators = np.zeros(T_test) # Optimistic integrator term
    covereds = np.zeros(T_test)    # Coverage boolean

    # Set initial values
    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # 3. Online COP Loop
    # =========================================================
    # Logic adapted from `core/methods.py` function `COP`

    for t in range(T_test - 1):
        # 1. Observe coverage at current step t
        covereds[t] = 1 if qs[t] >= scores[t] else 0

        # 2. Calculate Standard Gradient
        # If covered, we decrease q (grad is positive). If not, increase q.
        grad = alpha if covereds[t] else -(1 - alpha)

        # 3. Calculate Distribution-Informed Gradient (The "Optimistic" part)
        if t < T_burnin:
            grad_i = 0
        else:
            # Look at the window of recent scores
            window_s = scores[t - T_burnin : t]

            # Calculate ECDF at the predicted next quantile step
            # logic: np.mean(window_s <= qts[t] - lr * grad) - (1 - alpha)
            current_target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= current_target) - (1 - alpha)

        # 4. Update Terms
        integrator = -scale * grad_i

        # Update base quantile (Gradient Descent)
        qts[t + 1] = qts[t] - lr * grad

        # Update integrator state
        integrators[t + 1] = lr * integrator

        # Combine for final quantile
        qs[t + 1] = qts[t + 1] + integrators[t + 1]

        # Safety: Ensure quantile implies non-negative width
        qs[t + 1] = max(0, qs[t + 1])

    # Handle the final step coverage for metrics
    covereds[-1] = 1 if qs[-1] >= scores[-1] else 0

    # =========================================================
    # 4. Construct Prediction Intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # 5. Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== CONFORMAL OPTIMISTIC PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Avg Width: {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # 6. Summary Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true": y_true_test,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score_residual": scores,
        "adaptive_q": qs
    })

    # =========================================================
    # 7. Plotting
    # =========================================================
    idx = np.arange(len(y_true_test))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")

    ax.set_title(f"Conformal Optimistic Prediction (COP) - {model_name}")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("Settlement")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # 8. Excel Export
    # =========================================================
    if excel_file_path:
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            # Create a new workbook if it doesn't exist
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active) # Remove default sheet

        # ---- Summary ----
        sheet_name = "COP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

In [13]:
def conformal_predictions_EXTREME(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):
    """
    Extreme Conformal Prediction (upper-tail, single-sided)
    ✔ Same structure as NexCP & OnlineCP
    ✔ No return values
    ✔ Excel-safe
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Train / calibration split
    # =========================================================
    X_fit, X_calib, y_fit, y_calib = train_test_split(
        X_train,
        y_train,
        test_size=calib_size,
        random_state=random_state,
        shuffle=True,
    )

    # =========================================================
    # Train model
    # =========================================================
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(X_test).ravel()
    y_pred_calib = model.predict(X_calib).ravel()

    # =========================================================
    # Nonconformity scores (upper tail only)
    # =========================================================
    scores = y_calib.to_numpy().ravel() - y_pred_calib
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few calibration exceedances for GPD fitting.")

    # =========================================================
    # Peaks-over-threshold
    # =========================================================
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # =========================================================
    # Bootstrap GPD extreme quantile
    # =========================================================
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        resampled = np.random.choice(excesses, size=n_exc, replace=True)
        xi_b, _, sigma_b = genpareto.fit(resampled, floc=0)

        q_b = (
            u
            + (sigma_b / xi_b)
            * ((n_scores / (n_scores * alpha)) ** xi_b - 1)
        )
        boot_q.append(q_b)

    q_extreme = np.quantile(boot_q, 0.95)

    # =========================================================
    # Finite prediction intervals (for plotting & width)
    # =========================================================
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # =========================================================
    # Metrics
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rmse = np.sqrt(mean_squared_error(y_true, y_pred_test))
    coverage = np.mean(y_true <= ymax)
    width = q_extreme  # meaningful one-sided width

    print(f"\n===== EXTREME CONFORMAL PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"q_extreme: {q_extreme:.3f}")
    print(f"u        : {u:.3f}")
    print(f"#Exceed. : {len(scores)}")

    # =========================================================
    # Summary table
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # =========================================================
    # Values table
    # =========================================================
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true)),
        "y_true": y_true,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (y_true <= ymax).astype(int),
        "residual": y_true - y_pred_test,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(y_true))

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.scatter(idx, y_true, s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme Conformal Prediction ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("Settlement")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe, SAME FILE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "EXTREMECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

In [14]:


try:
    from tqdm.auto import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False
    print("[Info] Install tqdm for progress bars: pip install tqdm")


# ═══════════════════════════════════════════════════════════
# AlphaNet Architecture  (FIXED)
# ═══════════════════════════════════════════════════════════
class AlphaNet(nn.Module):
    """
    Maps a feature vector (sum of LOO scores) → learned α̃.
    Output is clamped to (alpha_min, 1) so that the conformal
    denominator α̃·(n+1)−1 is always positive.
    """

    def __init__(self, input_dim, alpha_min=0.05):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 32)
        self.fc2 = nn.Linear(32, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
        self.alpha_min = alpha_min  # lower bound for valid α̃
        self._initialize_near_one()

    def _initialize_near_one(self):
        """Bias output toward α̃ ≈ 1 at init (sigmoid(5) ≈ 0.993)."""
        with torch.no_grad():
            self.fc2.weight.data.normal_(0, 0.01)
            self.fc2.bias.data.fill_(5.0)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        raw = self.sigmoid(self.fc2(x)).squeeze(-1)
        # Remap from (0,1) → (alpha_min, 1) so denominator stays positive
        return self.alpha_min + (1.0 - self.alpha_min) * raw


def _interval_size(scores, alpha, eps=1e-8):
    """
    Conformal interval width = 2 * Σscores / (α̃·(n+1) − 1).
    Denominator is clamped to be strictly positive.
    """
    n = len(scores)
    denom = alpha * (n + 1) - 1
    denom = torch.clamp(denom, min=eps)   # ← KEY FIX: prevent negative/zero
    r = scores.sum() / denom
    return 2 * r


def _fmt_time(seconds):
    """Format seconds into human-readable string."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    elif seconds < 3600:
        return f"{seconds/60:.1f}min"
    else:
        return f"{seconds/3600:.1f}hr"


# ═══════════════════════════════════════════════════════════
# Main function  (CORRECTED + PROGRESS TRACKING)
# ═══════════════════════════════════════════════════════════
def conformal_predictions_AlphaNet(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet.
    - FIXED: α̃ clamped to valid range (no negative intervals)
    - FIXED: LOO scores precomputed (massive speedup)
    - ADDED: tqdm progress bars + ETA estimates
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # --- numpy-ify if pandas ---
    y_train_np = y_train.to_numpy().ravel() if hasattr(y_train, "to_numpy") else np.asarray(y_train).ravel()
    y_test_np  = y_test.to_numpy().ravel()  if hasattr(y_test,  "to_numpy") else np.asarray(y_test).ravel()
    X_train_np = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    X_test_np  = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)

    # =================================================================
    # 1.  Split training data → fit + calibration
    # =================================================================
    n_total = len(X_train_np)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = X_train_np[fit_idx],   y_train_np[fit_idx]
    X_calib, y_calib = X_train_np[calib_idx],  y_train_np[calib_idx]
    n_calib = len(X_calib)

    # Compute alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01   # small margin above threshold
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =================================================================
    # 2.  Train base regression model
    # =================================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =================================================================
    # 3.  PRECOMPUTE all LOO scores  (KEY SPEEDUP)
    # =================================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(base_model.predict(loo_X).ravel() - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =================================================================
    # 4.  Train AlphaNet (multiple runs, keep best)
    # =================================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net   = None
    best_loss  = np.inf
    history    = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores instead of calling predict()
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =================================================================
    # 5.  Compute conformal intervals on the TEST set
    # =================================================================
    print(f"  [Step 5/9] Computing conformal intervals on test set...")

    scores_calib = np.abs(base_model.predict(X_calib).ravel() - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(X_test_np).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =================================================================
    # 6.  Metrics
    # =================================================================
    y_true_test = y_test_np
    is_covered  = ((y_true_test >= ymin) & (y_true_test <= ymax)).astype(int)
    coverage    = is_covered.mean()
    avg_width   = np.mean(ymax - ymin)
    rmse        = np.sqrt(mean_squared_error(y_true_test, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =================================================================
    # 7.  Summary & values DataFrames
    # =================================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true":       y_true_test,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =================================================================
    # 8.  Plotting (SAVE ONLY — NO SHOW)
    # =================================================================
    print(f"  [Step 8/9] Generating plots...")
    idx = np.arange(len(y_true_test))

    # --- PI plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal – {model_name}")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("Settlement")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training curves ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =================================================================
    # 9.  Excel Export
    # =================================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_Summary")
        ws = wb.create_sheet(sn, 0)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        sn = _unique_sheet(wb, "AlphaNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_pi), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_tc), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet Conformal complete in {_fmt_time(total_time)}")
    return summary_df

# **Tuned Parameters**

In [15]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 152.98063120551464,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 152.98063120551464,
  'test_rmse': np.float64(12.368533914959956),
  'test_corr_coef': np.float64(0.9100717040625368),
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 170.63124260879067,
  'best_params': {'n_estimators': 100,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 170.63124260879067,
  'test_rmse': np.float64(13.062589429695425),
  'test_corr_coef': np.float64(0.8943907434686084),
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 180.04588999142493,
  'best_params': {'n_estimators': 100,
   'criterion': 'poisson',
   'max_depth': 10,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 180.04588999142493,
  'test_rmse': np.float64(13.418117975015159),
  'test_corr_coef': np.float64(0.8893904103704389),
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 154.16247953238616,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 154.16247953238616,
  'test_rmse': np.float64(12.416218407082978),
  'test_corr_coef': np.float64(0.9098826634121733),
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 152.46010559118824, 'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.3,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05}, 'test_mse': 152.46010559118824, 'test_rmse': np.float64(12.347473652176312), 'test_corr_coef': np.float64(0.9101947022096951), 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 163.0289258942997,
  'best_params': {'n_estimators': 500,
   'criterion': 'poisson',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 163.0289258942997,
  'test_rmse': np.float64(12.768278109999786),
  'test_corr_coef': np.float64(0.9002897960107232),
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 154.64840720467092,
  'best_params': {'n_estimators': 200,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.3,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 154.64840720467092,
  'test_rmse': np.float64(12.435771275022347),
  'test_corr_coef': np.float64(0.9065053984224763),
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 158.28207318969893,
  'best_params': {'n_estimators': 700,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.3,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 158.28207318969893,
  'test_rmse': np.float64(12.581020355666663),
  'test_corr_coef': np.float64(0.9052738863008764),
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 106.82199342946828,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 106.82199342946828,
  'test_rmse': np.float64(10.335472578913278),
  'test_corr_coef': np.float64(0.9310344147012503),
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 111.15668952779254,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 2,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 111.15668952779254,
  'test_rmse': np.float64(10.543087286359368),
  'test_corr_coef': np.float64(0.9270426649914485),
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 89.02816733158211,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 89.02816733158211,
  'test_rmse': np.float64(9.435473879545325),
  'test_corr_coef': np.float64(0.9456205230324285),
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 100.66262991393918,
  'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 100.66262991393918,
  'test_rmse': np.float64(10.033076791988547),
  'test_corr_coef': np.float64(0.9342492651003499),
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 120.46198397430994, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 100,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.001}, 'test_mse': 120.46198397430994, 'test_rmse': np.float64(10.975517480935007), 'test_corr_coef': np.float64(0.923499908135557), 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 109.53579015309792,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.01},
  'test_mse': 109.53579015309792,
  'test_rmse': np.float64(10.46593474817696),
  'test_corr_coef': np.float64(0.9327627929002421),
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 107.86816836778692,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 107.86816836778692,
  'test_rmse': np.float64(10.385960156277653),
  'test_corr_coef': np.float64(0.9277543666060549),
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 115.63069596852776,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 200,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 115.63069596852776,
  'test_rmse': np.float64(10.753171437698171),
  'test_corr_coef': np.float64(0.9255816102420358),
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 100.58914887067544,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 100.58914887067544,
  'test_rmse': np.float64(10.029414183823272),
  'test_corr_coef': np.float64(0.9359533194853996),
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 89.61367880089917,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.5,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 89.61367880089917,
  'test_rmse': np.float64(9.466450168933399),
  'test_corr_coef': np.float64(0.9431313973448553),
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 98.49578970490964,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 98.49578970490964,
  'test_rmse': np.float64(9.924504506770583),
  'test_corr_coef': np.float64(0.9365472186074788),
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 67.93676050134304,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 67.93676050134304,
  'test_rmse': np.float64(8.242375901482717),
  'test_corr_coef': np.float64(0.9561296172273666),
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 99.3361140760957,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 99.3361140760957,
  'test_rmse': np.float64(9.966750427099884),
  'test_corr_coef': np.float64(0.9389056880557962),
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 86.68867330070917,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 86.68867330070917,
  'test_rmse': np.float64(9.310675233338834),
  'test_corr_coef': np.float64(0.9488970717669976),
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 92.02039272806104,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 92.02039272806104,
  'test_rmse': np.float64(9.592726032159005),
  'test_corr_coef': np.float64(0.9432169166482989),
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 93.85385734548784,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 93.85385734548784,
  'test_rmse': np.float64(9.687820051254453),
  'test_corr_coef': np.float64(0.9417304624183378),
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 95.44911836418507,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 95.44911836418507,
  'test_rmse': np.float64(9.769806465032206),
  'test_corr_coef': np.float64(0.93682381557629),
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 78.38037008965738,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 78.38037008965738,
  'test_rmse': np.float64(8.85326889288117),
  'test_corr_coef': np.float64(0.9541227486219568),
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 100.44210495654774,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 100.44210495654774,
  'test_rmse': np.float64(10.0220808695873),
  'test_corr_coef': np.float64(0.933242701768733),
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 101.63336303111387,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'min_child_weight': 0.01,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 101.63336303111387,
  'test_rmse': np.float64(10.081337363222891),
  'test_corr_coef': np.float64(0.9322923768116579),
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 97.56376537904843,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 1.0,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 97.56376537904843,
  'test_rmse': np.float64(9.877437186793365),
  'test_corr_coef': np.float64(0.9334568585552251),
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 108.72600408852692,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 108.72600408852692,
  'test_rmse': np.float64(10.427176227940473),
  'test_corr_coef': np.float64(0.926544507181797),
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 100.48601146382701,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 0,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 100.48601146382701,
  'test_rmse': np.float64(10.024271118830885),
  'test_corr_coef': np.float64(0.9336433334531059),
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 88.65248921998764,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 88.65248921998764,
  'test_rmse': np.float64(9.41554508353009),
  'test_corr_coef': np.float64(0.9452888449153922),
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 98.89133129858779,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.9,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 98.89133129858779,
  'test_rmse': np.float64(9.944412063997941),
  'test_corr_coef': np.float64(0.933729392135044),
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 101.36751534760184,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 1.0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 101.36751534760184,
  'test_rmse': np.float64(10.068143589937613),
  'test_corr_coef': np.float64(0.9311295278444216),
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 95.51459146564854,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.9,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 1.0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 95.51459146564854,
  'test_rmse': np.float64(9.773156678660612),
  'test_corr_coef': np.float64(0.935810950039782),
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 95.02584170675935,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.5,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 95.02584170675935,
  'test_rmse': np.float64(9.748119906256763),
  'test_corr_coef': np.float64(0.9367257738852067),
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 103.04660969928004,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.5,
   'reg_lambda': 1.0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 103.04660969928004,
  'test_rmse': np.float64(10.151187600437696),
  'test_corr_coef': np.float64(0.9294310296392595),
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 93.31598269527979,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': -1,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 93.31598269527979,
  'test_rmse': np.float64(9.660019808223987),
  'test_corr_coef': np.float64(0.9374326288527489),
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 96.29461706369923,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'max_depth': 7,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 96.29461706369923,
  'test_rmse': np.float64(9.812982067837444),
  'test_corr_coef': np.float64(0.934807468291228),
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 102.18009827730634,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': -1,
   'num_leaves': 31,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 102.18009827730634,
  'test_rmse': np.float64(10.108417199408933),
  'test_corr_coef': np.float64(0.9314026791262863),
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 85.48272460888411,
  'best_params': {'iterations': 500,
   'learning_rate': 0.1,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 85.48272460888411,
  'test_rmse': np.float64(9.245686811096519),
  'test_corr_coef': np.float64(0.9445059932077939),
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 93.36712377305112,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 6,
   'l2_leaf_reg': 3,
   'border_count': 128,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 93.36712377305112,
  'test_rmse': np.float64(9.662666493936916),
  'test_corr_coef': np.float64(0.9413875272554717),
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 89.50072499631383,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 128,
   'min_data_in_leaf': 10,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 89.50072499631383,
  'test_rmse': np.float64(9.46048228138047),
  'test_corr_coef': np.float64(0.9462768805177888),
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 88.95178129138309,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 128,
   'min_data_in_leaf': 1,
   'rsm': 0.8,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 88.95178129138309,
  'test_rmse': np.float64(9.431425199373798),
  'test_corr_coef': np.float64(0.945133421527909),
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 85.36080983400738,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 85.36080983400738,
  'test_rmse': np.float64(9.239091396560994),
  'test_corr_coef': np.float64(0.944589054411141),
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 89.78953847272699,
  'best_params': {'iterations': 500,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 128,
   'min_data_in_leaf': 20,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 89.78953847272699,
  'test_rmse': np.float64(9.475734191751423),
  'test_corr_coef': np.float64(0.9446376921418882),
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 88.95178129138309,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 128,
   'min_data_in_leaf': 1,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 88.95178129138309,
  'test_rmse': np.float64(9.431425199373798),
  'test_corr_coef': np.float64(0.945133421527909),
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 85.36080983400738,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 8,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 85.36080983400738,
  'test_rmse': np.float64(9.239091396560994),
  'test_corr_coef': np.float64(0.944589054411141),
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 153.3856053332811,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 153.3856053332811,
  'test_rmse': np.float64(12.384894239890832),
  'test_corr_coef': np.float64(0.8930112337646037),
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 143.30218176515817,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 143.30218176515817,
  'test_rmse': np.float64(11.970888929614132),
  'test_corr_coef': np.float64(0.9007498276924898),
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 157.5719110469103,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 157.5719110469103,
  'test_rmse': np.float64(12.552765075747665),
  'test_corr_coef': np.float64(0.8882779345461344),
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 159.10355471401047,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 159.10355471401047,
  'test_rmse': np.float64(12.613625756062785),
  'test_corr_coef': np.float64(0.8887176533138197),
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 151.44908811890718,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 151.44908811890718,
  'test_rmse': np.float64(12.306465297513627),
  'test_corr_coef': np.float64(0.8942223224428472),
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 145.81711936793175,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 145.81711936793175,
  'test_rmse': np.float64(12.07547594788428),
  'test_corr_coef': np.float64(0.8990006764687222),
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 152.87737506561598,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 152.87737506561598,
  'test_rmse': np.float64(12.364359064084802),
  'test_corr_coef': np.float64(0.8947260671053722),
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 155.76578578406654,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 1.0,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 155.76578578406654,
  'test_rmse': np.float64(12.480616402408439),
  'test_corr_coef': np.float64(0.8945010680208828),
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 67.56506779356722,
  'best_params': {'n_d': 32,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 2.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 67.56506779356722,
  'test_rmse': np.float64(8.21979730854522),
  'test_corr_coef': np.float64(0.9530052734492968),
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 76.08969444498896,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 76.08969444498896,
  'test_rmse': np.float64(8.722940699385097),
  'test_corr_coef': np.float64(0.9539981359400319),
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 51.715715833103495,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 3,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 51.715715833103495,
  'test_rmse': np.float64(7.191363975846549),
  'test_corr_coef': np.float64(0.9656865213398506),
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 71.63011611867866,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 71.63011611867866,
  'test_rmse': np.float64(8.463457692850993),
  'test_corr_coef': np.float64(0.9654969292739963),
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 82.00418994914077,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 3,
   'gamma': 2.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 82.00418994914077,
  'test_rmse': np.float64(9.055616486421052),
  'test_corr_coef': np.float64(0.9437403007013775),
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 61.70944877314963,
  'best_params': {'n_d': 8,
   'n_a': 16,
   'n_steps': 3,
   'gamma': 1.5,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 61.70944877314963,
  'test_rmse': np.float64(7.855536186228769),
  'test_corr_coef': np.float64(0.9585631287990138),
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 75.58697579720257,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 75.58697579720257,
  'test_rmse': np.float64(8.694077052637764),
  'test_corr_coef': np.float64(0.9758601351677328),
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 71.4337647373294,
  'best_params': {'n_d': 16,
   'n_a': 64,
   'n_steps': 5,
   'gamma': 1.3,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 71.4337647373294,
  'test_rmse': np.float64(8.451849781990296),
  'test_corr_coef': np.float64(0.9505375759724721),
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 129.3442580892259,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 300,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 129.3442580892259,
  'test_rmse': np.float64(11.372961711411232),
  'test_corr_coef': np.float64(0.9110563465189973),
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 128.84698844088038,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 300,
   'max_depth': 5,
   'min_samples_leaf': 5,
   'max_leaf_nodes': None,
   'l2_regularization': 0.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 128.84698844088038,
  'test_rmse': np.float64(11.351078734678937),
  'test_corr_coef': np.float64(0.9126867001605148),
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 118.10639347146959,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 200,
   'max_depth': None,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.1,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 118.10639347146959,
  'test_rmse': np.float64(10.867676544297295),
  'test_corr_coef': np.float64(0.9232102276248901),
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 118.33165303465466, 'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 31,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 118.33165303465466, 'test_rmse': np.float64(10.878035348106508), 'test_corr_coef': np.float64(0.9214138007846934), 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 120.04036901152315, 'best_params': {'learning_rate': 0.15,
   'max_iter': 500,
   'max_depth': 7,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 120.04036901152315, 'test_rmse': np.float64(10.956293580017064), 'test_corr_coef': np.float64(0.9202582418957181), 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting',
  'HyperbandPruner'): {'best_score': 116.79271602948637, 'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': None,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 1.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 116.79271602948637, 'test_rmse': np.float64(10.8070678738262), 'test_corr_coef': np.float64(0.9225001141872002), 'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting',
  'ThresholdPruner'): {'best_score': 114.40748198147847, 'best_params': {'learning_rate': 0.15,
   'max_iter': 500,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 114.40748198147847, 'test_rmse': np.float64(10.696143322781277), 'test_corr_coef': np.float64(0.9255663426415169), 'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 117.98955148062424,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 300,
   'max_depth': 7,
   'min_samples_leaf': 10,
   'max_leaf_nodes': None,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 117.98955148062424,
  'test_rmse': np.float64(10.8622995484669),
  'test_corr_coef': np.float64(0.9224400475682029),
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 110.06646235121923,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 59,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 110.06646235121923,
  'test_rmse': np.float64(10.491256471520426),
  'test_corr_coef': np.float64(0.9238145638885917),
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 116.36760716412837,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 54,
   'min_split_gain': 0.5,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 116.36760716412837,
  'test_rmse': np.float64(10.787381849370512),
  'test_corr_coef': np.float64(0.9212230066839205),
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 120.43814576742204,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_leaves': 19,
   'min_split_gain': 0.1,
   'reg_lambda': 1.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 120.43814576742204,
  'test_rmse': np.float64(10.97443145531567),
  'test_corr_coef': np.float64(0.9174495811585923),
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 105.28414366018494,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 15,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 64,
   'distribution': 'normal'},
  'test_mse': 105.28414366018494,
  'test_rmse': np.float64(10.260806189583006),
  'test_corr_coef': np.float64(0.9302272067031147),
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 109.29949887489617,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_leaves': 56,
   'min_split_gain': 0.5,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 109.29949887489617,
  'test_rmse': np.float64(10.454640064339669),
  'test_corr_coef': np.float64(0.9255118931278087),
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 110.77295523525386,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 34,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 110.77295523525386,
  'test_rmse': np.float64(10.52487316955667),
  'test_corr_coef': np.float64(0.9231205172720397),
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 111.64254560217586,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_leaves': 55,
   'min_split_gain': 0.1,
   'reg_lambda': 10.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 111.64254560217586,
  'test_rmse': np.float64(10.566103614964973),
  'test_corr_coef': np.float64(0.9236377603457087),
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 105.48508904482442,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 58,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 105.48508904482442,
  'test_rmse': np.float64(10.270593412496886),
  'test_corr_coef': np.float64(0.9287649006989753),
  'pruner': 'WilcoxonPruner'}}

# **Conformal Predictions with Lightgbm**

In [16]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

In [17]:
conformal_predictions_NEXCP(
    model_class=LGBMRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 23.118% | Width: 0.386
NexCP Full - Coverage: 23.118% | Width: 0.386
NexCP Jackknife+ aB - Coverage: 94.624% | Width: 22.931
NexCP CV+ - Coverage: 93.011% | Width: 42.037

              Strategy  Coverage      Width       RMSE           CWC
0          NexCP Split  0.231183   0.385739   8.853269  1.567511e+15
1           NexCP Full  0.231183   0.385665   8.853269  1.567213e+15
2  NexCP Jackknife+ aB  0.946237  22.931152  12.293603  5.061000e+01
3            NexCP CV+  0.930108  42.036669  11.811693  1.556915e+02

In [18]:
conformal_predictions_online_super(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.231183   0.385665   8.853269   0.682172
1            Online CV+  0.693548   5.954654   8.853269   7.779468
2  Online Jackknife+ aB  0.951613  23.403141  12.113075  23.403141
3                 SAOCP  0.801075  13.861522   8.853269  16.618922
4                SF-OGD  0.924731  29.102664   8.853269  31.293187
5                  FACI  0.908602  30.427837   8.853269  33.208876
6            MFCS Split  0.231183   0.385665   8.853269   0.682172
7             MFCS Full  0.161290   0.233418   7.833168   0.429188

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.231183   0.385665   8.853269   0.682172
1            Online CV+  0.693548   5.954654   8.853269   7.779468
2  Online Jackknife+ aB  0.951613  23.403141  12.113075  23.403141
3                 SAOCP  0.801075  13.861522   8.853269  16.618922
4                SF-OGD  0.924731  29.102664   8.853269  31.293187
5                  FACI  0.908602  30.427837   8.853269  33.208876
6            MFCS Split  0.231183   0.385665   8.853269   0.682172
7             MFCS Full  0.161290   0.233418   7.833168   0.429188

In [19]:
conformal_predictions_COP(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (LightGBM) =====
Coverage : 66.129%
Avg Width: 3.509
RMSE     : 8.853
Final q  : 2.886

  Strategy  Coverage     Width      RMSE  Alpha    LR  Scale
0      COP   0.66129  3.508614  8.853269   0.05  0.05    0.5

In [20]:
conformal_predictions_EXTREME(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (LightGBM) =====
Coverage : 98.925%
Width    : 59.670
RMSE     : 12.743
q_extreme: 59.670
u        : 40.272
#Exceed. : 59

In [21]:
conformal_predictions_AlphaNet(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=186 | alpha_min=0.0153
  [Step 2/9] Training base LightGBM model...
  [Step 2/9] Done in 1s
  [Step 3/9] Precomputing 186 LOO score vectors...

    LOO precompute:   0%|          | 0/186 [00:00<?, ?it/s]

  [Step 3/9] Done in 2s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 49.2832 | Size: 32.4900 | α̃: 0.8397 | ⏱ 0.76s/epoch | ETA: 15.4min
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 29.7412 | Size: 9.7412 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1.5min
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 29.7403 | Size: 9.7403 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 50s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 29.7402 | Size: 9.7402 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 36s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 29.7420 | Size: 9.7420 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 28s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 29.7418 | Size: 9.7418 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 23s
  ✓ Run 1 complete | Final loss: 29.7418

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 36.9086 | Size: 20.4869 | α̃: 0.8211 | ⏱ 0.07s/epoch | ETA: 23s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 29.7416 | Size: 9.7416 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 19s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 29.7406 | Size: 9.7406 | α̃: 1.0000 | ⏱ 0.09s/epoch | ETA: 17s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 29.7410 | Size: 9.7410 | α̃: 1.0000 | ⏱ 0.10s/epoch | ETA: 15s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 29.7414 | Size: 9.7414 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 13s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 29.7418 | Size: 9.7418 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 12s
  ✓ Run 2 complete | Final loss: 29.7418

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 29.7413 | Size: 9.7413 | α̃: 1.0000 | ⏱ 0.12s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 29.7413 | Size: 9.7413 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 10s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 29.7420 | Size: 9.7420 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 9s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 29.7414 | Size: 9.7414 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 7s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 29.7422 | Size: 9.7422 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 29.7410 | Size: 9.7410 | α̃: 1.0000 | ⏱ 0.15s/epoch | ETA: 5s
  ✓ Run 3 complete | Final loss: 29.7410

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 59.4141 | Size: 44.8250 | α̃: 0.7295 | ⏱ 0.11s/epoch | ETA: 5s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 29.7414 | Size: 9.7414 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 29.7399 | Size: 9.7399 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 29.7408 | Size: 9.7408 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 29.7414 | Size: 9.7414 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 29.7408 | Size: 9.7408 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 29.7408
  [Step 4/9] Training done in 20s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (LightGBM)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 4.8706
  Coverage       : 73.118%
  Avg Width      : 9.7411
  RMSE           : 16.9320
  Total time     : 22s
    ├─ Precompute: 2s
    └─ Training  : 20s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 22s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.731183,9.741102,16.932035,0.05,1.0,20.0,22.47

# **Conformal Predictions with XGBoost**

In [22]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

In [23]:
conformal_predictions_NEXCP(
    model_class=XGBRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 0.538% | Width: 0.013
NexCP Full - Coverage: 0.538% | Width: 0.013
NexCP Jackknife+ aB - Coverage: 95.699% | Width: 22.046
NexCP CV+ - Coverage: 93.548% | Width: 37.366

              Strategy  Coverage      Width       RMSE           CWC
0          NexCP Split  0.005376   0.012818   8.242376  4.169242e+18
1           NexCP Full  0.005376   0.012701   8.242376  4.131191e+18
2  NexCP Jackknife+ aB  0.956989  22.045578  11.653504  2.204558e+01
3            NexCP CV+  0.935484  37.365810  10.216270  1.145784e+02

In [24]:
conformal_predictions_online_super(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.005376   0.012701   8.242376   0.025334
1            Online CV+  0.629032   7.153974   8.242376   9.807868
2  Online Jackknife+ aB  0.930108  20.799994  11.997641  22.253757
3                 SAOCP  0.747312  17.157830   8.242376  21.493411
4                SF-OGD  0.000000   0.000000   8.242376   0.000000
5                  FACI  0.897849  34.186452   8.242376  37.678616
6            MFCS Split  0.005376   0.012701   8.242376   0.025334
7             MFCS Full  0.021505   0.046492   9.158004   0.091983

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.005376   0.012701   8.242376   0.025334
1            Online CV+  0.629032   7.153974   8.242376   9.807868
2  Online Jackknife+ aB  0.930108  20.799994  11.997641  22.253757
3                 SAOCP  0.747312  17.157830   8.242376  21.493411
4                SF-OGD  0.000000   0.000000   8.242376   0.000000
5                  FACI  0.897849  34.186452   8.242376  37.678616
6            MFCS Split  0.005376   0.012701   8.242376   0.025334
7             MFCS Full  0.021505   0.046492   9.158004   0.091983

In [25]:
conformal_predictions_COP(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (XGBoost) =====
Coverage : 67.204%
Avg Width: 3.246
RMSE     : 8.242
Final q  : 2.598

  Strategy  Coverage     Width      RMSE  Alpha    LR  Scale
0      COP  0.672043  3.245505  8.242376   0.05  0.05    0.5

In [26]:
conformal_predictions_EXTREME(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (XGBoost) =====
Coverage : 98.925%
Width    : 47.449
RMSE     : 12.128
q_extreme: 47.449
u        : 38.381
#Exceed. : 57

In [27]:
conformal_predictions_AlphaNet(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=186 | alpha_min=0.0153
  [Step 2/9] Training base XGBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 186 LOO score vectors...

    LOO precompute:   0%|          | 0/186 [00:00<?, ?it/s]

  [Step 3/9] Done in 1s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 105.5096 | Size: 88.8950 | α̃: 0.8307 | ⏱ 0.08s/epoch | ETA: 18s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 31.5378 | Size: 11.5378 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 12s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 31.5375 | Size: 11.5375 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 12s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 31.5375 | Size: 11.5375 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 11s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 31.5391 | Size: 11.5391 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 31.5383 | Size: 11.5383 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 10s
  ✓ Run 1 complete | Final loss: 31.5383

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 64.8865 | Size: 49.1173 | α̃: 0.7885 | ⏱ 0.08s/epoch | ETA: 10s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 31.5384 | Size: 11.5384 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 9s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 31.5379 | Size: 11.5379 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 8s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 31.5384 | Size: 11.5384 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 8s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 31.5382 | Size: 11.5382 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 31.5388 | Size: 11.5388 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 6s
  ✓ Run 2 complete | Final loss: 31.5388

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 31.5388 | Size: 11.5388 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 31.5380 | Size: 11.5380 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 31.5389 | Size: 11.5389 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 5s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 31.5371 | Size: 11.5371 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 31.5385 | Size: 11.5385 | α̃: 1.0000 | ⏱ 0.09s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 31.5381 | Size: 11.5381 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 3s
  ✓ Run 3 complete | Final loss: 31.5381

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 31.5111 | Size: 12.9086 | α̃: 0.9301 | ⏱ 0.11s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 31.5390 | Size: 11.5390 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 31.5364 | Size: 11.5364 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 31.5374 | Size: 11.5374 | α̃: 1.0000 | ⏱ 0.10s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 31.5384 | Size: 11.5384 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 31.5381 | Size: 11.5381 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 31.5381
  [Step 4/9] Training done in 14s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (XGBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 5.7690
  Coverage       : 72.043%
  Avg Width      : 11.5380
  RMSE           : 17.0530
  Total time     : 15s
    ├─ Precompute: 1s
    └─ Training  : 14s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 15s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.72043,11.538002,17.053031,0.05,1.0,20.0,15.31

# **Conformal Predictions with GPBoost**

In [28]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

In [29]:
conformal_predictions_NEXCP(
    model_class=GPBoostRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 68.280% | Width: 3.208
NexCP Full - Coverage: 65.591% | Width: 2.758
NexCP Jackknife+ aB - Coverage: 92.473% | Width: 21.135
NexCP CV+ - Coverage: 91.935% | Width: 38.364

              Strategy  Coverage      Width       RMSE           CWC
0          NexCP Split  0.682796   3.208089   9.660020  2.034768e+06
1           NexCP Full  0.655914   2.758189   9.660020  6.708432e+06
2  NexCP Jackknife+ aB  0.924731  21.134546  11.850884  9.589954e+01
3            NexCP CV+  0.919355  38.364422  10.811588  2.159386e+02

In [30]:
conformal_predictions_online_super(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.655914   2.758189   9.660020   3.707243
1            Online CV+  0.779570   9.086693   9.660020  11.089674
2  Online Jackknife+ aB  0.908602  20.929450  12.088364  22.842357
3                 SAOCP  0.849462  18.945384   9.660020  21.797378
4                SF-OGD  0.903226  30.673039   9.660020  33.641398
5                  FACI  0.924731  35.339595   9.660020  37.999565
6            MFCS Split  0.655914   2.758189   9.660020   3.707243
7             MFCS Full  0.677419   2.850792   9.045731   3.770402

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.655914   2.758189   9.660020   3.707243
1            Online CV+  0.779570   9.086693   9.660020  11.089674
2  Online Jackknife+ aB  0.908602  20.929450  12.088364  22.842357
3                 SAOCP  0.849462  18.945384   9.660020  21.797378
4                SF-OGD  0.903226  30.673039   9.660020  33.641398
5                  FACI  0.924731  35.339595   9.660020  37.999565
6            MFCS Split  0.655914   2.758189   9.660020   3.707243
7             MFCS Full  0.677419   2.850792   9.045731   3.770402

In [31]:
conformal_predictions_COP(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GPBoost) =====
Coverage : 74.194%
Avg Width: 4.837
RMSE     : 9.660
Final q  : 3.321

  Strategy  Coverage     Width     RMSE  Alpha    LR  Scale
0      COP  0.741935  4.837111  9.66002   0.05  0.05    0.5

In [32]:
conformal_predictions_EXTREME(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (GPBoost) =====
Coverage : 100.000%
Width    : 62.351
RMSE     : 11.785
q_extreme: 62.351
u        : 42.156
#Exceed. : 53

In [33]:
conformal_predictions_AlphaNet(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=186 | alpha_min=0.0153
  [Step 2/9] Training base GPBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 186 LOO score vectors...

    LOO precompute:   0%|          | 0/186 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 75.7874 | Size: 59.1170 | α̃: 0.8335 | ⏱ 0.10s/epoch | ETA: 24s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 30.7688 | Size: 10.7688 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 17s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 30.7683 | Size: 10.7683 | α̃: 1.0000 | ⏱ 0.09s/epoch | ETA: 16s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 30.7691 | Size: 10.7691 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 15s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 30.7699 | Size: 10.7699 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 14s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 30.7699 | Size: 10.7699 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 13s
  ✓ Run 1 complete | Final loss: 30.7699

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 49.0084 | Size: 32.9729 | α̃: 0.8018 | ⏱ 0.08s/epoch | ETA: 13s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 30.7702 | Size: 10.7702 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 11s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 30.7688 | Size: 10.7688 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 10s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 30.7696 | Size: 10.7696 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 9s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 30.7695 | Size: 10.7695 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 8s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 30.7695 | Size: 10.7695 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 7s
  ✓ Run 2 complete | Final loss: 30.7695

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 30.7701 | Size: 10.7701 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 7s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 30.7696 | Size: 10.7696 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 7s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 30.7701 | Size: 10.7701 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 30.7689 | Size: 10.7689 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 5s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 30.7698 | Size: 10.7698 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 30.7692 | Size: 10.7692 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 4s
  ✓ Run 3 complete | Final loss: 30.7692

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 30.5558 | Size: 11.7210 | α̃: 0.9417 | ⏱ 0.07s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 30.7699 | Size: 10.7699 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 30.7674 | Size: 10.7674 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 30.7690 | Size: 10.7690 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 30.7700 | Size: 10.7700 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 30.7695 | Size: 10.7695 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 30.7695
  [Step 4/9] Training done in 14s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GPBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 5.3845
  Coverage       : 78.495%
  Avg Width      : 10.7691
  RMSE           : 17.5931
  Total time     : 14s
    ├─ Precompute: 0s
    └─ Training  : 14s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 14s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.784946,10.769097,17.593081,0.05,1.0,20.0,14.5

# **Conformal Predictions with NGBoost**

In [34]:
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

In [35]:
conformal_predictions_NEXCP(
    model_class=NGBRegressor,
    best_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 75.269% | Width: 15.068
NexCP Full - Coverage: 75.269% | Width: 13.104
NexCP Jackknife+ aB - Coverage: 93.548% | Width: 32.873
NexCP CV+ - Coverage: 89.785% | Width: 43.702

              Strategy  Coverage      Width       RMSE            CWC
0          NexCP Split  0.752688  15.068060  12.422201  290169.533922
1           NexCP Full  0.752688  13.103908  12.733025  252345.340981
2  NexCP Jackknife+ aB  0.935484  32.872523  13.983557     100.800203
3            NexCP CV+  0.897849  43.701950  13.321517     636.539013

In [36]:
conformal_predictions_online_super(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.736559  13.399147  12.422201  16.929030
1            Online CV+  0.811828  21.092250  12.422201  25.061221
2  Online Jackknife+ aB  0.930108  31.497797  14.202098  33.699255
3                 SAOCP  0.865591  34.933236  12.422201  39.628563
4                SF-OGD  0.881720  40.048322  12.422201  44.785220
5                  FACI  0.924731  51.615789  12.422201  55.500849
6            MFCS Split  0.736559  13.399147  12.422201  16.929030
7             MFCS Full  0.806452  17.766612  13.114096  21.205311

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.736559  13.399147  12.422201  16.929030
1            Online CV+  0.811828  21.092250  12.422201  25.061221
2  Online Jackknife+ aB  0.930108  31.497797  14.202098  33.699255
3                 SAOCP  0.865591  34.933236  12.422201  39.628563
4                SF-OGD  0.881720  40.048322  12.422201  44.785220
5                  FACI  0.924731  51.615789  12.422201  55.500849
6            MFCS Split  0.736559  13.399147  12.422201  16.929030
7             MFCS Full  0.806452  17.766612  13.114096  21.205311

In [37]:
conformal_predictions_COP(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (NGBoost) =====
Coverage : 76.344%
Avg Width: 15.214
RMSE     : 12.422
Final q  : 8.441

  Strategy  Coverage      Width       RMSE  Alpha    LR  Scale
0      COP  0.763441  15.213672  12.422201   0.05  0.05    0.5

In [38]:
conformal_predictions_EXTREME(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (NGBoost) =====
Coverage : 100.000%
Width    : 58.479
RMSE     : 13.122
q_extreme: 58.479
u        : 46.019
#Exceed. : 55

In [39]:
conformal_predictions_AlphaNet(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=186 | alpha_min=0.0153
  [Step 2/9] Training base NGBoost model...
  [Step 2/9] Done in 4s
  [Step 3/9] Precomputing 186 LOO score vectors...

    LOO precompute:   0%|          | 0/186 [00:00<?, ?it/s]

  [Step 3/9] Done in 38s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 222.1103 | Size: 205.6081 | α̃: 0.8251 | ⏱ 0.08s/epoch | ETA: 19s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 34.0001 | Size: 14.0001 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 12s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 33.9997 | Size: 13.9997 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 11s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 33.9999 | Size: 13.9999 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 11s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 34.0001 | Size: 14.0001 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 33.9998 | Size: 13.9998 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 9s
  ✓ Run 1 complete | Final loss: 33.9998

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 33.9993 | Size: 13.9993 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 9s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 33.9994 | Size: 13.9994 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 9s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 33.9992 | Size: 13.9992 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 8s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 34.0001 | Size: 14.0001 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 8s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 33.9999 | Size: 13.9999 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 34.0006 | Size: 14.0006 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 6s
  ✓ Run 2 complete | Final loss: 34.0006

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 34.0004 | Size: 14.0004 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 33.9998 | Size: 13.9998 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 34.0007 | Size: 14.0007 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 5s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 33.9991 | Size: 13.9991 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 34.0005 | Size: 14.0005 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 33.9998 | Size: 13.9998 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 3s
  ✓ Run 3 complete | Final loss: 33.9998

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 36.2048 | Size: 18.3909 | α̃: 0.8907 | ⏱ 0.09s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 34.0000 | Size: 14.0000 | α̃: 1.0000 | ⏱ 0.09s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 33.9977 | Size: 13.9977 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 34.0001 | Size: 14.0001 | α̃: 1.0000 | ⏱ 0.10s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 33.9999 | Size: 13.9999 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 33.9999 | Size: 13.9999 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 33.9999
  [Step 4/9] Training done in 14s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (NGBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 6.9998
  Coverage       : 70.430%
  Avg Width      : 13.9997
  RMSE           : 18.4850
  Total time     : 56s
    ├─ Precompute: 38s
    └─ Training  : 14s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 56s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.704301,13.999693,18.485018,0.05,1.0,20.0,56.01

# **Conformal Predictions with Gradient Boosting**

In [40]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

In [41]:
conformal_predictions_NEXCP(
    model_class=GradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 72.581% | Width: 4.559
NexCP Full - Coverage: 70.968% | Width: 4.077
NexCP Jackknife+ aB - Coverage: 92.473% | Width: 20.206
NexCP CV+ - Coverage: 93.011% | Width: 37.253

              Strategy  Coverage      Width       RMSE            CWC
0          NexCP Split  0.725806   4.559385   9.435474  336676.798415
1           NexCP Full  0.709677   4.077273   9.435474  674389.808670
2  NexCP Jackknife+ aB  0.924731  20.206426  12.203771      91.688130
3            NexCP CV+  0.930108  37.253438  11.130620     137.975805

In [42]:
conformal_predictions_online_super(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.709677   4.077273   9.435474   5.260998
1            Online CV+  0.790323  10.549499   9.435474  12.761491
2  Online Jackknife+ aB  0.892473  19.089322  12.210984  21.141937
3                 SAOCP  0.849462  18.844160   9.435474  21.680915
4                SF-OGD  0.924731  32.327421   9.435474  34.760668
5                  FACI  0.930108  35.618552   9.435474  38.108021
6            MFCS Split  0.709677   4.077273   9.435474   5.260998
7             MFCS Full  0.725806   4.738246   9.174672   6.037442

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.709677   4.077273   9.435474   5.260998
1            Online CV+  0.790323  10.549499   9.435474  12.761491
2  Online Jackknife+ aB  0.892473  19.089322  12.210984  21.141937
3                 SAOCP  0.849462  18.844160   9.435474  21.680915
4                SF-OGD  0.924731  32.327421   9.435474  34.760668
5                  FACI  0.930108  35.618552   9.435474  38.108021
6            MFCS Split  0.709677   4.077273   9.435474   5.260998
7             MFCS Full  0.725806   4.738246   9.174672   6.037442

In [43]:
conformal_predictions_COP(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GradientBoosting) =====
Coverage : 75.806%
Avg Width: 6.070
RMSE     : 9.435
Final q  : 3.830

  Strategy  Coverage     Width      RMSE  Alpha    LR  Scale
0      COP  0.758065  6.070405  9.435474   0.05  0.05    0.5

In [44]:
conformal_predictions_EXTREME(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (GradientBoosting) =====
Coverage : 98.925%
Width    : 41.996
RMSE     : 10.400
q_extreme: 41.996
u        : 38.514
#Exceed. : 51

In [45]:
conformal_predictions_AlphaNet(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

  [Info] n_calib=186 | alpha_min=0.0153
  [Step 2/9] Training base GradientBoosting model...
  [Step 2/9] Done in 2s
  [Step 3/9] Precomputing 186 LOO score vectors...

    LOO precompute:   0%|          | 0/186 [00:00<?, ?it/s]

  [Step 3/9] Done in 1s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 76.5275 | Size: 59.8593 | α̃: 0.8334 | ⏱ 0.08s/epoch | ETA: 19s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 30.8044 | Size: 10.8044 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 13s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 30.8035 | Size: 10.8035 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 12s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 30.8040 | Size: 10.8040 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 11s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 30.8046 | Size: 10.8047 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 30.8046 | Size: 10.8046 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 10s
  ✓ Run 1 complete | Final loss: 30.8046

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 49.8837 | Size: 33.8630 | α̃: 0.8010 | ⏱ 0.09s/epoch | ETA: 10s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 30.8040 | Size: 10.8040 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 9s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 30.8034 | Size: 10.8034 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 8s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 30.8043 | Size: 10.8043 | α̃: 1.0000 | ⏱ 0.12s/epoch | ETA: 8s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 30.8037 | Size: 10.8037 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 7s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 30.8048 | Size: 10.8049 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 7s
  ✓ Run 2 complete | Final loss: 30.8048

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 30.8048 | Size: 10.8048 | α̃: 1.0000 | ⏱ 0.11s/epoch | ETA: 7s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 30.8041 | Size: 10.8041 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 30.8046 | Size: 10.8046 | α̃: 1.0000 | ⏱ 0.10s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 30.8038 | Size: 10.8038 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 5s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 30.8047 | Size: 10.8047 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 30.8045 | Size: 10.8045 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 4s
  ✓ Run 3 complete | Final loss: 30.8045

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 30.5957 | Size: 11.7695 | α̃: 0.9413 | ⏱ 0.08s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 30.8048 | Size: 10.8048 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 30.8021 | Size: 10.8021 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 30.8038 | Size: 10.8038 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 30.8046 | Size: 10.8046 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 30.8040 | Size: 10.8040 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 30.8040
  [Step 4/9] Training done in 14s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GradientBoosting)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 5.4020
  Coverage       : 72.581%
  Avg Width      : 10.8040
  RMSE           : 18.5272
  Total time     : 17s
    ├─ Precompute: 1s
    └─ Training  : 14s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 17s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.725806,10.803969,18.527163,0.05,1.0,20.0,16.75

# **Conformal Predictions with CatBoost**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

In [ ]:
conformal_predictions_NEXCP(
    model_class=CatBoostRegressor,
    best_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

In [ ]:
conformal_predictions_online_super(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

In [49]:
conformal_predictions_COP(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (CatBoost) =====
Coverage : 65.591%
Avg Width: 3.378
RMSE     : 9.239
Final q  : 2.758

  Strategy  Coverage     Width      RMSE  Alpha    LR  Scale
0      COP  0.655914  3.377656  9.239091   0.05  0.05    0.5

In [ ]:
conformal_predictions_EXTREME(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

In [ ]:
conformal_predictions_AlphaNet(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

# **Conformal Predictions with HistGradientBoosting**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'HGBR')

In [53]:
conformal_predictions_NEXCP(
    model_class=HistGradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 75.269% | Width: 7.909
NexCP Full - Coverage: 72.581% | Width: 6.743
NexCP Jackknife+ aB - Coverage: 96.237% | Width: 29.263
NexCP CV+ - Coverage: 93.011% | Width: 45.502

              Strategy  Coverage      Width       RMSE            CWC
0          NexCP Split  0.752688   7.909222  10.696143  152309.939744
1           NexCP Full  0.725806   6.742656  10.696143  497895.214089
2  NexCP Jackknife+ aB  0.962366  29.262895  12.471429      29.262895
3            NexCP CV+  0.930108  45.502348  12.399002     168.527347

In [ ]:
conformal_predictions_online_super(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

In [ ]:
conformal_predictions_COP(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

In [ ]:
conformal_predictions_EXTREME(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

In [ ]:
conformal_predictions_AlphaNet(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

# **Conformal Predictions with PGBM**

In [ ]:
class PGBMWrapper(BaseEstimator, RegressorMixin):
    def __init__(self, **params):
        self.params = params
        self.model = None

    def fit(self, X, y):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        y_ = y.to_numpy() if hasattr(y, "to_numpy") else np.array(y)
        self.model = PGBM()
        self.model.train(
            train_set=(X_, y_),
            objective=mseloss_objective,
            metric=rmseloss_metric,
            params=self.params
        )
        return self

    def predict(self, X):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        return self.model.predict(X_).numpy()

In [59]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()
def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params=best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Define the quantiles you want to predict
quantiles = [0.05, 0.1, 0.15, 0.2, 0.3,
             0.4, 0.5, 0.6, 0.7, 0.8,
             0.85, 0.9, 0.95]

# DataFrame to store predictions
predictions_PGBM_df = pd.DataFrame()

# Calculate and store quantiles
for q in quantiles:
    predictions_PGBM_df[q] = np.quantile(pred_dist, q, axis=0)

# Add actual Settlement to the DataFrame
predictions_PGBM_df['Actual'] = y_test.ravel()

# Print the DataFrame with predictions for each quantile
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/500, Train metric: 22.1361
Estimator 1/500, Train metric: 20.8855
Estimator 2/500, Train metric: 19.5915
Estimator 3/500, Train metric: 18.2131
Estimator 4/500, Train metric: 17.1009
Estimator 5/500, Train metric: 16.1603
Estimator 6/500, Train metric: 15.3445
Estimator 7/500, Train metric: 14.5007
Estimator 8/500, Train metric: 13.8727
Estimator 9/500, Train metric: 13.4215
Estimator 10/500, Train metric: 12.9436
Estimator 11/500, Train metric: 12.4729
Estimator 12/500, Train metric: 12.0088
Estimator 13/500, Train metric: 11.6548
Estimator 14/500, Train metric: 11.2491
Estimator 15/500, Train metric: 10.9663
Estimator 16/500, Train metric: 10.6614
Estimator 17/500, Train metric: 10.4037
Estimator 18/500, Train metric: 10.1342
Estimator 19/500, Train metric: 9.8889
Estimator 20/500, Train metric: 9.5760
Estimator 21/500, Train metric: 9.4135
Estimator 22/500, Train metric: 9.2053
Estimator 23/500, Train metric: 8.9860
Estimator 24/500, Train metric: 8.8239
Estimator 25/500, Train metric: 8.6790
Estimator 26/500, Train metric: 8.4876
Estimator 27/500, Train metric: 8.3136
Estimator 28/500, Train metric: 8.1183
Estimator 29/500, Train metric: 7.9377
Estimator 30/500, Train metric: 7.7895
Estimator 31/500, Train metric: 7.6707
Estimator 32/500, Train metric: 7.5320
Estimator 33/500, Train metric: 7.4224
Estimator 34/500, Train metric: 7.3083
Estimator 35/500, Train metric: 7.2022
Estimator 36/500, Train metric: 7.1235
Estimator 37/500, Train metric: 7.0237
Estimator 38/500, Train metric: 6.9367
Estimator 39/500, Train metric: 6.8656
Estimator 40/500, Train metric: 6.7973
Estimator 41/500, Train metric: 6.6991
Estimator 42/500, Train metric: 6.6169
Estimator 43/500, Train metric: 6.5408
Estimator 44/500, Train metric: 6.4748
Estimator 45/500, Train metric: 6.4064
Estimator 46/500, Train metric: 6.3435
Estimator 47/500, Train metric: 6.2793
Estimator 48/500, Train metric: 6.2214
Estimator 49/500, Train metric: 6.1996
Estimator 50/500, Train metric: 6.1498
Estimator 51/500, Train metric: 6.0786
Estimator 52/500, Train metric: 6.0167
Estimator 53/500, Train metric: 5.9480
Estimator 54/500, Train metric: 5.9062
Estimator 55/500, Train metric: 5.8544
Estimator 56/500, Train metric: 5.7895
Estimator 57/500, Train metric: 5.7287
Estimator 58/500, Train metric: 5.6810
Estimator 59/500, Train metric: 5.6438
Estimator 60/500, Train metric: 5.5933
Estimator 61/500, Train metric: 5.5517
Estimator 62/500, Train metric: 5.5185
Estimator 63/500, Train metric: 5.4568
Estimator 64/500, Train metric: 5.4112
Estimator 65/500, Train metric: 5.3210
Estimator 66/500, Train metric: 5.2438
Estimator 67/500, Train metric: 5.2145
Estimator 68/500, Train metric: 5.1845
Estimator 69/500, Train metric: 5.1613
Estimator 70/500, Train metric: 5.1095
Estimator 71/500, Train metric: 5.0795
Estimator 72/500, Train metric: 5.0478
Estimator 73/500, Train metric: 4.9786
Estimator 74/500, Train metric: 4.9509
Estimator 75/500, Train metric: 4.9210
Estimator 76/500, Train metric: 4.8920
Estimator 77/500, Train metric: 4.8735
Estimator 78/500, Train metric: 4.8422
Estimator 79/500, Train metric: 4.7913
Estimator 80/500, Train metric: 4.7588
Estimator 81/500, Train metric: 4.7358
Estimator 82/500, Train metric: 4.7036
Estimator 83/500, Train metric: 4.6857
Estimator 84/500, Train metric: 4.6650
Estimator 85/500, Train metric: 4.6294
Estimator 86/500, Train metric: 4.5969
Estimator 87/500, Train metric: 4.5627
Estimator 88/500, Train metric: 4.5363
Estimator 89/500, Train metric: 4.5052
Estimator 90/500, Train metric: 4.4786
Estimator 91/500, Train metric: 4.4591
Estimator 92/500, Train metric: 4.4320
Estimator 93/500, Train metric: 4.4053
Estimator 94/500, Train metric: 4.3795
Estimator 95/500, Train metric: 4.3589
Estimator 96/500, Train metric: 4.3279
Estimator 97/500, Train metric: 4.3043
Estimator 98/500, Train metric: 4.2897
Estimator 99/500, Train metric: 4.2778
Estimator 100/500, Train metric: 4.2578
Estimator 101/500, Train metric: 4.2484
Estimator 102/500, Train metric: 4.2361
Estimator 103/500, Train metric: 4.2131
Estimator 104/500, Train metric: 4.1884
Estimator 105/500, Train metric: 4.1733
Estimator 106/500, Train metric: 4.1630
Estimator 107/500, Train metric: 4.1446
Estimator 108/500, Train metric: 4.0921
Estimator 109/500, Train metric: 4.0748
Estimator 110/500, Train metric: 4.0523
Estimator 111/500, Train metric: 4.0308
Estimator 112/500, Train metric: 4.0152
Estimator 113/500, Train metric: 4.0034
Estimator 114/500, Train metric: 3.9792
Estimator 115/500, Train metric: 3.9407
Estimator 116/500, Train metric: 3.9286
Estimator 117/500, Train metric: 3.9190
Estimator 118/500, Train metric: 3.8847
Estimator 119/500, Train metric: 3.8722
Estimator 120/500, Train metric: 3.8593
Estimator 121/500, Train metric: 3.8549
Estimator 122/500, Train metric: 3.8470
Estimator 123/500, Train metric: 3.8259
Estimator 124/500, Train metric: 3.8150
Estimator 125/500, Train metric: 3.8062
Estimator 126/500, Train metric: 3.7907
Estimator 127/500, Train metric: 3.7747
Estimator 128/500, Train metric: 3.7677
Estimator 129/500, Train metric: 3.7246
Estimator 130/500, Train metric: 3.7076
Estimator 131/500, Train metric: 3.6967
Estimator 132/500, Train metric: 3.6783
Estimator 133/500, Train metric: 3.6486
Estimator 134/500, Train metric: 3.6314
Estimator 135/500, Train metric: 3.6192
Estimator 136/500, Train metric: 3.5881
Estimator 137/500, Train metric: 3.5780
Estimator 138/500, Train metric: 3.5627
Estimator 139/500, Train metric: 3.5518
Estimator 140/500, Train metric: 3.5273
Estimator 141/500, Train metric: 3.5189
Estimator 142/500, Train metric: 3.5109
Estimator 143/500, Train metric: 3.5013
Estimator 144/500, Train metric: 3.4913
Estimator 145/500, Train metric: 3.4808
Estimator 146/500, Train metric: 3.4553
Estimator 147/500, Train metric: 3.4508
Estimator 148/500, Train metric: 3.4388
Estimator 149/500, Train metric: 3.4327
Estimator 150/500, Train metric: 3.4200
Estimator 151/500, Train metric: 3.3962
Estimator 152/500, Train metric: 3.3885
Estimator 153/500, Train metric: 3.3792
Estimator 154/500, Train metric: 3.3648
Estimator 155/500, Train metric: 3.3561
Estimator 156/500, Train metric: 3.3384
Estimator 157/500, Train metric: 3.3248
Estimator 158/500, Train metric: 3.3173
Estimator 159/500, Train metric: 3.3074
Estimator 160/500, Train metric: 3.2979
Estimator 161/500, Train metric: 3.2857
Estimator 162/500, Train metric: 3.2741
Estimator 163/500, Train metric: 3.2620
Estimator 164/500, Train metric: 3.2532
Estimator 165/500, Train metric: 3.2503
Estimator 166/500, Train metric: 3.2438
Estimator 167/500, Train metric: 3.2300
Estimator 168/500, Train metric: 3.2183
Estimator 169/500, Train metric: 3.1968
Estimator 170/500, Train metric: 3.1900
Estimator 171/500, Train metric: 3.1656
Estimator 172/500, Train metric: 3.1588
Estimator 173/500, Train metric: 3.1480
Estimator 174/500, Train metric: 3.1219
Estimator 175/500, Train metric: 3.1099
Estimator 176/500, Train metric: 3.0889
Estimator 177/500, Train metric: 3.0769
Estimator 178/500, Train metric: 3.0696
Estimator 179/500, Train metric: 3.0668
Estimator 180/500, Train metric: 3.0528
Estimator 181/500, Train metric: 3.0473
Estimator 182/500, Train metric: 3.0385
Estimator 183/500, Train metric: 3.0218
Estimator 184/500, Train metric: 3.0109
Estimator 185/500, Train metric: 3.0058
Estimator 186/500, Train metric: 2.9940
Estimator 187/500, Train metric: 2.9801
Estimator 188/500, Train metric: 2.9656
Estimator 189/500, Train metric: 2.9558
Estimator 190/500, Train metric: 2.9462
Estimator 191/500, Train metric: 2.9395
Estimator 192/500, Train metric: 2.9346
Estimator 193/500, Train metric: 2.9257
Estimator 194/500, Train metric: 2.9205
Estimator 195/500, Train metric: 2.9093
Estimator 196/500, Train metric: 2.9021
Estimator 197/500, Train metric: 2.8921
Estimator 198/500, Train metric: 2.8861
Estimator 199/500, Train metric: 2.8686
Estimator 200/500, Train metric: 2.8621
Estimator 201/500, Train metric: 2.8563
Estimator 202/500, Train metric: 2.8548
Estimator 203/500, Train metric: 2.8479
Estimator 204/500, Train metric: 2.8407
Estimator 205/500, Train metric: 2.8327
Estimator 206/500, Train metric: 2.8208
Estimator 207/500, Train metric: 2.8154
Estimator 208/500, Train metric: 2.8071
Estimator 209/500, Train metric: 2.7983
Estimator 210/500, Train metric: 2.7925
Estimator 211/500, Train metric: 2.7862
Estimator 212/500, Train metric: 2.7813
Estimator 213/500, Train metric: 2.7761
Estimator 214/500, Train metric: 2.7674
Estimator 215/500, Train metric: 2.7601
Estimator 216/500, Train metric: 2.7503
Estimator 217/500, Train metric: 2.7425
Estimator 218/500, Train metric: 2.7386
Estimator 219/500, Train metric: 2.7334
Estimator 220/500, Train metric: 2.7241
Estimator 221/500, Train metric: 2.7152
Estimator 222/500, Train metric: 2.7094
Estimator 223/500, Train metric: 2.7013
Estimator 224/500, Train metric: 2.6969
Estimator 225/500, Train metric: 2.6933
Estimator 226/500, Train metric: 2.6891
Estimator 227/500, Train metric: 2.6778
Estimator 228/500, Train metric: 2.6690
Estimator 229/500, Train metric: 2.6656
Estimator 230/500, Train metric: 2.6558
Estimator 231/500, Train metric: 2.6533
Estimator 232/500, Train metric: 2.6418
Estimator 233/500, Train metric: 2.6352
Estimator 234/500, Train metric: 2.6297
Estimator 235/500, Train metric: 2.6204
Estimator 236/500, Train metric: 2.6094
Estimator 237/500, Train metric: 2.6022
Estimator 238/500, Train metric: 2.5933
Estimator 239/500, Train metric: 2.5834
Estimator 240/500, Train metric: 2.5775
Estimator 241/500, Train metric: 2.5697
Estimator 242/500, Train metric: 2.5639
Estimator 243/500, Train metric: 2.5568
Estimator 244/500, Train metric: 2.5539
Estimator 245/500, Train metric: 2.5450
Estimator 246/500, Train metric: 2.5372
Estimator 247/500, Train metric: 2.5325
Estimator 248/500, Train metric: 2.5260
Estimator 249/500, Train metric: 2.5183
Estimator 250/500, Train metric: 2.5137
Estimator 251/500, Train metric: 2.5106
Estimator 252/500, Train metric: 2.5070
Estimator 253/500, Train metric: 2.4971
Estimator 254/500, Train metric: 2.4898
Estimator 255/500, Train metric: 2.4826
Estimator 256/500, Train metric: 2.4807
Estimator 257/500, Train metric: 2.4738
Estimator 258/500, Train metric: 2.4686
Estimator 259/500, Train metric: 2.4663
Estimator 260/500, Train metric: 2.4595
Estimator 261/500, Train metric: 2.4554
Estimator 262/500, Train metric: 2.4500
Estimator 263/500, Train metric: 2.4429
Estimator 264/500, Train metric: 2.4347
Estimator 265/500, Train metric: 2.4289
Estimator 266/500, Train metric: 2.4234
Estimator 267/500, Train metric: 2.4177
Estimator 268/500, Train metric: 2.4148
Estimator 269/500, Train metric: 2.4113
Estimator 270/500, Train metric: 2.4070
Estimator 271/500, Train metric: 2.4033
Estimator 272/500, Train metric: 2.3984
Estimator 273/500, Train metric: 2.3944
Estimator 274/500, Train metric: 2.3874
Estimator 275/500, Train metric: 2.3833
Estimator 276/500, Train metric: 2.3770
Estimator 277/500, Train metric: 2.3704
Estimator 278/500, Train metric: 2.3585
Estimator 279/500, Train metric: 2.3540
Estimator 280/500, Train metric: 2.3494
Estimator 281/500, Train metric: 2.3433
Estimator 282/500, Train metric: 2.3388
Estimator 283/500, Train metric: 2.3321
Estimator 284/500, Train metric: 2.3279
Estimator 285/500, Train metric: 2.3239
Estimator 286/500, Train metric: 2.3159
Estimator 287/500, Train metric: 2.3138
Estimator 288/500, Train metric: 2.3110
Estimator 289/500, Train metric: 2.3073
Estimator 290/500, Train metric: 2.3020
Estimator 291/500, Train metric: 2.2949
Estimator 292/500, Train metric: 2.2889
Estimator 293/500, Train metric: 2.2869
Estimator 294/500, Train metric: 2.2815
Estimator 295/500, Train metric: 2.2779
Estimator 296/500, Train metric: 2.2725
Estimator 297/500, Train metric: 2.2699
Estimator 298/500, Train metric: 2.2675
Estimator 299/500, Train metric: 2.2645
Estimator 300/500, Train metric: 2.2602
Estimator 301/500, Train metric: 2.2549
Estimator 302/500, Train metric: 2.2521
Estimator 303/500, Train metric: 2.2482
Estimator 304/500, Train metric: 2.2477
Estimator 305/500, Train metric: 2.2433
Estimator 306/500, Train metric: 2.2388
Estimator 307/500, Train metric: 2.2349
Estimator 308/500, Train metric: 2.2311
Estimator 309/500, Train metric: 2.2273
Estimator 310/500, Train metric: 2.2242
Estimator 311/500, Train metric: 2.2233
Estimator 312/500, Train metric: 2.2214
Estimator 313/500, Train metric: 2.2169
Estimator 314/500, Train metric: 2.2092
Estimator 315/500, Train metric: 2.2016
Estimator 316/500, Train metric: 2.1965
Estimator 317/500, Train metric: 2.1925
Estimator 318/500, Train metric: 2.1901
Estimator 319/500, Train metric: 2.1874
Estimator 320/500, Train metric: 2.1845
Estimator 321/500, Train metric: 2.1825
Estimator 322/500, Train metric: 2.1733
Estimator 323/500, Train metric: 2.1704
Estimator 324/500, Train metric: 2.1660
Estimator 325/500, Train metric: 2.1580
Estimator 326/500, Train metric: 2.1569
Estimator 327/500, Train metric: 2.1549
Estimator 328/500, Train metric: 2.1520
Estimator 329/500, Train metric: 2.1503
Estimator 330/500, Train metric: 2.1471
Estimator 331/500, Train metric: 2.1465
Estimator 332/500, Train metric: 2.1435
Estimator 333/500, Train metric: 2.1377
Estimator 334/500, Train metric: 2.1336
Estimator 335/500, Train metric: 2.1312
Estimator 336/500, Train metric: 2.1288
Estimator 337/500, Train metric: 2.1250
Estimator 338/500, Train metric: 2.1221
Estimator 339/500, Train metric: 2.1188
Estimator 340/500, Train metric: 2.1151
Estimator 341/500, Train metric: 2.1132
Estimator 342/500, Train metric: 2.1074
Estimator 343/500, Train metric: 2.1046
Estimator 344/500, Train metric: 2.1027
Estimator 345/500, Train metric: 2.1001
Estimator 346/500, Train metric: 2.0972
Estimator 347/500, Train metric: 2.0927
Estimator 348/500, Train metric: 2.0917
Estimator 349/500, Train metric: 2.0849
Estimator 350/500, Train metric: 2.0833
Estimator 351/500, Train metric: 2.0791
Estimator 352/500, Train metric: 2.0776
Estimator 353/500, Train metric: 2.0724
Estimator 354/500, Train metric: 2.0703
Estimator 355/500, Train metric: 2.0671
Estimator 356/500, Train metric: 2.0621
Estimator 357/500, Train metric: 2.0575
Estimator 358/500, Train metric: 2.0479
Estimator 359/500, Train metric: 2.0403
Estimator 360/500, Train metric: 2.0370
Estimator 361/500, Train metric: 2.0352
Estimator 362/500, Train metric: 2.0335
Estimator 363/500, Train metric: 2.0315
Estimator 364/500, Train metric: 2.0288
Estimator 365/500, Train metric: 2.0259
Estimator 366/500, Train metric: 2.0221
Estimator 367/500, Train metric: 2.0191
Estimator 368/500, Train metric: 2.0172
Estimator 369/500, Train metric: 2.0152
Estimator 370/500, Train metric: 2.0129
Estimator 371/500, Train metric: 2.0083
Estimator 372/500, Train metric: 2.0070
Estimator 373/500, Train metric: 2.0038
Estimator 374/500, Train metric: 2.0019
Estimator 375/500, Train metric: 2.0011
Estimator 376/500, Train metric: 1.9925
Estimator 377/500, Train metric: 1.9901
Estimator 378/500, Train metric: 1.9854
Estimator 379/500, Train metric: 1.9825
Estimator 380/500, Train metric: 1.9806
Estimator 381/500, Train metric: 1.9781
Estimator 382/500, Train metric: 1.9762
Estimator 383/500, Train metric: 1.9730
Estimator 384/500, Train metric: 1.9666
Estimator 385/500, Train metric: 1.9639
Estimator 386/500, Train metric: 1.9621
Estimator 387/500, Train metric: 1.9574
Estimator 388/500, Train metric: 1.9545
Estimator 389/500, Train metric: 1.9480
Estimator 390/500, Train metric: 1.9459
Estimator 391/500, Train metric: 1.9372
Estimator 392/500, Train metric: 1.9343
Estimator 393/500, Train metric: 1.9321
Estimator 394/500, Train metric: 1.9305
Estimator 395/500, Train metric: 1.9292
Estimator 396/500, Train metric: 1.9268
Estimator 397/500, Train metric: 1.9261
Estimator 398/500, Train metric: 1.9198
Estimator 399/500, Train metric: 1.9172
Estimator 400/500, Train metric: 1.9157
Estimator 401/500, Train metric: 1.9137
Estimator 402/500, Train metric: 1.9118
Estimator 403/500, Train metric: 1.9100
Estimator 404/500, Train metric: 1.9080
Estimator 405/500, Train metric: 1.9028
Estimator 406/500, Train metric: 1.9012
Estimator 407/500, Train metric: 1.9003
Estimator 408/500, Train metric: 1.8979
Estimator 409/500, Train metric: 1.8955
Estimator 410/500, Train metric: 1.8934
Estimator 411/500, Train metric: 1.8910
Estimator 412/500, Train metric: 1.8876
Estimator 413/500, Train metric: 1.8859
Estimator 414/500, Train metric: 1.8822
Estimator 415/500, Train metric: 1.8804
Estimator 416/500, Train metric: 1.8775
Estimator 417/500, Train metric: 1.8771
Estimator 418/500, Train metric: 1.8741
Estimator 419/500, Train metric: 1.8707
Estimator 420/500, Train metric: 1.8685
Estimator 421/500, Train metric: 1.8676
Estimator 422/500, Train metric: 1.8666
Estimator 423/500, Train metric: 1.8644
Estimator 424/500, Train metric: 1.8630
Estimator 425/500, Train metric: 1.8627
Estimator 426/500, Train metric: 1.8612
Estimator 427/500, Train metric: 1.8585
Estimator 428/500, Train metric: 1.8556
Estimator 429/500, Train metric: 1.8535
Estimator 430/500, Train metric: 1.8508
Estimator 431/500, Train metric: 1.8491
Estimator 432/500, Train metric: 1.8475
Estimator 433/500, Train metric: 1.8450
Estimator 434/500, Train metric: 1.8424
Estimator 435/500, Train metric: 1.8398
Estimator 436/500, Train metric: 1.8339
Estimator 437/500, Train metric: 1.8272
Estimator 438/500, Train metric: 1.8255
Estimator 439/500, Train metric: 1.8239
Estimator 440/500, Train metric: 1.8212
Estimator 441/500, Train metric: 1.8192
Estimator 442/500, Train metric: 1.8177
Estimator 443/500, Train metric: 1.8171
Estimator 444/500, Train metric: 1.8133
Estimator 445/500, Train metric: 1.8123
Estimator 446/500, Train metric: 1.8097
Estimator 447/500, Train metric: 1.8077
Estimator 448/500, Train metric: 1.8056
Estimator 449/500, Train metric: 1.8023
Estimator 450/500, Train metric: 1.8006
Estimator 451/500, Train metric: 1.7979
Estimator 452/500, Train metric: 1.7964
Estimator 453/500, Train metric: 1.7930
Estimator 454/500, Train metric: 1.7903
Estimator 455/500, Train metric: 1.7884
Estimator 456/500, Train metric: 1.7869
Estimator 457/500, Train metric: 1.7846
Estimator 458/500, Train metric: 1.7824
Estimator 459/500, Train metric: 1.7811
Estimator 460/500, Train metric: 1.7798
Estimator 461/500, Train metric: 1.7783
Estimator 462/500, Train metric: 1.7773
Estimator 463/500, Train metric: 1.7757
Estimator 464/500, Train metric: 1.7738
Estimator 465/500, Train metric: 1.7718
Estimator 466/500, Train metric: 1.7699
Estimator 467/500, Train metric: 1.7665
Estimator 468/500, Train metric: 1.7661
Estimator 469/500, Train metric: 1.7649
Estimator 470/500, Train metric: 1.7633
Estimator 471/500, Train metric: 1.7630
Estimator 472/500, Train metric: 1.7612
Estimator 473/500, Train metric: 1.7591
Estimator 474/500, Train metric: 1.7557
Estimator 475/500, Train metric: 1.7533
Estimator 476/500, Train metric: 1.7518
Estimator 477/500, Train metric: 1.7509
Estimator 478/500, Train metric: 1.7498
Estimator 479/500, Train metric: 1.7478
Estimator 480/500, Train metric: 1.7417
Estimator 481/500, Train metric: 1.7401
Estimator 482/500, Train metric: 1.7388
Estimator 483/500, Train metric: 1.7380
Estimator 484/500, Train metric: 1.7323
Estimator 485/500, Train metric: 1.7308
Estimator 486/500, Train metric: 1.7281
Estimator 487/500, Train metric: 1.7230
Estimator 488/500, Train metric: 1.7222
Estimator 489/500, Train metric: 1.7210
Estimator 490/500, Train metric: 1.7201
Estimator 491/500, Train metric: 1.7181
Estimator 492/500, Train metric: 1.7170
Estimator 493/500, Train metric: 1.7135
Estimator 494/500, Train metric: 1.7108
Estimator 495/500, Train metric: 1.7079
Estimator 496/500, Train metric: 1.7066
Estimator 497/500, Train metric: 1.7052
Estimator 498/500, Train metric: 1.7041
Estimator 499/500, Train metric: 1.7032
        0.05        0.1       0.15        0.2        0.3        0.4  \

In [ ]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

In [ ]:

def to_numpy_1d(y):
    return y.to_numpy().ravel() if hasattr(y, "to_numpy") else np.asarray(y).ravel()


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values, weights = values[sorter], weights[sorter]
    cdf = np.cumsum(weights) / np.sum(weights)
    return np.interp(q, cdf, values)



# ============================================================
# NexCP for PGBM (Excel-safe, NexCP-style, NO RETURNS)
# ============================================================

def conformal_predictions_NEXCP_PGBM(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    # ========================================================
    # Data conversion (PGBM-specific)
    # ========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    STRATEGIES = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # ========================================================
    # Fit base model
    # ========================================================
    base_model = model_class(**best_params)
    base_model.fit(Xtr, ytr)

    yhat_tr = base_model.predict(Xtr)
    yhat_te = base_model.predict(Xte)
    residuals = np.abs(ytr - yhat_tr)

    # ========================================================
    # NexCP – Split (Exponentially Weighted)
    # ========================================================
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_te
    int_pred["NexCP-Split"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Full
    # ========================================================
    q = np.quantile(residuals, 1 - alpha)
    y_pred["NexCP-Full"] = yhat_te
    int_pred["NexCP-Full"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Jackknife+ aB
    # ========================================================
    rng = np.random.default_rng(seed)
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(Xtr), len(Xtr), replace=True)
        m = model_class(**best_params)
        m.fit(Xtr[idx], ytr[idx])

        q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # ========================================================
    # NexCP – CV+
    # ========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    lowers, uppers, preds = [], [], []

    for tr_idx, cal_idx in kf.split(Xtr):
        m = model_class(**best_params)
        m.fit(Xtr[tr_idx], ytr[tr_idx])

        q = np.quantile(np.abs(ytr[cal_idx] - m.predict(Xtr[cal_idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== NEXCP (PGBM) RESULTS =====")

    for s in STRATEGIES:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in STRATEGIES:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("Settlement")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary sheet ----
        sheet_name = "NEXCP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"NEXCP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        sheet_name = "NEXCP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_NEXCP_PGBM(
    model_class=PGBMWrapper,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

In [ ]:
def conformal_predictions_online_super_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    STRATEGIES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    if strategies == "all":
        strategies = list(STRATEGIES.keys())

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Base model (trained once)
    # --------------------------------------------------------
    base_model = model_class(**model_params)
    base_model.fit(Xtr, ytr)

    yhat_train = base_model.predict(Xtr)

    # --------------------------------------------------------
    # Streaming predictions
    # --------------------------------------------------------
    X_all = np.vstack([Xtr, Xte])
    y_all = np.concatenate([ytr, yte])

    n_train = len(Xtr)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train

    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # ========================================================
    # Online Split
    # ========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_pred["Online-Split"] - q,
                                          y_pred["Online-Split"] + q]

    # ========================================================
    # Online CV+
    # ========================================================
    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    # ========================================================
    # Online Jackknife+ aB
    # ========================================================
    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(Xtr[idx], ytr[idx])

            q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
            p = m.predict(Xte)

            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)

        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    # ========================================================
    # SAOCP
    # ========================================================
    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, t // 2), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    # ========================================================
    # SF-OGD
    # ========================================================
    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            grad = alpha - (residuals[t] <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    # ========================================================
    # FACI
    # ========================================================
    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    # ========================================================
    # MFCS-Split ✅ (ADDED)
    # ========================================================
    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_pred["MFCS-Split"] - q,
                                       y_pred["MFCS-Split"] + q]

    # ========================================================
    # MFCS-Full
    # ========================================================
    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            q = np.quantile(np.abs(y_all[:t] - m.predict(X_all[:t])), 1 - alpha)
            preds.append(yhat)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== ONLINE CP (PGBM) RESULTS =====")

    for s in y_pred:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("Settlement")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "ONLINECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "ONLINECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_online_super_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
    strategies="all",
)

In [ ]:
def conformal_predictions_COP_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,
    T_burnin=50,
    scale=0.5,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Safe NumPy conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # Train base PGBM model
    # =========================================================
    model = model_class(**model_params)
    model.fit(Xtr, ytr)

    y_pred_test = model.predict(Xte).ravel()
    y_pred_train = model.predict(Xtr).ravel()

    # Absolute residuals (symmetric COP)
    scores_test = np.abs(yte - y_pred_test)
    scores_train = np.abs(ytr - y_pred_train)

    T_test = len(scores_test)

    # =========================================================
    # COP initialization
    # =========================================================
    init_q = np.quantile(scores_train, 1 - alpha)

    qs = np.zeros(T_test)
    qts = np.zeros(T_test)
    integrators = np.zeros(T_test)
    covereds = np.zeros(T_test)

    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # Online COP loop
    # =========================================================
    for t in range(T_test - 1):

        covereds[t] = 1 if qs[t] >= scores_test[t] else 0

        # Standard COP gradient
        grad = alpha if covereds[t] else -(1 - alpha)

        # Distribution-informed (optimistic) gradient
        if t < T_burnin:
            grad_i = 0.0
        else:
            window_s = scores_test[t - T_burnin : t]
            target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= target) - (1 - alpha)

        # Updates
        integrator = -scale * grad_i
        qts[t + 1] = qts[t] - lr * grad
        integrators[t + 1] = lr * integrator
        qs[t + 1] = max(0.0, qts[t + 1] + integrators[t + 1])

    covereds[-1] = 1 if qs[-1] >= scores_test[-1] else 0

    # =========================================================
    # Prediction intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== COP (PGBM) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale,
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score": scores_test,
        "adaptive_q": qs,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Predicted mean")


    ax.set_title(f"COP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("Settlement")
    ax.legend(loc="upper left")

    plt.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "COP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1
        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

conformal_predictions_COP_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

In [64]:
def conformal_predictions_EXTREME_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Train / calibration split
    # --------------------------------------------------------
    X_fit, X_cal, y_fit, y_cal = train_test_split(
        Xtr, ytr, test_size=calib_size, random_state=random_state, shuffle=True
    )

    # --------------------------------------------------------
    # Train model
    # --------------------------------------------------------
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(Xte)
    y_pred_cal = model.predict(X_cal)

    # --------------------------------------------------------
    # Upper-tail nonconformity scores
    # --------------------------------------------------------
    scores = y_cal - y_pred_cal
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few exceedances for EVT fitting.")

    # --------------------------------------------------------
    # Peaks-over-threshold
    # --------------------------------------------------------
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # --------------------------------------------------------
    # Bootstrap EVT quantile
    # --------------------------------------------------------
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        res = np.random.choice(excesses, size=n_exc, replace=True)
        xi, _, sigma = genpareto.fit(res, floc=0)
        q = u + (sigma / xi) * ((n_scores / (n_scores * alpha)) ** xi - 1)
        boot_q.append(q)

    q_extreme = np.quantile(boot_q, 0.95)

    # --------------------------------------------------------
    # FINITE prediction intervals (for plotting & width)
    # --------------------------------------------------------
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # --------------------------------------------------------
    # Metrics (one-sided coverage)
    # --------------------------------------------------------
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(yte <= ymax)
    width = q_extreme

    print(f"\n===== EXTREME CP (PGBM) =====")
    print(f"Coverage     : {coverage*100:.3f}%")
    print(f"Width        : {width:.3f}")
    print(f"RMSE         : {rmse:.3f}")
    print(f"q_extreme    : {q_extreme:.3f}")
    print(f"threshold_u  : {u:.3f}")
    print(f"#Exceedances : {len(scores)}")

    # --------------------------------------------------------
    # Summary table
    # --------------------------------------------------------
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # --------------------------------------------------------
    # Values table
    # --------------------------------------------------------
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (yte <= ymax).astype(int),
        "residual": yte - y_pred_test,
    })

    # --------------------------------------------------------
    # Plot (SAVE ONLY — NO SHOW)
    # --------------------------------------------------------
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme CP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("Settlement")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # --------------------------------------------------------
    # Excel export (append-safe)
    # --------------------------------------------------------
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "EXTREMECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_EXTREME_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

Training on CPU
Estimator 0/500, Train metric: 22.2958
Estimator 1/500, Train metric: 21.1768
Estimator 2/500, Train metric: 20.2888
Estimator 3/500, Train metric: 19.5145
Estimator 4/500, Train metric: 18.5562
Estimator 5/500, Train metric: 17.6373
Estimator 6/500, Train metric: 16.9123
Estimator 7/500, Train metric: 16.2313
Estimator 8/500, Train metric: 15.5957
Estimator 9/500, Train metric: 15.1452
Estimator 10/500, Train metric: 14.6688
Estimator 11/500, Train metric: 14.1592
Estimator 12/500, Train metric: 13.7088
Estimator 13/500, Train metric: 13.2435
Estimator 14/500, Train metric: 12.9565
Estimator 15/500, Train metric: 12.4760
Estimator 16/500, Train metric: 12.0153
Estimator 17/500, Train metric: 11.7203
Estimator 18/500, Train metric: 11.4416
Estimator 19/500, Train metric: 11.1693
Estimator 20/500, Train metric: 10.8905
Estimator 21/500, Train metric: 10.5974
Estimator 22/500, Train metric: 10.2814
Estimator 23/500, Train metric: 10.0393
Estimator 24/500, Train metric: 9.8244
Estimator 25/500, Train metric: 9.5960
Estimator 26/500, Train metric: 9.3785
Estimator 27/500, Train metric: 9.1966
Estimator 28/500, Train metric: 9.0916
Estimator 29/500, Train metric: 8.9403
Estimator 30/500, Train metric: 8.7645
Estimator 31/500, Train metric: 8.6309
Estimator 32/500, Train metric: 8.4359
Estimator 33/500, Train metric: 8.2425
Estimator 34/500, Train metric: 8.1146
Estimator 35/500, Train metric: 7.9898
Estimator 36/500, Train metric: 7.8988
Estimator 37/500, Train metric: 7.7451
Estimator 38/500, Train metric: 7.6307
Estimator 39/500, Train metric: 7.5100
Estimator 40/500, Train metric: 7.3979
Estimator 41/500, Train metric: 7.3049
Estimator 42/500, Train metric: 7.1968
Estimator 43/500, Train metric: 7.0622
Estimator 44/500, Train metric: 6.9875
Estimator 45/500, Train metric: 6.8801
Estimator 46/500, Train metric: 6.7734
Estimator 47/500, Train metric: 6.7041
Estimator 48/500, Train metric: 6.6190
Estimator 49/500, Train metric: 6.4989
Estimator 50/500, Train metric: 6.4471
Estimator 51/500, Train metric: 6.3698
Estimator 52/500, Train metric: 6.3187
Estimator 53/500, Train metric: 6.2656
Estimator 54/500, Train metric: 6.2110
Estimator 55/500, Train metric: 6.1230
Estimator 56/500, Train metric: 6.0548
Estimator 57/500, Train metric: 5.9884
Estimator 58/500, Train metric: 5.9514
Estimator 59/500, Train metric: 5.9049
Estimator 60/500, Train metric: 5.8433
Estimator 61/500, Train metric: 5.8036
Estimator 62/500, Train metric: 5.7537
Estimator 63/500, Train metric: 5.7148
Estimator 64/500, Train metric: 5.6680
Estimator 65/500, Train metric: 5.6216
Estimator 66/500, Train metric: 5.5447
Estimator 67/500, Train metric: 5.4767
Estimator 68/500, Train metric: 5.4383
Estimator 69/500, Train metric: 5.4064
Estimator 70/500, Train metric: 5.3633
Estimator 71/500, Train metric: 5.3398
Estimator 72/500, Train metric: 5.3063
Estimator 73/500, Train metric: 5.2840
Estimator 74/500, Train metric: 5.2555
Estimator 75/500, Train metric: 5.2153
Estimator 76/500, Train metric: 5.1819
Estimator 77/500, Train metric: 5.1463
Estimator 78/500, Train metric: 5.1138
Estimator 79/500, Train metric: 5.0754
Estimator 80/500, Train metric: 5.0487
Estimator 81/500, Train metric: 5.0239
Estimator 82/500, Train metric: 4.9934
Estimator 83/500, Train metric: 4.9608
Estimator 84/500, Train metric: 4.9057
Estimator 85/500, Train metric: 4.8762
Estimator 86/500, Train metric: 4.8452
Estimator 87/500, Train metric: 4.8327
Estimator 88/500, Train metric: 4.7896
Estimator 89/500, Train metric: 4.7326
Estimator 90/500, Train metric: 4.7139
Estimator 91/500, Train metric: 4.7008
Estimator 92/500, Train metric: 4.6557
Estimator 93/500, Train metric: 4.6125
Estimator 94/500, Train metric: 4.5740
Estimator 95/500, Train metric: 4.5579
Estimator 96/500, Train metric: 4.5320
Estimator 97/500, Train metric: 4.5088
Estimator 98/500, Train metric: 4.4785
Estimator 99/500, Train metric: 4.4543
Estimator 100/500, Train metric: 4.4308
Estimator 101/500, Train metric: 4.4227
Estimator 102/500, Train metric: 4.3816
Estimator 103/500, Train metric: 4.3561
Estimator 104/500, Train metric: 4.3347
Estimator 105/500, Train metric: 4.2858
Estimator 106/500, Train metric: 4.2505
Estimator 107/500, Train metric: 4.2322
Estimator 108/500, Train metric: 4.2158
Estimator 109/500, Train metric: 4.1969
Estimator 110/500, Train metric: 4.1636
Estimator 111/500, Train metric: 4.1373
Estimator 112/500, Train metric: 4.1202
Estimator 113/500, Train metric: 4.0828
Estimator 114/500, Train metric: 4.0554
Estimator 115/500, Train metric: 4.0185
Estimator 116/500, Train metric: 4.0055
Estimator 117/500, Train metric: 3.9840
Estimator 118/500, Train metric: 3.9723
Estimator 119/500, Train metric: 3.9497
Estimator 120/500, Train metric: 3.9391
Estimator 121/500, Train metric: 3.9207
Estimator 122/500, Train metric: 3.9068
Estimator 123/500, Train metric: 3.8944
Estimator 124/500, Train metric: 3.8779
Estimator 125/500, Train metric: 3.8462
Estimator 126/500, Train metric: 3.8312
Estimator 127/500, Train metric: 3.8019
Estimator 128/500, Train metric: 3.7708
Estimator 129/500, Train metric: 3.7596
Estimator 130/500, Train metric: 3.7417
Estimator 131/500, Train metric: 3.7219
Estimator 132/500, Train metric: 3.7114
Estimator 133/500, Train metric: 3.6993
Estimator 134/500, Train metric: 3.6840
Estimator 135/500, Train metric: 3.6657
Estimator 136/500, Train metric: 3.6498
Estimator 137/500, Train metric: 3.6383
Estimator 138/500, Train metric: 3.6096
Estimator 139/500, Train metric: 3.5974
Estimator 140/500, Train metric: 3.5851
Estimator 141/500, Train metric: 3.5722
Estimator 142/500, Train metric: 3.5524
Estimator 143/500, Train metric: 3.5398
Estimator 144/500, Train metric: 3.5269
Estimator 145/500, Train metric: 3.5158
Estimator 146/500, Train metric: 3.4887
Estimator 147/500, Train metric: 3.4749
Estimator 148/500, Train metric: 3.4685
Estimator 149/500, Train metric: 3.4525
Estimator 150/500, Train metric: 3.4318
Estimator 151/500, Train metric: 3.4138
Estimator 152/500, Train metric: 3.3936
Estimator 153/500, Train metric: 3.3847
Estimator 154/500, Train metric: 3.3575
Estimator 155/500, Train metric: 3.3406
Estimator 156/500, Train metric: 3.3319
Estimator 157/500, Train metric: 3.3183
Estimator 158/500, Train metric: 3.3040
Estimator 159/500, Train metric: 3.2933
Estimator 160/500, Train metric: 3.2881
Estimator 161/500, Train metric: 3.2765
Estimator 162/500, Train metric: 3.2606
Estimator 163/500, Train metric: 3.2553
Estimator 164/500, Train metric: 3.2437
Estimator 165/500, Train metric: 3.2314
Estimator 166/500, Train metric: 3.2220
Estimator 167/500, Train metric: 3.2101
Estimator 168/500, Train metric: 3.1980
Estimator 169/500, Train metric: 3.1947
Estimator 170/500, Train metric: 3.1904
Estimator 171/500, Train metric: 3.1826
Estimator 172/500, Train metric: 3.1703
Estimator 173/500, Train metric: 3.1599
Estimator 174/500, Train metric: 3.1496
Estimator 175/500, Train metric: 3.1404
Estimator 176/500, Train metric: 3.1317
Estimator 177/500, Train metric: 3.1255
Estimator 178/500, Train metric: 3.1111
Estimator 179/500, Train metric: 3.0966
Estimator 180/500, Train metric: 3.0883
Estimator 181/500, Train metric: 3.0760
Estimator 182/500, Train metric: 3.0679
Estimator 183/500, Train metric: 3.0547
Estimator 184/500, Train metric: 3.0391
Estimator 185/500, Train metric: 3.0222
Estimator 186/500, Train metric: 3.0038
Estimator 187/500, Train metric: 2.9956
Estimator 188/500, Train metric: 2.9853
Estimator 189/500, Train metric: 2.9829
Estimator 190/500, Train metric: 2.9720
Estimator 191/500, Train metric: 2.9657
Estimator 192/500, Train metric: 2.9585
Estimator 193/500, Train metric: 2.9504
Estimator 194/500, Train metric: 2.9414
Estimator 195/500, Train metric: 2.9331
Estimator 196/500, Train metric: 2.9257
Estimator 197/500, Train metric: 2.9137
Estimator 198/500, Train metric: 2.9012
Estimator 199/500, Train metric: 2.8864
Estimator 200/500, Train metric: 2.8785
Estimator 201/500, Train metric: 2.8717
Estimator 202/500, Train metric: 2.8585
Estimator 203/500, Train metric: 2.8495
Estimator 204/500, Train metric: 2.8369
Estimator 205/500, Train metric: 2.8207
Estimator 206/500, Train metric: 2.8150
Estimator 207/500, Train metric: 2.8061
Estimator 208/500, Train metric: 2.7979
Estimator 209/500, Train metric: 2.7884
Estimator 210/500, Train metric: 2.7775
Estimator 211/500, Train metric: 2.7714
Estimator 212/500, Train metric: 2.7665
Estimator 213/500, Train metric: 2.7565
Estimator 214/500, Train metric: 2.7505
Estimator 215/500, Train metric: 2.7398
Estimator 216/500, Train metric: 2.7309
Estimator 217/500, Train metric: 2.7224
Estimator 218/500, Train metric: 2.7172
Estimator 219/500, Train metric: 2.7036
Estimator 220/500, Train metric: 2.6925
Estimator 221/500, Train metric: 2.6899
Estimator 222/500, Train metric: 2.6811
Estimator 223/500, Train metric: 2.6749
Estimator 224/500, Train metric: 2.6694
Estimator 225/500, Train metric: 2.6625
Estimator 226/500, Train metric: 2.6545
Estimator 227/500, Train metric: 2.6483
Estimator 228/500, Train metric: 2.6443
Estimator 229/500, Train metric: 2.6371
Estimator 230/500, Train metric: 2.6301
Estimator 231/500, Train metric: 2.6235
Estimator 232/500, Train metric: 2.6178
Estimator 233/500, Train metric: 2.6167
Estimator 234/500, Train metric: 2.6062
Estimator 235/500, Train metric: 2.5987
Estimator 236/500, Train metric: 2.5913
Estimator 237/500, Train metric: 2.5831
Estimator 238/500, Train metric: 2.5742
Estimator 239/500, Train metric: 2.5711
Estimator 240/500, Train metric: 2.5656
Estimator 241/500, Train metric: 2.5588
Estimator 242/500, Train metric: 2.5502
Estimator 243/500, Train metric: 2.5463
Estimator 244/500, Train metric: 2.5401
Estimator 245/500, Train metric: 2.5368
Estimator 246/500, Train metric: 2.5293
Estimator 247/500, Train metric: 2.5247
Estimator 248/500, Train metric: 2.5203
Estimator 249/500, Train metric: 2.5141
Estimator 250/500, Train metric: 2.5086
Estimator 251/500, Train metric: 2.5048
Estimator 252/500, Train metric: 2.5007
Estimator 253/500, Train metric: 2.4961
Estimator 254/500, Train metric: 2.4906
Estimator 255/500, Train metric: 2.4839
Estimator 256/500, Train metric: 2.4795
Estimator 257/500, Train metric: 2.4766
Estimator 258/500, Train metric: 2.4702
Estimator 259/500, Train metric: 2.4648
Estimator 260/500, Train metric: 2.4624
Estimator 261/500, Train metric: 2.4570
Estimator 262/500, Train metric: 2.4527
Estimator 263/500, Train metric: 2.4482
Estimator 264/500, Train metric: 2.4407
Estimator 265/500, Train metric: 2.4368
Estimator 266/500, Train metric: 2.4324
Estimator 267/500, Train metric: 2.4276
Estimator 268/500, Train metric: 2.4242
Estimator 269/500, Train metric: 2.4207
Estimator 270/500, Train metric: 2.4153
Estimator 271/500, Train metric: 2.4126
Estimator 272/500, Train metric: 2.4061
Estimator 273/500, Train metric: 2.3986
Estimator 274/500, Train metric: 2.3968
Estimator 275/500, Train metric: 2.3924
Estimator 276/500, Train metric: 2.3881
Estimator 277/500, Train metric: 2.3837
Estimator 278/500, Train metric: 2.3800
Estimator 279/500, Train metric: 2.3744
Estimator 280/500, Train metric: 2.3707
Estimator 281/500, Train metric: 2.3662
Estimator 282/500, Train metric: 2.3626
Estimator 283/500, Train metric: 2.3581
Estimator 284/500, Train metric: 2.3543
Estimator 285/500, Train metric: 2.3516
Estimator 286/500, Train metric: 2.3476
Estimator 287/500, Train metric: 2.3460
Estimator 288/500, Train metric: 2.3423
Estimator 289/500, Train metric: 2.3388
Estimator 290/500, Train metric: 2.3358
Estimator 291/500, Train metric: 2.3317
Estimator 292/500, Train metric: 2.3292
Estimator 293/500, Train metric: 2.3241
Estimator 294/500, Train metric: 2.3149
Estimator 295/500, Train metric: 2.3131
Estimator 296/500, Train metric: 2.3107
Estimator 297/500, Train metric: 2.3062
Estimator 298/500, Train metric: 2.3013
Estimator 299/500, Train metric: 2.2974
Estimator 300/500, Train metric: 2.2934
Estimator 301/500, Train metric: 2.2892
Estimator 302/500, Train metric: 2.2867
Estimator 303/500, Train metric: 2.2842
Estimator 304/500, Train metric: 2.2779
Estimator 305/500, Train metric: 2.2738
Estimator 306/500, Train metric: 2.2709
Estimator 307/500, Train metric: 2.2683
Estimator 308/500, Train metric: 2.2635
Estimator 309/500, Train metric: 2.2573
Estimator 310/500, Train metric: 2.2535
Estimator 311/500, Train metric: 2.2495
Estimator 312/500, Train metric: 2.2464
Estimator 313/500, Train metric: 2.2443
Estimator 314/500, Train metric: 2.2413
Estimator 315/500, Train metric: 2.2389
Estimator 316/500, Train metric: 2.2366
Estimator 317/500, Train metric: 2.2336
Estimator 318/500, Train metric: 2.2315
Estimator 319/500, Train metric: 2.2294
Estimator 320/500, Train metric: 2.2246
Estimator 321/500, Train metric: 2.2191
Estimator 322/500, Train metric: 2.2158
Estimator 323/500, Train metric: 2.2137
Estimator 324/500, Train metric: 2.2091
Estimator 325/500, Train metric: 2.2065
Estimator 326/500, Train metric: 2.2029
Estimator 327/500, Train metric: 2.2010
Estimator 328/500, Train metric: 2.1929
Estimator 329/500, Train metric: 2.1846
Estimator 330/500, Train metric: 2.1776
Estimator 331/500, Train metric: 2.1710
Estimator 332/500, Train metric: 2.1661
Estimator 333/500, Train metric: 2.1625
Estimator 334/500, Train metric: 2.1562
Estimator 335/500, Train metric: 2.1539
Estimator 336/500, Train metric: 2.1515
Estimator 337/500, Train metric: 2.1443
Estimator 338/500, Train metric: 2.1393
Estimator 339/500, Train metric: 2.1346
Estimator 340/500, Train metric: 2.1330
Estimator 341/500, Train metric: 2.1312
Estimator 342/500, Train metric: 2.1308
Estimator 343/500, Train metric: 2.1295
Estimator 344/500, Train metric: 2.1268
Estimator 345/500, Train metric: 2.1248
Estimator 346/500, Train metric: 2.1227
Estimator 347/500, Train metric: 2.1210
Estimator 348/500, Train metric: 2.1198
Estimator 349/500, Train metric: 2.1169
Estimator 350/500, Train metric: 2.1156
Estimator 351/500, Train metric: 2.1132
Estimator 352/500, Train metric: 2.1110
Estimator 353/500, Train metric: 2.1092
Estimator 354/500, Train metric: 2.1055
Estimator 355/500, Train metric: 2.1033
Estimator 356/500, Train metric: 2.1025
Estimator 357/500, Train metric: 2.0981
Estimator 358/500, Train metric: 2.0967
Estimator 359/500, Train metric: 2.0924
Estimator 360/500, Train metric: 2.0907
Estimator 361/500, Train metric: 2.0844
Estimator 362/500, Train metric: 2.0822
Estimator 363/500, Train metric: 2.0809
Estimator 364/500, Train metric: 2.0790
Estimator 365/500, Train metric: 2.0775
Estimator 366/500, Train metric: 2.0727
Estimator 367/500, Train metric: 2.0658
Estimator 368/500, Train metric: 2.0643
Estimator 369/500, Train metric: 2.0625
Estimator 370/500, Train metric: 2.0603
Estimator 371/500, Train metric: 2.0567
Estimator 372/500, Train metric: 2.0504
Estimator 373/500, Train metric: 2.0462
Estimator 374/500, Train metric: 2.0395
Estimator 375/500, Train metric: 2.0374
Estimator 376/500, Train metric: 2.0341
Estimator 377/500, Train metric: 2.0335
Estimator 378/500, Train metric: 2.0327
Estimator 379/500, Train metric: 2.0309
Estimator 380/500, Train metric: 2.0265
Estimator 381/500, Train metric: 2.0239
Estimator 382/500, Train metric: 2.0221
Estimator 383/500, Train metric: 2.0181
Estimator 384/500, Train metric: 2.0160
Estimator 385/500, Train metric: 2.0123
Estimator 386/500, Train metric: 2.0116
Estimator 387/500, Train metric: 2.0067
Estimator 388/500, Train metric: 2.0051
Estimator 389/500, Train metric: 2.0032
Estimator 390/500, Train metric: 2.0015
Estimator 391/500, Train metric: 1.9961
Estimator 392/500, Train metric: 1.9949
Estimator 393/500, Train metric: 1.9935
Estimator 394/500, Train metric: 1.9915
Estimator 395/500, Train metric: 1.9894
Estimator 396/500, Train metric: 1.9871
Estimator 397/500, Train metric: 1.9860
Estimator 398/500, Train metric: 1.9840
Estimator 399/500, Train metric: 1.9827
Estimator 400/500, Train metric: 1.9810
Estimator 401/500, Train metric: 1.9794
Estimator 402/500, Train metric: 1.9756
Estimator 403/500, Train metric: 1.9751
Estimator 404/500, Train metric: 1.9703
Estimator 405/500, Train metric: 1.9685
Estimator 406/500, Train metric: 1.9667
Estimator 407/500, Train metric: 1.9670
Estimator 408/500, Train metric: 1.9647
Estimator 409/500, Train metric: 1.9618
Estimator 410/500, Train metric: 1.9604
Estimator 411/500, Train metric: 1.9592
Estimator 412/500, Train metric: 1.9577
Estimator 413/500, Train metric: 1.9573
Estimator 414/500, Train metric: 1.9557
Estimator 415/500, Train metric: 1.9541
Estimator 416/500, Train metric: 1.9528
Estimator 417/500, Train metric: 1.9484
Estimator 418/500, Train metric: 1.9465
Estimator 419/500, Train metric: 1.9438
Estimator 420/500, Train metric: 1.9425
Estimator 421/500, Train metric: 1.9395
Estimator 422/500, Train metric: 1.9379
Estimator 423/500, Train metric: 1.9362
Estimator 424/500, Train metric: 1.9347
Estimator 425/500, Train metric: 1.9338
Estimator 426/500, Train metric: 1.9314
Estimator 427/500, Train metric: 1.9305
Estimator 428/500, Train metric: 1.9298
Estimator 429/500, Train metric: 1.9286
Estimator 430/500, Train metric: 1.9262
Estimator 431/500, Train metric: 1.9249
Estimator 432/500, Train metric: 1.9227
Estimator 433/500, Train metric: 1.9192
Estimator 434/500, Train metric: 1.9185
Estimator 435/500, Train metric: 1.9170
Estimator 436/500, Train metric: 1.9159
Estimator 437/500, Train metric: 1.9133
Estimator 438/500, Train metric: 1.9117
Estimator 439/500, Train metric: 1.9115
Estimator 440/500, Train metric: 1.9088
Estimator 441/500, Train metric: 1.9044
Estimator 442/500, Train metric: 1.9033
Estimator 443/500, Train metric: 1.9021
Estimator 444/500, Train metric: 1.9008
Estimator 445/500, Train metric: 1.8990
Estimator 446/500, Train metric: 1.8975
Estimator 447/500, Train metric: 1.8963
Estimator 448/500, Train metric: 1.8949
Estimator 449/500, Train metric: 1.8943
Estimator 450/500, Train metric: 1.8920
Estimator 451/500, Train metric: 1.8904
Estimator 452/500, Train metric: 1.8873
Estimator 453/500, Train metric: 1.8863
Estimator 454/500, Train metric: 1.8854
Estimator 455/500, Train metric: 1.8819
Estimator 456/500, Train metric: 1.8782
Estimator 457/500, Train metric: 1.8769
Estimator 458/500, Train metric: 1.8727
Estimator 459/500, Train metric: 1.8704
Estimator 460/500, Train metric: 1.8694
Estimator 461/500, Train metric: 1.8679
Estimator 462/500, Train metric: 1.8679
Estimator 463/500, Train metric: 1.8665
Estimator 464/500, Train metric: 1.8638
Estimator 465/500, Train metric: 1.8621
Estimator 466/500, Train metric: 1.8588
Estimator 467/500, Train metric: 1.8574
Estimator 468/500, Train metric: 1.8559
Estimator 469/500, Train metric: 1.8524
Estimator 470/500, Train metric: 1.8507
Estimator 471/500, Train metric: 1.8485
Estimator 472/500, Train metric: 1.8439
Estimator 473/500, Train metric: 1.8397
Estimator 474/500, Train metric: 1.8392
Estimator 475/500, Train metric: 1.8384
Estimator 476/500, Train metric: 1.8371
Estimator 477/500, Train metric: 1.8359
Estimator 478/500, Train metric: 1.8340
Estimator 479/500, Train metric: 1.8323
Estimator 480/500, Train metric: 1.8322
Estimator 481/500, Train metric: 1.8306
Estimator 482/500, Train metric: 1.8286
Estimator 483/500, Train metric: 1.8278
Estimator 484/500, Train metric: 1.8276
Estimator 485/500, Train metric: 1.8249
Estimator 486/500, Train metric: 1.8222
Estimator 487/500, Train metric: 1.8207
Estimator 488/500, Train metric: 1.8187
Estimator 489/500, Train metric: 1.8149
Estimator 490/500, Train metric: 1.8136
Estimator 491/500, Train metric: 1.8117
Estimator 492/500, Train metric: 1.8100
Estimator 493/500, Train metric: 1.8069
Estimator 494/500, Train metric: 1.8055
Estimator 495/500, Train metric: 1.8044
Estimator 496/500, Train metric: 1.8022
Estimator 497/500, Train metric: 1.8006
Estimator 498/500, Train metric: 1.7995
Estimator 499/500, Train metric: 1.7981

===== EXTREME CP (PGBM) =====
Coverage     : 98.925%

In [ ]:
def conformal_predictions_AlphaNet_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # Data conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base PGBM model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    def _safe_predict(m, X):
        p = m.predict(X)
        return p.ravel() if hasattr(p, "ravel") else np.asarray(p).ravel()

    # =========================================================
    # 3. PRECOMPUTE all LOO scores
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(_safe_predict(base_model, loo_X) - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")
    scores_calib = np.abs(_safe_predict(base_model, X_calib) - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small; fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = _safe_predict(base_model, Xte)
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("Settlement")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet PGBM complete in {_fmt_time(total_time)}")
    return summary_df

In [ ]:
conformal_predictions_AlphaNet_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

# **Conformal Predictions with TabNet**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'TabNet')
print(best_params)

In [ ]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.mean((y_arr >= int_pred[strat_name][:, 0]) & (y_arr <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.sqrt(mean_squared_error(y_arr, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        y_arr = np.array(y_test)
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_arr[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) &
                                           (y_arr[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan)
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages
class visualize:
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        y_true_np = np.array(y_true).ravel()
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')
        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)],
                 linestyle='--', color='blue', label='Ideal Prediction Line')
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')
        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()
        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]
        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

class TabNetRegressorCP(TabNetRegressor):
    def fit(self, X, y, *args, **kwargs):
        y = np.asarray(y)
        if y.ndim == 1:
            y = y.reshape(-1, 1)
        return super().fit(X, y, *args, **kwargs)

    def predict(self, X, *args, **kwargs):
        return super().predict(X).flatten()

In [ ]:
def conformal_predictions_NEXCP_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):
    warnings.filterwarnings("ignore")

    SEED = 123
    rng = np.random.default_rng(SEED)
    np.random.seed(SEED)

    if "verbose" in best_params:
        best_params = dict(best_params)
        best_params.pop("verbose", None)

    model_class = TabNetRegressorCP

    strategies = {
        "NEXCP-Split": "NexCP Split",
        "NEXCP-Full": "NexCP Full",
        "NEXCP-J+aB": "NexCP Jackknife+ aB",
        "NEXCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    y_train_np = np.asarray(y_train).ravel()
    y_test_np = np.asarray(y_test).ravel()

    # =========================
    # NexCP – Split (Weighted)
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    residuals = np.abs(y_train_np - yhat_train)
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NEXCP-Split"] = yhat_test
    int_pred["NEXCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Full
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train_np - yhat_train), 1 - alpha)

    y_pred["NEXCP-Full"] = yhat_test
    int_pred["NEXCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Jackknife+ aB
    # =========================
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train_np[idx])

        yhat_boot_train = model.predict(X_train[idx])
        yhat_test = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train_np[idx] - yhat_boot_train),
            1 - alpha,
        )

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NEXCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # =========================
    # NexCP – CV+
    # =========================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers, uppers, preds = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train_np[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train_np[cal] - y_cal), 1 - alpha)

        yhat_test = model.predict(X_test)

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NEXCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # =========================
    # Metrics
    # =========================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    summary = []

    print("\n===== NEXCP TABNET RESULTS =====")
    for s in strategies:
        cov = coverage(y_test_np, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_test_np, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_test_np, alpha)

        summary.append([strategies[s], cov, wid, rmse, cwc_val])
        print(f"{strategies[s]} | Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================
    # Plot + Excel Export
    # =========================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        sheet = "NEXCP_TabNet_Summary"
        base = sheet
        i = 1
        while sheet in wb.sheetnames:
            sheet = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        for s in strategies:
            fig, ax = plt.subplots(figsize=(10, 4))
            idx = np.arange(len(y_test_np))

            ax.scatter(idx, y_test_np, s=10, alpha=0.7, label="True")
            ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1], alpha=0.4)
            ax.plot(idx, y_pred[s], linewidth=1, label="Pred")

            ax.set_title(f"{strategies[s]} ({model_name})")
            ax.legend()

            buf = io.BytesIO()
            fig.savefig(buf, format="png")
            buf.seek(0)
            plt.close(fig)

            img = Image(buf)
            ps = f"NEXCP_TabNet_{s}"
            base = ps
            i = 1
            while ps in wb.sheetnames:
                ps = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(ps)
            ws.add_image(img, "A1")

        wb.save(excel_file_path)

    return summary_df


conformal_predictions_NEXCP_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50
)

In [70]:
y_train = pd.Series(y_train)
y_test = pd.Series(y_test)

conformal_predictions_online_super(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.817204  10.500237   7.142196  12.419635
1            Online CV+  0.838710  11.325353   7.142196  13.152022
2  Online Jackknife+ aB  1.000000  61.634029   9.696145  61.634029
3                 SAOCP  0.854839  12.387022   7.142196  14.185138
4                SF-OGD  0.951613  37.826807   7.142196  37.826807
5                  FACI  0.876344  13.821826   7.142196  15.530977
6            MFCS Split  0.817204  10.500237   7.142196  12.419635
7             MFCS Full  0.870968  18.169203  10.509773  20.513616

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.817204  10.500237   7.142196  12.419635
1            Online CV+  0.838710  11.325353   7.142196  13.152022
2  Online Jackknife+ aB  1.000000  61.634029   9.696145  61.634029
3                 SAOCP  0.854839  12.387022   7.142196  14.185138
4                SF-OGD  0.951613  37.826807   7.142196  37.826807
5                  FACI  0.876344  13.821826   7.142196  15.530977
6            MFCS Split  0.817204  10.500237   7.142196  12.419635
7             MFCS Full  0.870968  18.169203  10.509773  20.513616

In [71]:
conformal_predictions_COP(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    lr=0.05,
    T_burnin=50,
    scale=0.5
)

===== CONFORMAL OPTIMISTIC PREDICTION (TabNet) =====
Coverage : 83.333%
Avg Width: 11.186
RMSE     : 7.142
Final q  : 5.878

  Strategy  Coverage      Width      RMSE  Alpha    LR  Scale
0      COP  0.833333  11.186441  7.142196    0.1  0.05    0.5

In [72]:
conformal_predictions_EXTREME(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.05,
    calib_size=0.4,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30
)

===== EXTREME CONFORMAL PREDICTION (TabNet) =====
Coverage : 100.000%
Width    : 67.762
RMSE     : 12.398
q_extreme: 67.762
u        : 38.968
#Exceed. : 114

In [ ]:
def conformal_predictions_AlphaNet_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet — TabNet-specific variant.

    Handles:
    - TabNetRegressorCP wrapper (y reshape, predict flatten)
    - Removes 'verbose' from best_params if present
    - Precomputed LOO scores for speed
    - Progress tracking with tqdm + ETA
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # TabNet-specific: clean params & set model class
    # =========================================================
    tabnet_params = dict(best_params)
    tabnet_params.pop("verbose", None)           # TabNet doesn't use verbose here
    model_class = TabNetRegressorCP

    # =========================================================
    # Data conversion
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    # alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base TabNet model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**tabnet_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =========================================================
    # 3. PRECOMPUTE all LOO scores (KEY SPEEDUP)
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = (
        tqdm(range(n_calib), desc="    LOO precompute", leave=False)
        if HAS_TQDM else range(n_calib)
    )

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        preds_loo = base_model.predict(loo_X).ravel()
        scores_loo = np.abs(preds_loo - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet (multiple runs, keep best)
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores — no predict() call here
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")

    calib_preds = base_model.predict(X_calib).ravel()
    scores_calib = np.abs(calib_preds - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(Xte).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    # --- Prediction-interval plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("Settlement")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training-curves plot ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export (append-safe)
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        # ---- Summary ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- PI Plot ----
        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        # ---- Training Curves Plot ----
        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        # ---- Values ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet TabNet complete in {_fmt_time(total_time)}")
    return summary_df

In [74]:
conformal_predictions_AlphaNet_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/pile_load_gendy_data/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.05,
)

  [Info] n_calib=186 | alpha_min=0.0153
  [Step 2/9] Training base TabNet model...
epoch 0  | loss: 593.13068|  0:00:00s
epoch 1  | loss: 393.53003|  0:00:00s
epoch 2  | loss: 344.66843|  0:00:00s
epoch 3  | loss: 238.7894|  0:00:00s
epoch 4  | loss: 211.18793|  0:00:00s
epoch 5  | loss: 221.96721|  0:00:00s
epoch 6  | loss: 153.69017|  0:00:00s
epoch 7  | loss: 129.72523|  0:00:00s
epoch 8  | loss: 145.41841|  0:00:00s
epoch 9  | loss: 82.92272|  0:00:00s
epoch 10 | loss: 137.03496|  0:00:00s
epoch 11 | loss: 116.98508|  0:00:00s
epoch 12 | loss: 101.09461|  0:00:01s
epoch 13 | loss: 78.13171|  0:00:01s
epoch 14 | loss: 76.88547|  0:00:01s
epoch 15 | loss: 72.45139|  0:00:01s
epoch 16 | loss: 54.49234|  0:00:01s
epoch 17 | loss: 45.97492|  0:00:01s
epoch 18 | loss: 43.86858|  0:00:01s
epoch 19 | loss: 36.29791|  0:00:01s
epoch 20 | loss: 23.01759|  0:00:01s
epoch 21 | loss: 25.65808|  0:00:01s
epoch 22 | loss: 34.10342|  0:00:01s
epoch 23 | loss: 22.70222|  0:00:02s
epoch 24 | loss: 28.46221|  0:00:02s
epoch 25 | loss: 20.74058|  0:00:02s
epoch 26 | loss: 21.38337|  0:00:02s
epoch 27 | loss: 33.37183|  0:00:02s
epoch 28 | loss: 25.83593|  0:00:02s
epoch 29 | loss: 16.3913 |  0:00:02s
epoch 30 | loss: 12.91291|  0:00:02s
epoch 31 | loss: 17.40405|  0:00:02s
epoch 32 | loss: 14.11336|  0:00:02s
epoch 33 | loss: 7.62847 |  0:00:02s
epoch 34 | loss: 5.66111 |  0:00:03s
epoch 35 | loss: 8.25855 |  0:00:03s
epoch 36 | loss: 8.52366 |  0:00:03s
epoch 37 | loss: 9.63304 |  0:00:03s
epoch 38 | loss: 7.11376 |  0:00:03s
epoch 39 | loss: 3.82897 |  0:00:03s
epoch 40 | loss: 4.63576 |  0:00:03s
epoch 41 | loss: 3.14869 |  0:00:03s
epoch 42 | loss: 3.4097  |  0:00:03s
epoch 43 | loss: 4.39716 |  0:00:03s
epoch 44 | loss: 2.10913 |  0:00:03s
epoch 45 | loss: 2.95798 |  0:00:04s
epoch 46 | loss: 3.08196 |  0:00:04s
epoch 47 | loss: 1.89107 |  0:00:04s
epoch 48 | loss: 2.65287 |  0:00:04s
epoch 49 | loss: 2.3634  |  0:00:04s
epoch 50 | loss: 1.61746 |  0:00:04s
epoch 51 | loss: 1.39619 |  0:00:04s
epoch 52 | loss: 1.54967 |  0:00:04s
epoch 53 | loss: 1.24476 |  0:00:04s
epoch 54 | loss: 0.84502 |  0:00:04s
epoch 55 | loss: 1.01813 |  0:00:04s
epoch 56 | loss: 0.7578  |  0:00:04s
epoch 57 | loss: 0.81099 |  0:00:04s
epoch 58 | loss: 0.74577 |  0:00:04s
epoch 59 | loss: 0.75989 |  0:00:04s
epoch 60 | loss: 4.55965 |  0:00:05s
epoch 61 | loss: 1.46313 |  0:00:05s
epoch 62 | loss: 1.0639  |  0:00:05s
epoch 63 | loss: 0.77912 |  0:00:05s
epoch 64 | loss: 1.40389 |  0:00:05s
epoch 65 | loss: 1.30498 |  0:00:05s
epoch 66 | loss: 1.49368 |  0:00:05s
epoch 67 | loss: 1.6589  |  0:00:05s
epoch 68 | loss: 0.78614 |  0:00:05s
epoch 69 | loss: 1.04667 |  0:00:05s
epoch 70 | loss: 1.42084 |  0:00:05s
epoch 71 | loss: 0.97955 |  0:00:05s
epoch 72 | loss: 0.93154 |  0:00:05s
epoch 73 | loss: 1.15982 |  0:00:05s
epoch 74 | loss: 1.06083 |  0:00:05s
epoch 75 | loss: 1.42793 |  0:00:06s
epoch 76 | loss: 0.98965 |  0:00:06s
epoch 77 | loss: 0.91748 |  0:00:06s
epoch 78 | loss: 0.71897 |  0:00:06s
epoch 79 | loss: 0.82163 |  0:00:06s
epoch 80 | loss: 0.7165  |  0:00:06s
epoch 81 | loss: 0.94966 |  0:00:06s
epoch 82 | loss: 0.62293 |  0:00:06s
epoch 83 | loss: 1.85787 |  0:00:06s
epoch 84 | loss: 3.23932 |  0:00:06s
epoch 85 | loss: 1.99901 |  0:00:06s
epoch 86 | loss: 0.88751 |  0:00:06s
epoch 87 | loss: 1.72991 |  0:00:06s
epoch 88 | loss: 1.57493 |  0:00:06s
epoch 89 | loss: 0.9095  |  0:00:06s
epoch 90 | loss: 1.19426 |  0:00:07s
epoch 91 | loss: 1.34603 |  0:00:07s
epoch 92 | loss: 0.88746 |  0:00:07s
epoch 93 | loss: 0.80252 |  0:00:07s
epoch 94 | loss: 0.79154 |  0:00:07s
epoch 95 | loss: 0.86556 |  0:00:07s
epoch 96 | loss: 0.70308 |  0:00:07s
epoch 97 | loss: 0.85172 |  0:00:07s
epoch 98 | loss: 0.65934 |  0:00:07s
epoch 99 | loss: 0.60974 |  0:00:07s
  [Step 2/9] Done in 8s
  [Step 3/9] Precomputing 186 LOO score vectors...

    LOO precompute:   0%|          | 0/186 [00:00<?, ?it/s]

  [Step 3/9] Done in 6s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 296.1160 | Size: 279.7218 | α̃: 0.8197 | ⏱ 0.11s/epoch | ETA: 24s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 36.4243 | Size: 16.4243 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 14s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 36.4228 | Size: 16.4228 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 14s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 36.4241 | Size: 16.4241 | α̃: 1.0000 | ⏱ 0.10s/epoch | ETA: 14s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 36.4244 | Size: 16.4244 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 13s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 36.4248 | Size: 16.4248 | α̃: 1.0000 | ⏱ 0.11s/epoch | ETA: 13s
  ✓ Run 1 complete | Final loss: 36.4248

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 36.4209 | Size: 16.4209 | α̃: 1.0000 | ⏱ 0.10s/epoch | ETA: 13s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 36.4227 | Size: 16.4227 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 12s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 36.4228 | Size: 16.4228 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 11s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 36.4253 | Size: 16.4253 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 10s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 36.4228 | Size: 16.4228 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 9s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 36.4250 | Size: 16.4250 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 8s
  ✓ Run 2 complete | Final loss: 36.4250

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 36.4235 | Size: 16.4235 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 8s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 36.4234 | Size: 16.4234 | α̃: 1.0000 | ⏱ 0.08s/epoch | ETA: 7s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 36.4252 | Size: 16.4252 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 6s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 36.4214 | Size: 16.4214 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 5s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 36.4241 | Size: 16.4241 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 4s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 36.4241 | Size: 16.4241 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 4s
  ✓ Run 3 complete | Final loss: 36.4241

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 46.8766 | Size: 29.6436 | α̃: 0.8616 | ⏱ 0.09s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 36.4223 | Size: 16.4223 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 3s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 36.4210 | Size: 16.4210 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 36.4233 | Size: 16.4233 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 36.4249 | Size: 16.4249 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 36.4251 | Size: 16.4251 | α̃: 1.0000 | ⏱ 0.07s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 36.4251
  [Step 4/9] Training done in 14s
  [Step 5/9] Computing conformal intervals...

=======================================================
  ALPHANET CONFORMAL (TabNet)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 8.2119
  Coverage       : 81.720%
  Avg Width      : 16.4237
  RMSE           : 24.5425
  Total time     : 28s
    ├─ Precompute: 6s
    └─ Training  : 14s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet TabNet complete in 28s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.817204,16.423706,24.54249,0.05,1.0,20.0,27.66